- kie-parent-with-dependencies/pom.xml
Bug 1183481 - dashbuilder-bom import should be lower priority than jboss-integration-platform-bom import.
In kie-parent-with-dependencies pom.xml, the dashbulder-bom import has the higher priority than jboss-integration-platform-bom. However dashbuilder-bom actually will introduce a dependency on jboss-integration-platform-bom.
This will cause a problem that when dashbuilder-bom is older than jboss-integration-platform-bom, then it will force droolsjbpm project use an older integration-platform-bom. And dashbuilder is outside droolsjbpm project group.
This case happened when I build 6.1.0 ER4. For some reason, dashbuilder-0.2.0.CR2 can't be rebuilt and the latest droolsjbpm still need to use old dashbuilder. 
So the request here is to make dashbuilder-bom define after …
> Make dashbuilder-bom import later than jboss-integration-platform-bom

- kie-parent-with-dependencies/pom.xml
I've added AssertJ dependency (version 1.7.1). This will allow us easily migrate QE tests to community projects.
> Add AssertJ dependency

- pom.xml
* the 'jar' and 'test-jar' goals invoke execution of whole
lifecycle phase, which means all the plugins up to that
phase are executed multiple times during the build.
That includes for example enforcer and checkstyle plugins.
See https://maven.apache.org/plugins/maven-source-plugin/plugin-info.html
for more info.
* using the -no-fork goals will make sure that only these
goals are excuted and not the whole lifecycle again.
The output of the build in target/ dir is the same both
with and without this change.
@mbiarnes @ge0ffrey please take look just in case I missed something. I believe the change is safe, but its better if someone else reviews the changes before merging.
> maven-source-plugin: use -no-fork goals to avoid duplicated plugin executions

- kie-platform-bom/pom.xml
- pom.xml
Issue Keeper will allow us to connect tests with BZs or JIRAs using simple annotations. The test with such annotation is not run unless the related issue is resolved.
This is mostly used in jBPM engine tests which are being moved from QE test suite to jBPM repository and depend on the states of the related BZs.
> Add Issue Keeper dependency

- pom.xml
The latest Errai support version on 3.0.x is 3.0.5.Final-redhat-1. So let's update to 3.0.5.Final.
I hope that's ok.
> Update errai-cdi10 version to 3.0.5.Final to match support version

- pom.xml
* updates to local OBR (OSGi Bundle Repository) are not
necessary and they only prolong the build if the repository
(by default ~/.m2/repository/repository.xml) is large
@mariofusco please take a look as this is related to OSGi
> maven-bundle-plugin: disable OBR

- README.md
- ide-configuration/LICENSE-ASL-2.0-HEADER.txt
JBoss Inc. has not actually existed since 2006 :)
Here I suggest updating the copyright notices in this repository to refer to 'Red Hat, Inc. and/or its affiliates', if only because this is providing guidance to droolsjbpm projects on how to handle copyright notices.
Note that a Red Hat-specific copyright notice is not necessarily the best choice. Another possibility which you may wish to consider would be to refer generally to contributors to $projectname, e.g. 'Copyright $year Drools Authors'.
> Update copyright holder name

- pom.xml
Cargo is used just for integration tests, raising of version allows to create WebSphere standalone profiles.
> Upgrade Cargo plugin version to 1.4.18

- pom.xml
* 0.6.1 supports JDK 9 EA builds
(just the runtime itself, not jigsaw
or other Java 9 features)
> Upgrade revapi-java from 0.6.0 to 0.6.1

- pom.xml
Backport of #178. Touches only tests and makes them more reliable in case of parallel build.
> [GUVNOR-2410] disable UF git/ssh daemons for unit testing

- pom.xml
* this fixes recently spotted GWT compilation failures
for -webapps
CC @manstis
> Upgrade Guava from 19.0.0.jbossorg-1 to 19.0.0.jbossorg-2

- pom.xml
This fixes/workarounds the current issues with SNAPSHOT deploys.
> Use canonical URLs for Maven deploy repositories

- pom.xml
> [6.4.x] Use canonical URLs for Maven deploy repositories

- kie-third-party-bom/pom.xml
- pom.xml
[This use](https://github.com/uberfire/uberfire/blob/master/uberfire-commons/src/main/java/org/uberfire/commons/async/SimpleAsyncExecutorService.java#L75) of the `InitialContext` is causing errors in my tests, and `simple-jndi` (scope:test) fixes them. :) 
See for more info: http://fandry.blogspot.nl/2011/03/junit-based-integration-testing-with.html
> - avoiding JNDI errors when testing with uberfire code

- pom.xml
* IntegrationTest is just too long. IT is well established shortcut for
integration tests so makes sense to support it
> maven-failsafe-plugin: allow test classes to end also with "IT"

- pom.xml
Allows us to share version number between Cargo plugin and Cargo dependencies if they are used separately.
> Separated Cargo plugin version to property

- README.md
- RELEASE-README.md
- pom.xml
- script/repository-list.txt
* content of droolsjbpm-build-distribution was merged
into kie-wb-distributions. Having a separate
repository for just one module is an overkill
and only adds maintenance burden
> [DROOLS-1136] remove references to droolsjbpm-build-distribution repo

- pom.xml
* 2.3.0.Final brings initial Java 9 support
(no modules support, just works on the EA build 120)
> Upgrade org.mvel from 2.2.8.Final to 2.3.0.Final

- pom.xml
* this profile will only be executed on Java9+
(nothing changing for Java 8)
* it configures the NATIVE compiler for Drools
as ECJ (Eclipse Compiler for Java) does not
yet support Java 9
* adds the 'java.se.ee' module by default, as
APIs like javax.xml are not visible without it
@ge0ffrey please take a look and let me know what you think about this approach. It is far from ideal, as individual modules can overwrite the surefire/failsafe config and also the property, but it seems to fix quite a few issues I encountered, so it might be a good start.
> Add java9-only profile with custom fixes

- pom.xml
[This issue](https://issues.jboss.org/browse/ERRAI-963) describes why errai-js was being removed. The dependency management removed in this PR appears to be the only reference to errai-js in the droolsjbpm organization.
> ERRAI-963: Remove errai-js.

- kie-user-bom-parent/pom.xml
- pom.xml
* downgrade surefire&failsafe from 2.19.1 to 2.18.1
as 2.19.1 is buggy
* remove some config which is already brought in by
jboss-parent
> Fixes after IP BOM 7.0.0.CR4 upgrade

- pom.xml
https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/226
https://github.com/droolsjbpm/drools/pull/815
https://github.com/droolsjbpm/optaplanner/pull/200
https://github.com/droolsjbpm/jbpm/pull/487
https://github.com/droolsjbpm/droolsjbpm-integration/pull/509
https://github.com/droolsjbpm/kie-uberfire-extensions/pull/29
https://github.com/droolsjbpm/guvnor/pull/328
https://github.com/droolsjbpm/drools-wb/pull/209
https://github.com/droolsjbpm/jbpm-designer/pull/302
https://github.com/droolsjbpm/jbpm-console-ng/pull/432
https://github.com/droolsjbpm/kie-wb-distributions/pull/303
> [DROOLS-1216] add enforcer execution which bans blacklisted dependencies

- pom.xml
This reverts commit 21ce25c7e67755a71824aae2d9f58215bda29d97.
As ip-bom 6.0.7.Final contains an upgrade to <version.com.thoughtworks.xstream>1.4.9 and this 
contains Java 8 (*non*-backwards compatibile) code, which causes Webpshere to prevent the BPMS
webservice from deploying we have to revert this.
> Revert "upgraded jboss-ip-bom to 6.0.7.Final (#225)"

- pom.xml
* 1.5.0 brings support for EAP 6.4.7+
cc @mswiderski, @sutaakar
> Upgrade Cargo from 1.4.19 to 1.5.0

- pom.xml
Most external dependencies that used to be inside the gwt-dev.jar have now been unbundled. So we can get rid of the enforcer exception and can now manage exclusions using the standard maven mechanism.
> Upgrade to GWT 2.8.0-rc1

- pom.xml
* the failOnValidation is false by default since
most of the repos would fail on that. One repo
at the time, we need to fix them, override
the property there (temporarily) and once all
repos comply, we can also change the property
value here
> Use property to easily enable/disable checkstyle

- pom.xml
* the java command also contains the whole classpath, which
in our case means literally thousands of characters. Leaving
out the command makes the Maven build log much cleaner. It is
now also much easier to find the actual root cause of the
failed GWT compilation
The quest for clean GWT build logs in almost complete! Only one PR away :)
CC @csadilek
> gwt-maven-plugin: don't print entire java command on error

- pom.xml
* the failOnValidation is false by default since
most of the repos would fail on that. One repo
at the time, we need to fix them, override
the property there (temporarily) and once all
repos comply, we can also change the property
value here
> [6.5.x] Use property to easily enable/disable checkstyle

- pom.xml
See https://issues.jboss.org/browse/RHBRMS-2525
This overrides the version in ip-bom until we move to a version containing https://github.com/jboss-integration/jboss-integration-platform-bom/pull/327
> RHBRMS-2525: Business-central startup error: jGIT: Cannot run program 'bash'

- pom.xml
* Java 8 javadoc tool is more strict and fails the build.
This has been already fixed on newer branches
@manstis this should fix the PR builds on 6.3.x branch
> Fix build on Java 8: disable javadoc doclint

- pom.xml
Define a property for the latest Kie release, to be used in
droolsjbpm-knowledge/kie-api when checking API compatibility,
this allows productization to override this.
Latest Kie release property updated for consistency.
(cherry picked from commit bda543dda9bd0ec3b47cc1f9c03941f96f3c9178)
@psiroky Here you go :)
> RHBRMS-2552 Define a property for the latest Kie release.

- pom.xml
* WildFly 10 needs the 1.9.2 version
* needed to fix kie-server integ. tests
> Upgrade commons-beanutils from 1.8.3 to 1.9.2

- drools-bom/pom.xml
- pom.xml
All related PRs:
https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/274
https://github.com/droolsjbpm/drools/pull/902
https://github.com/droolsjbpm/droolsjbpm-integration/pull/631
> [DROOLS-898] rename drools-osgi to kie-osgi

- pom.xml
See https://issues.jboss.org/browse/GUVNOR-2722
This is the corollary of https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/294 for 6.5.x
(cherry picked from commit 98271587b5e2aa9153539329e55129bdec945fe9)
> [6.5.x] GUVNOR-2722: i18n: Host JSP's do not use correct Locale when the User has configured multiple

- pom.xml
See https://issues.jboss.org/browse/GUVNOR-2722
Ensure the ```LoginConstants_en.properties``` files are pushed to Zanata as a source file.
> GUVNOR-2722: i18n: Host JSP's do not use correct Locale when the User has configured multiple

- kie-bom/pom.xml
* kie-remote-common is still being used by kie-server,
so can not be removed at this point
Depends on https://github.com/droolsjbpm/droolsjbpm-integration/pull/685
> [JBPM-5366] remove most of kie-remote deps

- pom.xml
Correct element.
This is the corollary of https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/299 for 6.5.x
(cherry picked from commit 757b5b2c42251f88e2984e0b8fda40fc85f8d268)
> [6.5.x] GUVNOR-2722: i18n: Host JSP's do not use correct Locale when the User has configured multiple. Correct <includes> element

- pom.xml
Correct <includes> element.
@mbiarnes Hi, could you please approve?
I've tested with ```mvn zanata:push-module -B``` on ```kie-wb-distributions``` and it was fine.
> GUVNOR-2722: i18n: Host JSP's do not use correct Locale when the User has configured multiple. 

- kie-platform-bom/pom.xml
- pom.xml
Important note: the jgit upgrade requires Java7+, so this is also removing 1.6 support from the build.
> RHBPMS-4360: upgrade jgit version in order to avoid windows issues on high concurrency situations.

- README.md
- pom.xml
@mbiarnes could you please take a look? We need to upgrade the Jenkins jobs to use the newer Maven version. I believe I did most of the updates already, but if you find anything else that is missing, please let me know.
> Bump minimal required Maven version from 3.2.3 to 3.2.5

- ide-configuration/intellij-configuration/code-style/intellij-code-style_droolsjbpm-java-conventions.xml
This PR remove all empty lines before '}' symbol. For example:
```java
class SomeClass {
public void emptyMethod() {
}
public void someMethod() {
System.out.println("Hello World");
}
}
```
will be replaced to:
```java
class SomeClass {
public void emptyMethod() {
}
public void someMethod() {
System.out.println("Hello World");
}
}
```
To check this PR you can use IntelliJ editor:
File -> Settings -> Editor -> Code Style -> Java -> Blank Lines -> Keep Maximum Blank Lines -> Before '}':
> No empty lines before '}' allowed

- kie-user-bom-parent/pom.xml
- pom.xml
* CR5 brings JPA 2.1 + Hibernate 5.x
(upgraded from JPA 2.0 + Hibernate 4.x)
Please don't merge yet. All the IP BOM 7.0.0.CR5 PRs need to be merged together.
> Upgrade IP BOM to 7.0.0.CR5

- ide-configuration/intellij-configuration/code-style/intellij-code-style_droolsjbpm-java-conventions.xml
Following the discussion with @hasys on https://github.com/droolsjbpm/kie-wb-common/pull/634 I fetched the latest IDEA code-formatter. Much to my surprise it generated quite different code format to (a) I am used to, (b) that appears to be used by the vast majority of other developers.
This PR therefore reinstates spaces 'within' constructs that appeared to be the norm in older versions of this code formatter and most certainly older versions of IDEA. Possibly affected by dc77c93f9d60507382831612f6ddf0024abba02a
> Wrap and align implemented interfaces, method declaration parameters and method call parameters

- pom.xml
Test component - used for controlling of application servers during integration tests.
> Upgrade cargo-maven2-plugin from 1.5.0 to 1.6.2

- pom.xml
Hi,
I have updated revapi plugin to 0.8.1 and its Java extension to 0.13.1. It should be a lot better according to an author. Please do not merge it yet.
Thanks,
Marian
> Update revapi to 0.8.1/0.13.1

- pom.xml
Part of https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/342 about CheckStyle configuration. We had to split it because we need to use IDEA style plugin to reformat Stunner before CheckStyle will be configured.
> Stylecheck settings for Imports

- pom.xml
This enforcer execution takes considerable amount of time,
especially for big modules like showcases and webapps which
further slows down the webapp start. Full profile will be
executed on Jekins to make sure we catch all the duplicated
classes before the changes get merged.
> Execute ban-duplicated-classes in full profile

- pom.xml
Hello @psiroky @csadilek @mcimbora @ge0ffrey 
This PR is a proposal for upgrading the Roaster library we are currently using for java  files parsing/editing from current version in use: 2.13.0.Final (Feb, 2015) to the last version 2.19.4.Final (Dec, 2016).
Additionally to some bugs fixing, this version also benefits from an upgraded eclipse jdt compiler version that is used internally by Roaster.
To be honest I don't know exactly if we have a policy for this versions upgrades, but I believe it might be worth to do the update.
In general I checked in my local that everything works ok with the new library, and that the tests continues running etc. Only a minor change in a piece of code is needed to change, but all our internal APIs remains the same, and the same for all our tests, etc. (so …
> Roaster version update

- pom.xml
See https://issues.jboss.org/browse/RHBPMS-4602
See the JIRA comments for more details, but in summary:
```kie-parent``` ```pom.xml``` overrides ```xmlbeans``` version in ```jboss-integration-platform-bom``` from 2.6.0 to 2.3.0 - possibly for very good reason (that I am unaware). In order to use Apache POI with Microsoft Excel XLSX files we need to include ```org.apache.xmlbeans.XmlOptions``` that is not in IBM's JRE ```xml.jar```. However including ```xmlbeans-2.3.0.jar``` leads to duplicate ```org.w3c.dom.*``` classes and class loading problems.
> RHBPMS-4602: LinkageError during invocation of webservice workitem on WAS

- pom.xml
This is needed to fix the compatibility issue with Jandex 2.x.
It's just temporary override and shoud be removed once we upgrade
to IP BOM 7.0.0.CR7+.
> Upgrade Weld to 2.4.1.Final + Weld API to 2.4.Final

- pom.xml
This PR enables following modules:
**NeedBraces**
Checks for braces around code blocks.
if, else, for, while, do...while.
**EqualsHashCode**
Checks that classes that either override equals() or hashCode() also overrides the other. This checks only verifies that the method declarations match Object.equals(Object)} and Object.hashCode() exactly to be considered an override. This check does not verify invalid method names, parameters other than Object, or anything else.
**UnusedImports**
Checks for unused import statements. Checkstyle uses a simple but very reliable algorithm to report on unused import statements. An import statement is considered unused if:
- It is not referenced in the file. The algorithm does not support wild-card imports like import java.io.*;. Most IDE's provide very …
> Next portion of checkStyle modules

- pom.xml
* Java 8 javadoc tool is more strict and fails the build.
This has been already fixed on newer branches
> Fix build on Java 8: disable javadoc doclint (#273)

- pom.xml
See https://issues.jboss.org/browse/RHBPMS-4602
This is the corollary of https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/372 for 6.5.x
> [6.5.x] RHBPMS-4602: LinkageError during invocation of webservice workitem on WAS

- kie-bom/pom.xml
- pom.xml
Added Stunner's SVG support modules and their transitive dependencies.
See [this Jira ticket](https://issues.jboss.org/browse/JBPM-5389)
> JBPM-5389: Added Stunner SVG support modules.

- pom.xml
Hey @psiroky @manstis 
Adding the new lienzo-core version in both KIE and IP BOMs, so feel free to discard this one if finally the [other for the IP-BOM](https://github.com/jboss-integration/jboss-integration-platform-bom/pull/354) gets merged before the release. Thanks!
> JBPM-5728: Upgrade lienzo-core to 2.0.284-RELEASE.

- README.md
- pom.xml
By default jacoco java agent instruments classes on-the-fly during the test execution. This simplifies code coverage analysis a lot, as no pre-instrumentation and classpath tweaking is required.
However when using tests with custom classloader (tests that run with GwtMockitoTestRunner.class) the jacoco plugin shows zero coverage. This is because the ids of the classes in the report (jacoco.exec)
do not match the ids of the actual classes in the project (as GwtMockito uses proxies of the classes that are being tested). This problem has been solved by setting jacoco plugin to instrument
the classes before the test are run (and the proxies are created). This way exection report info is created from the original classes instead of the created proxies. The result is that the coverage of both …
> enable code-coverage for GwtMockito tests

- kie-user-bom-parent/pom.xml
- pom.xml
Testing the build time locally with empty local repo
(`mvn clean install -Dmaven.repo.local=maven-repo`) shows huge
improvement. 8min30s (without this change) vs 1min (with this change)
just for the build-bootstrap repo.
@mbiarnes, @ge0ffrey please take a look at let me know what you think. It definitely is not ideal, but I believe the speed up is worth it.
> Specifify the Maven Central before the JBoss.org repo to speed up builds

- pom.xml
@krisv, @porcelli I believe this should fix the issue (even though I can not reproduce it locally). I was looking at last Beta release and the WARs did not contain the bouncycastle deps, so it should be safe to exclude them.
This workaround can be removed once we upgrade to IP BOM 7.0.0.CR10+.
> Update com.lowagie:itext exclusions

- kie-bom/pom.xml
- pom.xml
Hey @manstis , @psiroky 
This is the upgrade to `lienzo-core` and `lienzo-tests` to version `2.0.287-RELEASE` for our 7.0.x branch. 
A few notes:
- Building only `uberfire` for `1.0.x `branch, the dependency versions resolved for lienzo stuff are a bit old. I dunno how to change this as it depends on a `CR2` IP BOM version already released. Anyway as our KIE-BOM uses the latest version, so the final version resolved for both kie and drools workbenches is fine (latest one),  the builds and webapps are working fine too.
- Once this gets merged, will create same PRs on master and for IP-BOM as well, so I understand all will be fine too.
Thanks!
> JBPM-5490: Upgrade to lienzo 2.0.287-RELEASE.

- script/utils/revapi-clean.sh
Hi, @psiroky,
I have created a script to simplify revapi ignores cleanup. It works this way:
`revapi-clean.sh <latestFinalCommunityVersion> <futureFinalCommunityVersion>`
For example:
`revapi-clean.sh 7.0.0.Final 7.1.0.Final`
It is sufficient to run it from the root of the repository which contains revapi-config.json files, since it will find such files recursively. In each of these files it will delete ignores and substitute versions in the comment.
This script should be run only on master if the following process is followed, for example:
1. After 7.0.0.Final is released in the community, run the script on master (7.0.x branch is already created) with parameters 7.0.0.Final and 7.1.0.Final. So master is tracking changes on master against 7.0.0.Final, while 7.0.x is tracking changes …
> Add a script for an easy way to clean revapi ignores

- pom.xml
- script/utils/revapi-clean.sh
Hi, @psiroky,
I have updated revapi configuration and fixed a small bug in revapi-clean script which I encountered when I was cleaning revapi ignores across the repositories. ~~I will put there all PRs which relate to this change.~~
Full PR set:
- kiegroup/droolsjbpm-knowledge#236
- kiegroup/jbpm#859
- kiegroup/droolsjbpm-integration#994
- kiegroup/optaplanner#314
- kiegroup/guvnor#459
- kiegroup/drools#1289
Thanks,
Marian
> Bump latest Final version to 7.0.0 and fix revapi-clean script

- README.md
- pom.xml
The common Pitest configuration will allow to run mutation coverage analysis in any module having `kie-parent` as its ancestor. This will make the tool available out of the box using a simple Maven invocation, which will be appreciated by QE, and developers might find this useful too.
> Add common Pitest configuration for mutation coverage analysis

- pom.xml
Hi @psiroky, @manstis, @ge0ffrey,
there are settings for CheckStyle to check is header correct or not. It will work as [here](https://github.com/kiegroup/jbpm-wb/blob/master/pom.xml#L35), but can be configurable for every repository.
> Configure checkstyle to check header if needed

- README.md
IntelliJ IDEA gives the option of reformating all changed files when committing from IntelliJ IDEA. Useful if you forgot to reformat after making changes to many files.
> Added another way you can reformat code in IntelliJ IDEA

- README.md
According to main [license file](https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/master/LICENSE-ASL-2.0.txt#L196).
> Remove extra spaces from License instruction

- README.md
Changes version of maven from 3.2.5 to 3.3.9.
This is due to #463 upgrading minimal maven version to 3.3.9.
> Update README file to use maven version 3.3.9

- script/branch-mapping.yaml
@mbiarnes please take a look. This should make the version upgrades easier. Instead of updating the 
`kie-build-helper-jenkins-plugin` every time, we would just need to update this file. One thing to remember is that we need to make sure the file is valid at all times otherwise bad things would happen :)
[jenkins skip ci]
> Add branch mapping file

- pom.xml
Hey @manstis , back-ported [this commit](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/500) into `7.3.x` as well. 
PS Just creating now the back-port for the commit in `kie-wb-common`, have to be merged together. Adding the PR link in a bit.
Thanks!
> JBPM-5967: Upgrade to lienzo 2.0.291-RELEASE.

- script/branch-mapping.yaml
The full repo name (including the org. unit) makes it easier to
understand which repo is actually being cloned. It also avoids the
issues with renamed org. units (e.g. uberfire -> AppFormer)
> branch-mapping: explicitly specify org. unit

- script/repository-list.txt
The repo was renamed some time ago and even tough the 'jbpm-console-ng'
still works as redirect, it causes minor issues here and there as the
two names actually differ.
@mbiarnes could you please take a look? Would this break something?
> repository-list: jbpm-console-ng -> jbpm-wb

- pom.xml
This is a mandatory step before merging the repos to form AppFormer single repository.
Related PRs:
https://github.com/AppFormer/uberfire/pull/784
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/487
https://github.com/kiegroup/drools/pull/1397
https://github.com/kiegroup/droolsjbpm-integration/pull/1135
https://github.com/kiegroup/guvnor/pull/484
https://github.com/kiegroup/kie-wb-common/pull/1005
https://github.com/kiegroup/drools-wb/pull/560
https://github.com/kiegroup/optaplanner-wb/pull/205
> AF-540: additional models to support generic data model move from drools to appformer

- script/release/kie-copyBinariesToNexus.sh
- script/release/kie-deployLocally.sh
Had to rename the variable deploy-dir to deployDir to prevent the execution of shell script from crashing.
Besides it is also required -T2 for 7.3.x branch to GWT compile.
> Script tweaks 7.3.x

- script/release/kie-copyBinariesToNexus.sh
- script/release/kie-deployLocally.sh
Had to rename the variable deploy-dir to deployDir to prevent the execution of shell script from crashing.
> changed variable name since old variable name wasn't found

- pom.xml
Resolves https://issues.jboss.org/browse/ROASTER-116 which causes generic parameters to be ignored in interface definitions
Part of:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/537
https://github.com/kiegroup/kie-wb-common/pull/1116
> PLANNER-870: Bump Roaster version to 2.19.5.Final

- pom.xml
(cherry picked from commit 1b3251f5db803460b55a00bab9f606106833ae03)
> RHBRMS-2870 - override of version.org.apache.httpcomponents.httpcore

- ide-configuration/intellij-configuration/code-style/intellij-code-style_droolsjbpm-java-conventions.xml
Always automatically wrapping method declaration parameters and call arguments is an inconvenient requirement. It [harms readability](https://github.com/jhrcek/guvnor/blob/a81b8781fca06bfdb99fb19a0ccc35314f206b13/guvnor-ala/guvnor-ala-registry-local/src/test/java/org/guvnor/ala/registry/tests/PageSortUtilsTest.java#L81-L101) and is a destructive operation as no IDE is able to revert it even if the rule is lifted. Better to fix the template as soon as possible before more [repositories](https://github.com/kiegroup/optaplanner-wb/pull/179) are [affected](https://github.com/kiegroup/guvnor/pull/478).
> Update IDEA code style not to wrap method params and call arguments

- kie-bom/pom.xml
- pom.xml
This is for JBPM-4480: https://issues.jboss.org/browse/JBPM-4480
One additional comment, the POM already contained and old com.wordnik.swagger dependency, but I couldn't really find where that dependency is actually used. If it's not used anywhere, we should remove it. If it is used, we should consider upgrading the dependency to "io.swagger".
> JBPM-4480: Add Swagger to KIE-Server REST API

- pom.xml
Hey @manstis @psiroky @mbarkley 
As commented on [this ticket](https://issues.jboss.org/browse/JBPM-6426), and trying to actually keep same IDE configurations when running on either `master` either `7.3.x`, this is the version upgrade to `10.1.0.Final` for errai's  embbeded WF stuff. 
I have tested some showcases and the workbench and it seems to work fine, lemme know this sounds good for you or am I missing some parts.
FYI [this is the PR](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/550) merged on master.
Thanks!
> JBPM-6426: Use of Errai's embedded Wildfly server 10.1.0.Final

- pom.xml
See https://issues.jboss.org/browse/GUVNOR-3394
Update to Lienzo version.
This is the corollary of https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/564 for 7.3.x
(cherry picked from commit 1bfb1faee6ebf0649b273ea8962061a470d4d859)
@psiroky @mbiarnes AFAIK I don't need a similar PR for ```ip-bom``` for 7.3.x.. please correct me it I am wrong.
> [7.3.x] GUVNOR-3394: [DMN Editor] Literal Expression: Line breaks for multiple line expressions

- pom.xml
@psiroky @ryanzhang reverted the xnio override as we will do this upgrade in jboss-ip-bom
> Revert "override of version of xnio to align to EAP 7.0.8"

- ide-configuration/eclipse-configuration/code-style/eclipse-code-style-organize-imports_droolsjbpm-java-conventions.importorder
Hi
@ge0ffrey, @manstis, @psiroky, @tarilabs, @mswiderski,
It looks like I forgot to update Eclipse Imports file since it is separate one from main formatter. Here are the fix. (In general the only change is STATIC imports have to be on the bottom). Now it is fully synchronized with IDEA.
> Update Eclipse imports formatter

- pom.xml
These changes should currently be enough for the simple `mvn clean install` build. We will likely need further fixes for tests - but that can be done separately.
> JDK9 build compatibility fixes

- kie-platform-bom/pom.xml
- pom.xml
Please see this [PR](https://github.com/kiegroup/kie-soup/pull/8) for general discussion.
> AF-593+: Move uberfire-maven-utils to kie-soup.

- RELEASE-README.md
- pom.xml
- script/utils/revapi-clean.sh
Hi, @psiroky,
here is the change we spoke about. So I put back the version we check against to 7.0.0.Final and removed version.org.kie.latestFinal.release property too since it is useless now. I have also gone through revapi-config.json files and updated their ignores and their comments so they are not confusing.
PR set:
- https://github.com/kiegroup/droolsjbpm-knowledge/pull/278
- https://github.com/kiegroup/jbpm/pull/1053
- https://github.com/kiegroup/drools/pull/1573
- https://github.com/kiegroup/droolsjbpm-integration/pull/1255
- https://github.com/kiegroup/optaplanner/pull/348
Thanks,
Marian
> Change version to check against with revapi to 7.0.0.Final

- README.md
This resulted as fix from the conversation https://github.com/kiegroup/droolsjbpm-build-bootstrap/commit/491f5f5a4203d1f9e67b6e289e1458e0cef26b85#commitcomment-25477525
> README.md: updated minimal java from 6 to 8

- script/git-add-remote-gerrit.sh
- script/git-clone-others.sh
- added a script to create a remote pointing to Gerrit for pushing the tags.
- stabilized clone-script. Now it works better and stable.
- Gerrit doesn't need kie-eap-modules and droolsjbpm-build-integration tags
> added and modified scripts to push tags to Gerrit

- README.md
Going through GWT plugin setup in Eclipse I found some very probably not up to date things:
* my comment about same versions of GWT SDKs at https://github.com/kiegroup/droolsjbpm-build-bootstrap/commit/783318a087cb5d0218e4e07bf789d7ba3f010047#commitcomment-25476906
* fixed link to GWT plugin page download.
> Setup fixes in README.md

- pom.xml
A new Metadata index had been added. Its intention is to have an alternative to Lucene backend so you can use it, for instance in Openshift or on premise without zookeeper/helix to replicate those assets.
The idea is to maintain the same Lucene API but to transform it to Elasticsearch compatible messages. There is no need to change any Lucene Query to make it work. There is a class called **LuceneIndexEngine** that is not **public** anymore because it was very coupled to Lucene FS implementation so now it's behind a new Interface called **IndexProvider**. It tries to generate an abstraction for indexing a querying an index engine using domain objects and not lucene documents anymore.
The default indexing engine is Lucene but you can change it with a System Property:
- …
> [AF-549-elastic]: modified dependencies to add elasticsearch

- kie-bom/pom.xml
This pr updates the dependencies for the FormGenerationIntegrationTest. This pull-request is to be merged together with https://github.com/kiegroup/kie-wb-common/pull/1288.
@pefernan, @triceo, @jhrcek, @rsynek could you please review?
> update dependencies for FormGenerationIntegrationTest

- script/branch-mapping.yaml
- script/repository-list.txt
@psiroky Could you please review this? The primary goal of this PR set is to replace AppFormer/uberfire with kiegroup/appformer in the build (content being presently almost identical). I figgured it made sense to add kie-soup to the repositories list now too, but I don't have to do that here.
> AF-593+: Move uberfire to appformer.

- pom.xml
avalon-framework is unused dependency declared (only in) jbpm-designer-backend. It's a project that is no longer maintained since 2004. I'm removing it to remove useless jar from final kie-wb.war
Depends on https://github.com/kiegroup/jbpm-designer/pull/710
> Remove useles avalon-framework dependency

- pom.xml
during kie 7.5.0.Final release appformer was upgraded by error to 2.2.0.Final instead of 2.1.0.Final. So 2.2.0.Final is existing. We should upgrade the appformer develop version to 2.2.1-SNAPSHOT
> upgraded appformer version

- drools-bom/pom.xml
@mariofusco @lanceleverich Hi, Could you please look that if we need to add kie-pmml into drools-bom?
QE reports an issue on https://issues.jboss.org/browse/RHDM-240 .
> RHDM-240 Adding kie-pmml artifact into drools-bom

- pom.xml
@mbiarnes @psiroky @krisv @sutaakar 
here are the changes to upgrade version of jackson to 2.8+ as it seems to be required on EAP 7.1
Though this won't work on lower versions like 7.0 or Wildfly 10 and 10.1. I tested this with Wildfly 11 and it does work as expected - tests where only covering what is reported in the jira
PR with code change in droolsjbpm-integration
> DO NOT MERGE - RHBPMS-5026 - Version difference of jackson artifacts

- pom.xml
Hey @manstis @tiagodolphine 
Here is the upgrade to latest lienzo release. See [JBPM-6700](https://issues.jboss.org/browse/JBPM-6700) for more details about it.
Notice created the PR for IP BOM as well  https://github.com/jboss-integration/jboss-integration-platform-bom/pull/415
Thanks!!
> JBPM-6700: Upgrade to Lienzo 2.0.295-RELEASE

- kie-bom/pom.xml
Hey @manstis @jomarko @hasys 
This commit removes the Stunner's `BasicSet` stuff. It's not being used at all, even nobody cares about it, so as I'd been incrementally moving all shapes from this module into the `stunner-client-shapes` one, this can be removed at this point.
Please merge at same time as:
- https://github.com/kiegroup/kie-wb-common/pull/1362
- https://github.com/kiegroup/kie-wb-distributions/pull/670
- https://github.com/kiegroup/jbpm-wb/pull/971/
See [JBPM-6748](https://issues.jboss.org/browse/JBPM-6748).
Thanks!
> JBPM-6748: Removed Stunner's BasicSet artifacts from KIE BOM

- README.md
- script/checks/repo-dep-tree.pl
- script/git-all.sh
- script/mvn-all.sh
With this option I can run `mvn-all.sh clean install --target-repo=drools-wb` and only build the repositories that `drools-wb` depends on:
* kie-soup
* appformer
* droolsjbpm-build-bootstrap
* drlx-parser
* droolsjbpm-knowledge
* drools
* jbpm
* optaplanner
* droolsjbpm-integration
* kie-wb-playground
* kie-wb-common
* drools-wb
which is 12 out of 20. This can be handy when building a local feature that spans multiple repositories. See the full dependency graph generated by the `repo-dep-tree.pl` script.
> Add --target-repo option to git-all.sh and mvn-all.sh

- drools-bom/pom.xml
- kie-bom/pom.xml
- optaplanner-bom/pom.xml
@porcelli could you review?
https://issues.jboss.org/browse/RHDM-349
Related to:
https://github.com/kiegroup/optaplanner-wb/pull/250
https://github.com/kiegroup/drools-wb/pull/799
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/692
https://github.com/kiegroup/kie-wb-distributions/pull/685
https://github.com/kiegroup/kie-wb-playground/pull/46
https://github.com/kiegroup/jbpm-wb/pull/980
https://github.com/kiegroup/kie-wb-common/pull/1411
> [RHDM-349]: Added drools playground dependency

- pom.xml
sets the new org.eclipse.bpmn2 version until we align with platform bom changes. 
related to https://github.com/jboss-integration/jboss-integration-platform-bom/pull/419
> JBPM-6794 - updating eclipse.bpmn2 version

- script/repository-list.txt
@romartin @krisv both repositories have to be in repository list, as the DSL Jenkins groovy script works with the repository-list.txt. The upstream repos are defined depending where is the rep to build listed. If it is not in this list all repositories are build as upstream-repos, and this doesn't make any sense.
> added lienzo-core and lienzo-tests into repository-list

- kie-bom/pom.xml
(cherry picked from commit 67d99eb46911be478c7c4aee3a9aef71b242b483)
https://issues.jboss.org/browse/RHDM-344
https://issues.jboss.org/browse/DROOLS-2314
Bundle:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/708
https://github.com/kiegroup/kie-wb-distributions/pull/689
> [7.5.x] DROOLS-2314 : Standalone decision central is not branded

- pom.xml
@manstis this is missing enforcer ignore rule for ban-duplicated-classes
> RHDM-250: adding enforcer ignore for ASM classes (#684)

- kie-bom/pom.xml
- pom.xml
This again is the another round of reverted https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/682 
This PR is a set of PRs across kiegroup repositories based on @mbarkley own wf11 branches work.
This PR and dependent ones will need to change jenkins CI build command for wildfly11 profile instead of wildfly10 profile
> RHDM-251 - Wildfly 11 upgrade

- pom.xml
Hey @ederign @mbiarnes @mareknovotny @manstis 
Well not sure if I'm wrong or how things are really building fine on the `7.7.x` branch... but it seems it's using the wrong version for uberfire artifacts! 
So the build for `7.7.x` now it's broken as from merging https://github.com/kiegroup/kie-wb-common/pull/1559, but it's due to `kie-wb-common` is still using uberfire `2.4.0-SNAPSHOT` instead of `2.4.1-SNAPSHOT`, right? See https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/7.7.x/pom.xml#L53
Anyway please if you agree this should be merged asap, lemme know. Thanks!
> [7.7.x] Use the Uberfire 2.4.1-SNAPSHOT version for the 7.7.x branch.

- kie-bom/pom.xml
(cherry picked from commit 1024e66cc0b65f538bc9c943aaa770fe34f8d33e)
https://issues.jboss.org/browse/AF-1079
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/731
https://github.com/kiegroup/appformer/pull/272
https://github.com/kiegroup/kie-wb-common/pull/1565
https://github.com/kiegroup/drools-wb/pull/841
> [7.7.X] AF-1079: Empty 'Validation errors' popup in Decision/Business Central

- kie-bom/pom.xml
@mswiderski Please take a look.
Part of https://github.com/kiegroup/droolsjbpm-integration/pull/1460
> JBPM-7226: Delete Kie server ee6 assembly and references

- pom.xml
Freemarker needs to be added into dependencyMgmt so that product build can override the dependency version to productize version.
> RHPAM-1017 Add freemarker into dependencyMgmt

- RELEASE-README.md
1. The correct link seems to be https://mojo.redhat.com/docs/DOC-68317.
2. The SSH key generation instructions below the link are the exact copy
of the document so the document is redundant.
> Remove broken link from release readme

- pom.xml
The requirement now is to use only Final versions of dependencies for community or product.
> upgraded to errai Final

- drools-bom/pom.xml
Related PRs:
kiegroup/droolsjbpm-build-bootstrap#766
kiegroup/drools-wb#873
The new artifact is a result of splitting drools-wb-webapp into two
modules, which is a standard layout with the new tbroyer GWT plugin.
> AF-1243: Add new drools-wb-ui artifact

- pom.xml
This will allow to depend on `javax.enterprise:cdi-api` without having to
exclude `javax.el:javax.el-api` and
`javax.interceptor:javax.interceptor-api` to satisfy the
"banDuplicateClasses" Enforcer rule in situations where the project
also depends on `org.jboss.spec.javax.el:jboss-el-api_3.0_spec`
and `org.jboss.spec.javax.interceptor:jboss-interceptors-api_1.2_spec`.
> Exclude transitive Java EE APIs that are obsoleted by JBoss Specs

- pom.xml
org.apache.tomcat.catalina also used maven property version.org.apache.tomcat, so rename the properties to avoid the unwanted override.
> Fix tomcat-dbcp properties to avoid overriding catalina version

- optaplanner-bom/pom.xml
Reasons for removing:
1. optaplanner-bom should only contain org.optaplanner.* artifacts.
2. There should be minimal overlaps between BOMs and
kie-decision-playground is already in drools-bom.
Nothing should break since from all optaplanner-related repos,
kie-decision-playground is only used in optaplanner-wb and that imports
drools-bom.
> PLANNER-1063 Remove kie-decision-playground from optaplanner-bom

- pom.xml
Wait with merge until all valid repositories are updated.
@rsynek 
We now have to check against latest product release (7.0 DM/PAM) which means that we have to check against 7.5.0.Final community release (not 7.7.0.Final since that won't contain DM release).
> Change revapi to check against 7.5.0.Final

- kie-user-bom-parent/pom.xml
- pom.xml
moved org.apache.sshd and org.eclipse.jgit to jboss-ip-bom
org.sonatype.sisu.sisu-guice: removed dependency since it is already in jboss-ip-bom
org.quartz-scheduler: moved to jboss-ip-bom
org.wildfly.arquillian: moved to jboss ip-bom
org.apache.httpcomponents.httpclient: moved httpmime to jbos-ip-bom
org.jboss.arquillian.selenium: moved to jboss-ip-bom
org.mvel: moved to jboss ip-bom
org.jboss.remoting: moved to jboss-ip-bom
org.jboss.forge.roaster: moved to jboss-ip-bom
org.jboss.resteasy: moved to jboss ip bom
> updated to use jboss-integration-platform-bom 8.1.0.CR2

- kie-user-bom-parent/pom.xml
- pom.xml
jboss-ip-bom 8.1.0.Final is identical to 8.1.0.CR2 - we had to do this as prod will work only with Final versions. In future there won't be anymore CRs for jboss-ip-bom - only Final versions.
> upgraded jboss-ip-bom to 8.1.0.Final

- kie-user-bom-parent/pom.xml
- pom.xml
(cherry picked from commit 96157a8425b1fb25548f18d563d5e2306e59500f)
jboss-ip-bom 8.1.0.Final is identical to 8.1.0.CR2 - we had to do this as prod will work only with Final versions. In future there won't be anymore CRs for jboss-ip-bom - only Final versions.
> upgraded jboss-ip-bom to 8.1.0.Final (#815)

- drools-bom/pom.xml
- kie-bom/pom.xml
https://issues.jboss.org/browse/DROOLS-2846
https://issues.jboss.org/browse/DROOLS-2847
Pretty much just moving code for the 99% of the changes and then 1% of refactorings to make the move easier.
Bundle:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/800
https://github.com/kiegroup/drools/pull/2021
https://github.com/kiegroup/kie-wb-common/pull/2054
https://github.com/kiegroup/drools-wb/pull/916
https://github.com/kiegroup/optaplanner-wb/pull/301
https://github.com/kiegroup/kie-wb-distributions/pull/795
> DROOLS-2846 : Move Verifier core from drools-wb to drools

- kie-bom/pom.xml
Follow up for: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/800
https://issues.jboss.org/browse/DROOLS-2848
https://issues.jboss.org/browse/DROOLS-2849
Bundle:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/809
https://github.com/kiegroup/kie-wb-common/pull/2073
https://github.com/kiegroup/drools-wb/pull/919
https://github.com/kiegroup/optaplanner-wb/pull/302
https://github.com/kiegroup/kie-wb-distributions/pull/802
> DROOLS-2848 : Make the Verifier Web Worker connector reusable for different V&V types

- pom.xml
Cherry-pick latest selenium version update and timeout stabilizations to 7.11.x
Part of ensemble:
https://github.com/kiegroup/kie-jenkins-scripts/pull/341
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/846
https://github.com/kiegroup/kie-wb-distributions/pull/825
> BAQE-96: Update version of selenium test dependencies (#840)

- pom.xml
DON'T MERGE before https://github.com/jboss-integration/jboss-integration-platform-bom/pull/425 was merged and the IP BOM 8.2.0.Final was released and KIE reps updated
> BXMSPROD-38: moved org.eclispse.jdt to jboss-ip-bom

- pom.xml
@pszubiak @mareknovotny can somebody please review and merge this PR?
- introduces a new dependency org.jboss.integration:narayana-tomcat, which will replace org.jboss.narayana.tomcat:tomcat-jta (that one will be removed later, once all repositories switch to narayana-tomcat)
- overrides tomcat-dbcp with a patched version uploaded to jboss nexus https://repository.jboss.org/nexus/content/groups/public/org/apache/tomcat/tomcat-dbcp/9.0.12.jbossorg-00001
> BAQE-441 Provide dependencies versions for KIE server integration with Tomcat and Narayana

- pom.xml
the PR #852 was accidental closed - the camel upgrade PR was raise again.
Known high severity security vulnerability detected in org.apache.camel:camel-core = 2.21.0 defined in pom.xml.
pom.xml update suggested: org.apache.camel:camel-core ~> 2.21.1.
> upgrade due to security vulnerability reported by github

- pom.xml
The previously uploaded version didn't contain information about dependencies.
> Update tomcat-dbcp to a version containing pom with dependencies

- pom.xml
@rsynek
We now have to check against latest product release (7.1 DM/PAM) which means that we have to check against 7.11.0.Final community release.
> BAQE-730 - Change revapi to check against 7.11.0.Final

- pom.xml
the version org.apache.cxf was upgraded in jboss-ip-bom to 3.2.5. 
This caused test failures in droolsjbpm-integration/kie-spring-boot.
This commit overrides this version.
> override version of org.apache.cxf

- kie-bom/pom.xml
@adrielparedes this change seems necessary after classifiers have changed in this PR:
https://github.com/kiegroup/kie-wb-distributions/commit/219f9a66bfe2584915e0bfbf7e935919f1c7ca20
Should be merged with:
https://github.com/kiegroup/kie-jenkins-scripts/pull/365
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/875
https://github.com/kiegroup/jbpm/pull/1366
https://github.com/kiegroup/droolsjbpm-integration/pull/1627
https://github.com/kiegroup/kie-wb-distributions/pull/841
> Fix classifiers after wildfly14 upgrade

- pom.xml
JBEAP 7.2 alignment:
this upgrades byte-buddy to 1.8.17. We saw that this dependency is needed by kie-wb-commons, so it cannot be removed yet.
> upgrade byte-buddy

- pom.xml
Please merge this AFTER the kie reps were upgraded to use jboss-ip-bom 8.4.0.Final
since this has the mockito version 2.23.4 which has dependency to this version of byte-buddy
> upgraded byte buddy because needed by mockito upgrade

- kie-bom/pom.xml
- kie-user-bom-parent/pom.xml
- pom.xml
moved org.apache.cxf and its dependencies to jboss-ip-bom
moved org.apache.lucene to jboss-ip-bom
moved org.wildfly and org.wildfly.core to jboss-ip-bom
moved io.undertow to jboss-ip-bom 8.4.0.Final
(cherry picked from commit 1ff9d7a0be3ac11d3872470d48f557a759003412)
(cherry picked from commit 3cf0c43cf0e12bd62e3e40ada51ba5c61f9b0cdb)
upgraded jboss-ip-bom
JBPM-8113: Review the Forms Annotation processors (from Pere Fernandez - at already exists)
this commit has not to be moved to upstream
(cherry picked from commit bfff01b65643114b7e2dcbf89a49a8aae9c87051)
> hibernate and jboss-ip-bom upgrade

- pom.xml
Depends on https://github.com/jboss-integration/jboss-integration-platform-bom/pull/443. After ip bom of version 8.4.0.Final is released, these kiegroup PRs can be merged once they refer to this new ip bom.
@mbiarnes @mareknovotny here is the alignment of dependencies with Wildfly. They are now using jboss spec 2.3 of jaxb-api and jaxws-api. I have also made some cleaning of dependencies for JDK11. After this has passed and merged, maybe we can push version declarations of these 2 dependencies even to IP BOM, as it is the case now with spec 2.2. But I decided to do it this way first since I am not familiar with any other frontend repositories regarding workbench etc. Maybe jaxb-api and jaxws-api is not even used there.
PR set:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/9 …
> Align JAXB and JAXWS APIs with Wildfly

- pom.xml
Alignment to JBEAP 7.2
Only merge this when the version of jboss-ip-bom was upgraded to 8.4.0.Final
(https://github.com/jboss-integration/jboss-integration-platform-bom/pull/440)
> moved com.google.guava and its dependencies to jboss-ip-bom

- pom.xml
kiegroup/droolsjbpm-build-bootstrap/pull/908
kiegroup/kie-wb-common/pull/2385
kiegroup/optaplanner-wb/pull/322
kiegroup/jbpm-wb/pull/1271
kiegroup/kie-wb-distributions/pull/861
kiegroup/optaweb-employee-rostering/pull/218
To my understanding, Eclipse's M2Eclipse plugin has difficulties mapping Antrun plugin execution to the build lifecycle. This results in a project configuration error reported to Eclipse IDE users even when working with engine projects (drools, jbpm, optaplanner) where the workaround for [ERRAI-1101](https://issues.jboss.org/browse/ERRAI-1101) isn't needed. To improve the getting started experience for community contributors working in the Eclipse IDE I'm moving the Antrun plugin execution to a profile that's not activated by default.
Projects that use Errai's …
> PLANNER-1328: Make ERRAI-1101 workaround optional

- pom.xml
Hi @romartin, @mareknovotny, @ge0ffrey, @etirelli,
I upgraded JavaAssist dependency to fix GwtMockito issues on Java 11 (see exception below). I tested it on Stunner repository and this error is fixed, let's try FullDonwnstream build to check is it causes any issues.
Thank you!
Version of JavaAssist is set in jboss-integration bom repository, but we can't execute fulldownstream build from it so, not sure should I upgrade it there, or we can override this dependency in this repo.
<details>
<summary>ClassNotFoundException in GwtMockito</summary>
<pre>Error Message
caught an exception while obtaining a class file for com.google.gwtmockito.GwtMockito
Stacktrace
java.lang.ClassNotFoundException: caught an exception while obtaining a class file for com.google.gwtmockito.GwtMockito
at …
> JBPM-8029: Align javaassist for support GwtMockito in Java11

- pom.xml
@rsynek
We now have to check against latest product release (7.3 DM/PAM) which means that we have to check against 7.18.0.Final community release.
> BAQE-928 - Change revapi to check against 7.18.0.Final

- pom.xml
Please merge this only when the new jboss-ip-bom 8.5.1.Final is out since the version of ch.qos.logback will be coming from ip-bom
> PLANNER-1436: phase 2

- script/release/kie-upgrade-branch-auxiliary-reps.sh
script upgrades master branches of kie-docker-ci-images, kie-benchmarks and kie-cloud-tests to next development version or upgrades master branches and creates new branches with a new development version - needed after each community release
- master has to bump up (one branch)
- sometimes master have to bump up and a new branch has to be created (two branches)
> refactored sript for auxiliary reps

- pom.xml
This is an upgrade https://github.com/kiegroup/kie-gwthelper-maven-plugin/releases/tag/1.1  which fixes to have correct content for kie-gwthelper-maven-plugin when @gitgabrio externalized the plugin into individual repository.
This is not depending on any parent or dependency hierarchy from kiegroup repositories.
> upgrade of kie-gwthelper-maven-plugin to the latest 1.1

- kie-bom/pom.xml
Several things happen in this PR that can't be split in several commits:
All the information about spaces and repositories used to live in system.git project. That project makes that every change that was need to be done locks repository for all users. 
Now, all the information about each space is stored inside config.git in every space. So lock will happen only for that space and not for the whole file system. Also migration tool was modified to include previous changes.
When you delete a Space or Repository, they are marked to be deleted. User will continue working as it was used to. Nothing from user perspectiva but they way that deleted spaces are shown. 
* A deleted Repository disappear from Library View and is marked to be deleted with a flag in config.git
* A deleted Space doesn't …
> [AF-1792]  Migration of space information from system.git to config.git + HA improvements

- script/release/kie-createReleaseBranches.sh
- script/release/update-version-all.sh
version upgrades that doesn't update automatically and have to be changed "manually" now are changed directly in the update-version-all.sh script - so this is not needed any more in kie-createReleaseBranches.sh  script
With these changes the update of versions work:
- it respects the new kie-soup-bom and uberfire-bom in droolsjbpm-build-bootstrap
- is respects the own version number of uberfire
> fixed update script and kie-createReleaseBranches.sh

- pom.xml
Failsafe plugin was unintentionally removed in https://github.com/kiegroup/droolsjbpm-build-bootstrap/commit/fc094e3b4d14edde0a09c4de95f01ee5e8902326#diff-600376dffeb79835ede4a0b285078036L1415 .
The result is that majority of integration tests were not executed since then.
> Return failsafe plugin back to default plugin executions

- pom.xml
- jacoco:report, jacoco:merge and sonar:sonar are configured in pom.xml instead of triggering them directly
- sonarcloud-related properties are read from environment variables that are set by Jenkins
- PR analysis is moved to a separate profile
> BAQE-1001 Unify reporting to SonarCloud under KIE parent

- pom.xml
Change-Id: Ic16e566d6703420c168050c48367f68a0a8ea72f
Repeating https://github.com/jboss-integration/jboss-integration-platform-bom/pull/444 to current kie-parent
https://issues.jboss.org/browse/RHPAM-1873
> RHPAM-1873: upgrade of cxf to 3.2.5

- pom.xml
kieAllBuild-master failed because of 
22:53:16 [WARNING] Rule 0: org.apache.maven.plugins.enforcer.BannedDependencies failed with message:
22:53:16 Found Banned Dependency: commons-logging:commons-logging:jar:1.1.1
22:53:16 Use 'mvn dependency:tree' to locate the source of the banned dependencies
commons-logging is brought in as transitive dependency from resteasy-jaxrs.
> added exclusion for banned dependency

- pom.xml
Newer library causes error during initialization of example projects. After investigating and fixing the issue, we will upgrade it again.
> AF-2097: Upgrade JGit library - rollback due to jGit error

- pom.xml
@rsynek
We now have to check against latest product release (7.4 DM/PAM) which means that we have to check against 7.23.0.Final community release.
> BAQE-1039 - Change revapi to check against 7.23.0.Final

- script/repository-list.txt
This change is needed because openshift-drools-hacep requires kie-maven-plugin which is located in droolsjbpm-integration repository.
> Move hacep repo after droolsjbpm-integration

- pom.xml
All classes in `org.apache.kafka.common.message` package are autogenerated and duplicated. They are available in both `kafka-clients` and `kafka-clients-test` artifact.
Hacep integration tests module use both so the build fails
@jiripetrlik @desmax74 @mbiarnes @mareknovotny
> Add exclusion of org.apache.kafka.common.message.* classes to duplicated class check

- pom.xml
- script/release/update-version-all.sh
- uberfire-bom/pom.xml
The commit https://github.com/kiegroup/droolsjbpm-build-bootstrap/commit/34dfe2ec1c3634a0d06db0b16f49b57e5e085301 moved uberfire-bom from appformer into droolsjbpm-build-bootstrap, with uberfire-bom version kept as Appformer version. Since this is not very user-friendly and breaks product build, this PR proposes a change of uberfire-bom version to KIE version to align it with the rest of the BOMs.
Related PRs: 
- https://github.com/kiegroup/appformer/pull/746
- https://github.com/kiegroup/droolsjbpm-integration/pull/1873
- https://github.com/kiegroup/drools-wb/pull/1198
- https://github.com/kiegroup/jbpm-designer/pull/856
- https://github.com/kiegroup/jbpm-wb/pull/1375
- https://github.com/kiegroup/kie-uberfire-extensions/pull/87
- https://github.com/kiegroup/kie-wb-common/pull/2780
- …
> changed uberfire-bom version to KIE version

- pom.xml
@mbiarnes @MarianMacik Here is the global definition, once merged I will remove version definition from droolsjbpm-integration.
9.0.22 is the latest Tomcat version
> Add globally managed version of Tomcat application server

- script/git-clone-others.sh
- script/utils/revapi-clean.sh
@mbiarnes I have added 2 new options to the git-clone-others.sh file:
* Ability to run it only on a subset of repositories using either `--repo-list=` or `--target-repo=` option. Now it is aligned with other scripts like git-all.sh and mvn-all.sh. *.bat versions lack these parameters, so I decided to not add it to the git-clone-others.bat either.
* I have added `--add-upstream-remote` option so repositories can be cloned and an upstream remote is added (kiegroup) which might be handy in case there is a need to pull the newest upstream changes and rebase on that, for example when creating a PR.
I really have no idea what the `--target-repo=` option is for, so I just wanted to ask.
And please double check it if I didn't break anything. But it should be backward compatible.
> Further automate revapi cleaning

- pom.xml
This PR upgrades the cargo version to 1.7.6. It is needed due to the issue https://codehaus-cargo.atlassian.net/browse/CARGO-1488.
It is causing [1] in community selenium tests [2]
[1]
02:43:40,010 ERROR [org.uberfire.ext.security.management.BackendUserSystemManager] (MSC service thread 1-5) UserManagementService destroy failure: java.lang.RuntimeException: Properties file for users not found at './standalone/configuration/application-users.properties'.
[2]
https://github.com/kiegroup/kie-wb-distributions/tree/master/business-central-tests/business-central-tests-gui/src/test/java/org/kie/wb/selenium/ui
> BAQE-982: Upgrade version.org.codehaus.cargo to 1.7.6

- pom.xml
@manstis @ederign @Rikkola @danielezonca 
See https://issues.jboss.org/browse/DROOLS-4443
New version contains the "inheritance" goal, that allow GWT inheritance analysis.
> [DROOLS-4443] Switch kie-gwthelper-plugin to 1.3 version.

- pom.xml
Change-Id: I85767d32feee0b03d3e110a7546f81678041f617
Trying to upgrade to the latest upstream which is backward compatible with our code
> upgrade jackson and jackson-databind to 2.9.9

- pom.xml
Related PRs:
https://github.com/kiegroup/droolsjbpm-knowledge/pull/399
https://github.com/kiegroup/drools/pull/2511
https://github.com/kiegroup/optaplanner/pull/533
https://github.com/kiegroup/jbpm/pull/1529
https://github.com/kiegroup/openshift-drools-hacep/pull/27
https://github.com/kiegroup/droolsjbpm-tools/pull/97
https://github.com/kiegroup/kie-wb-playground/pull/79
https://github.com/kiegroup/jbpm-designer/pull/860
> BXMSPROD-491 clean duplicated management of dependencies in KIE-PARENT

- script/release/kie-removeReleaseBranchesGerrit.sh
adds the new sh script that removes created release branches, only in case the target=productized
> BXMSPROD-524: added shell script for removing branches on Gerrit

- pom.xml
Fixes this mess:
https://stackoverflow.com/questions/58014229/mvn-quarkusdev-throws-noclassdeffounderror-could-not-initialize-class-org-j
> Upgrade wildfly-common to 1.5 and xnio to 3.7 and restEasy to 4.2.0.Final

- script/release/kie-removeReleaseBranchesGerrit.sh
If productized is selected in release-jobs the remote name pointing to Gerrit is *origin*.
The remote Gerrit in these cases is pointing to nowhere since it doesn't exist.
> fixed right remote name

- pom.xml
@rsynek
We now have to check against latest product release (7.5 DM/PAM) which means that we have to check against 7.26.0.Final community release.
> BAQE-1114 - Change revapi to check against 7.26.0.Final

- pom.xml
so its compatible with hibernate-validator (as it is declared in that pom already)
**TODO: if this breaks any of the GWT builds, the GWT repositories should overwrite version.javax.validation in their root pom back to 1.0.0.GA.**
> Upgrade javax.validation from 1.0.0.GA to 2.0.1.Final 

- pom.xml
Change-Id: I0a0db79b253ff9c600bc1b98da48f4f38bcb98b9
https://issues.jboss.org/browse/AF-2150
> AF-2150: updating freemarker to 2.3.28

- pom.xml
This pull request is an upgrade of JFreeChart library.
This also allows to remove jcommon dependency.
Requires these changes on optaplanner repo: https://github.com/kiegroup/optaplanner/pull/576
> Bump version.org.jfree.jfreechart from 1.0.19 to 1.5.0

- pom.xml
Change-Id: I0f276845c458ab32700508223bf6268bf55b327f
https://issues.jboss.org/browse/BXMSPROD-507
Dependent PRs in kie-soup and appformer
* kiegroup/appformer/pull/831
* kiegroup/kie-soup/pull/117
> BXMSPROD-507: upgrade netty to 4.1.42.Final

- pom.xml
Change-Id: I5b91f8f06eec01797af0066f0ed078a568d1fc80
https://issues.jboss.org/browse/BXMSPROD-571
> BXMSPROD-571: removal of com.mchange.c3p0 dependency management

- pom.xml
(cherry picked from commit 1ddd5122b3c20c1c9f037fac241c2638ed8df0b9)
- Backport for 7.30.x community version.
- Original PR : https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1109
- Upgraded bootstrap to v3.4.1.
> [7.30.x] RHDM-874 :CVE-2018-20676 bootstrap: XSS in the tooltip data-viewport attribute [rhdm-7.2.1]

- optaplanner-bom/pom.xml
Part of PR set:
https://github.com/kiegroup/optaplanner/pull/619
> PLANNER-1682: Remove optaplanner-core-gwt module

- pom.xml
- Upgraded bootstrap to v3.4.1 (PR : https://github.com/gwtbootstrap3/gwtbootstrap3/pull/526).
- This upgrade fixes the XSS vulnerability on tooltips,popover etc present in business central. (see release notes - https://github.com/twbs/bootstrap/releases/tag/v3.4.1).
- When a malicious script is inserted, The user page will fail to load and they can see error as shown in screenshot.
> RHDM-874: CVE-2018-20676 bootstrap: XSS in the tooltip data-viewport attribute [rhdm-7.2.1]

- pom.xml
- Removing git-gwtbootstrap from dependancies since we already are using gwtbootstrap3 (https://github.com/gwtbootstrap3/gwtbootstrap3).
> Removing git-gwtbootstrap from the kie-parent-pom

- pom.xml
Change-Id: I4f875d4b88ec51b1aa78d3b62c6753e4878e9006
https://issues.jboss.org/browse/AF-2333
Downstream PR kiegroup/kie-wb-common/pull/3020
> AF-2333: Apache mina-core library depMgmt removed

- script/release/10_uploadBinariesToFilemgmt.sh
Path change since now binaries for filemgmt.jboss.org (drools. jbpm and optaplanner webs) are fetched from the local deploy directory (after a build) instead of /target directories.
> Tar deploy dir

- optaplanner-bom/pom.xml
Following Spring Boot (and Quarkus) conventions it becoming a quickstart instead and it's going into a versionless, non-released repository (hopefully as a spring guide).
We'll likely add other examples on kogito-examples.
> Remove optaplanner-spring-boot-example artifactId

- pom.xml
Jira: https://issues.redhat.com/browse/PLANNER-1753
Prerequisite for: https://github.com/kiegroup/optaplanner/pull/640
> [PLANNER-1753] Bump and add Spring Boot dependency management for optaplanner-integration

- pom.xml
Restores ability to measure code coverage in SonarCloud, so far WITHOUT transitive coverage between modules.
- uses jacoco.exec files per module instead of a global one
- creates XML report from jacoco.exec files before invoking Sonar scanner
- also removes outdated code-coverage profile and common jacoco-maven-plugin configuration as it collides with this change.
- tested locally with OptaPlanner project:
https://sonarcloud.io/dashboard?id=org.optaplanner%3Aoptaplanner
> BAQE-1212 Report code coverage in XML format

- pom.xml
This change returns back a single jacoco.exec file. For XML report generation this approach leverages jacoco ant goal "report", as jacoco-maven-plugin does not provide enough control of scope of the report.
> BAQE-1054 Enable cross-module coverage for XML reports

- pom.xml
Some repositories contain classes with the same fully-qualified name, resulting in a failure during coverage report generation.
> Revert BAQE-1054

- pom.xml
@rsynek
We now have to check against latest product release (7.7 DM/PAM) which means that we have to check against 7.33.0.Final community release.
> BAQE-1267 - Change revapi to check against 7.33.0.Final

- pom.xml
Returns back https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1186, which had to be reverted due to breaking PR check build of some repositories.
Please note that FDB does not help here, as SonarCloud-related profiles are activated only on PR checks. Reasons for that are as follows:
- not to overwrite SonarCloud statistics of every downstream repository for a change in upstream repository
- avoid introducing unnecessary delay into the FDB
This PR differs from https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1186 in adding exclusions of certain patterns of classes that are present in more that one module of some KIE group project. Such a duplicity ends up with a fast fast error by Jacoco report task.
Tested with every SonarCloud-enabled repository in KIE group.
> BAQE-1054 Enable cross-module coverage with JaCoCo XML reports in SonarCloud

- kie-bom/pom.xml
- uberfire-bom/pom.xml
KOGITO-879: Define State Control API
KOGITO-880: Create JSInterop layer for StateControl API
KOGITO-881: Integrate State Control API in Stunner to handle Undo & Redo
I had to add two new modules:
- `appformer-kogito-api`: to keep the base kogito APIs (for now only StateControl APIs are there), since this module may grow and the state control is a development linked to the envelope, I thoght it was a good idea to have it there.
- `kie-wb-common-stunner-kogito-runtime-common`: to keep the shared classes nedded for the stunner editor runtimes. Other modules under kie-wb-common-stunner-kogito are also present on BC.
@ederign @tiagobento @jomarko would you mind take a look?
This is part of an ensemble, please merge with:
https://github.com/kiegroup/kogito-tooling/pull/66 …
> KOGITO-879 KOGITO-880 KOGITO-881: State Control API (undo/redo)

- pom.xml
Reverts kiegroup/droolsjbpm-build-bootstrap#1202
due issue
`Caused by: java.lang.IllegalStateException: Can't add different class with same name: org/jbpm/prediction/pmml/AbstractPMMLBackend`
https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/droolsjbpm-integration-pullrequests/695/consoleText
@rsynek please look at it and resend
> Revert "BAQE-1054 Enable cross-module coverage with JaCoCo XML reports in SonarCloud"

- pom.xml
We use set of librares for xsd -> java -> js conversion.
Such conversion is is needed in DMN and Scenario Simalation marshaling modules to be able run editors without application server.
This PR unify the versions of used libraries.
For more details see https://issues.redhat.com/browse/DROOLS-5057
Ensemble together with:
- https://github.com/kiegroup/kie-wb-common/pull/3209
- https://github.com/kiegroup/drools-wb/pull/1324
> DROOLS-5057: Unify xsd -> java -> js conversion

- jbpm-bom/pom.xml
- A new jbpm-db-scripts module has been included to hold the db scripts for jbpm and quartz.
> [BAQE-1323] DB scripts move to a new module along with refactoring work in jbpm-installer

- pom.xml
See https://issues.redhat.com/browse/KOGITO-1441
@mbiarnes We'll need a new release of the Jsonix plugin to remove this `-SNAPSHOT` dependency for the next `kiegroup` release. Please see the linked PR.
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1229
- https://github.com/kiegroup/gwt-jsonix-schema-compiler/pull/6
> KOGITO-1441: [DMN Designer] JsonixGWTPlugin: JSUtils.toAttributesMap(…) null check

- pom.xml
Ensemble:
- https://github.com/kiegroup/appformer/pull/936
- https://github.com/kiegroup/kie-wb-common/pull/3256
For more details see https://issues.redhat.com/browse/DROOLS-5128
> DROOLS-5128: Update com.google.elemental2 and com.google.jsinterop versions

- downstream.production.stages
- downstream.stages
https://issues.redhat.com/browse/BXMSPROD-757
It's not needed for upstream build since the tests are skipped
Tested here https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/PROD/job/upstream-downstream/job/drools.downstream/4
> BXMSPROD-757 firefox driver path

- pom.xml
Fixup for #1288.
The dependency was used at some point when working on kiegroup/optaplanner#764 but is not needed in the ended.
> PLANNER-1003: Remove unneeded JUnit dependency

- pom.xml
This reverts https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1234 which broke `drools-wb` build.
@kiegroup/gatekeepers could you take a look and, possibly, merge?
> Revert "BXMSPROD-685: upgrade of org.jboss-weld (#1234)"

- kie-pmml-bom/.gitignore
- kie-pmml-bom/pom.xml
- pom.xml
@danielezonca @mariofusco @jiripetrlik 
Scope of this PR is to add the kie-pmml-bom.
Such bom is needed by kie-maven-plugin and will be used by kie-pmml-new module, replacing all the dependency management defined in this latter
> Drools 5258 - Create kie-pmml-bom

- pom.xml
upgraded version.org.jboss.spec.javax.ejb.jboss-ejb-api_3.2_spec
upgraded version.org.jboss.spec.javax.el.jboss-el-api_3.0_spec
upgraded version.org.jboss.spec.javax.enterprise.concurrent
upgraded version version.org.jboss.spec.javax.interceptor.jboss-interceptors-api_1.2_spec
upgraded version.org.jboss.spec.javax.jms
upgraded version.org.jboss.spec.javax.security.jacc.jboss-jacc-api_1.5_spec
upgraded version.org.jboss.spec.javax.servlet.jsp
upgraded version.org.jboss.spec.javax.websocket
upgraded version.org.jboss.spec.javax.ws.rs.jboss-jaxrs-api_2.1_spec
> BXMSPROD-685: upgrade of different version of org.jboss.spec

- optaplanner-bom/pom.xml
The Kogito and Quarkus teams have requested to externalize the OptaPlanner Quarkus extension to fix a cylic build issue (and because it's a layered product).
These are the bom additions. If approved, they can already be safely merged.
https://issues.redhat.com/browse/PLANNER-1973
> PLANNER-1973 Externalize Quarkus OptaPlanner

- pom.xml
This is just rebased branch on below change by @dependentbot
Bumps `version.org.keycloak` from 4.8.3.Final to 9.0.3.
Updates `keycloak-core` from 4.8.3.Final to 9.0.3
- [Release notes](https://github.com/keycloak/keycloak/releases)
- [Commits](https://github.com/keycloak/keycloak/compare/4.8.3.Final...9.0.3)
Updates `keycloak-common` from 4.8.3.Final to 9.0.3
- [Release notes](https://github.com/keycloak/keycloak/releases)
- [Commits](https://github.com/keycloak/keycloak/compare/4.8.3.Final...9.0.3)
Signed-off-by: dependabot[bot] <support@github.com>
> Bump version.org.keycloak from 4.8.3.Final to 9.0.3

- pom.xml
That dependency does not appear in product builds, so it has zero impact on product.
In the quarkus extensions, it's a dependency of quarkus-core that gets removed later on magically.
It's a blocker for the quarkus-optaplanner externalization.
> The enforcer plugin shouldn't trigger banDuplicatedClasses in quarkus-ide-launcher

- pom.xml
- This will help us to package jboss-msc as part of container and remove dependancies on specific EAP provider
- Related to wildfly 18 upgrade 
Related or Merge with : https://github.com/kiegroup/kie-wb-distributions/pull/1038
> RHPAM-2985 : Added Jboss MSC to avoid specific EAP dependacies

- script/git-clone-others.sh
@ge0ffrey if not merged this commit it works properly and checks-out tha 7.x master branch but in logs still appear -b master. It is nicer to have this in the logs.
> echo in logs of correct branch for optaplanner when cloning master

- script/release/update-version-all.sh
If optaplanner is checked out to **master** the update-version-all script will fail.
optaplanner has to be checked out to **7.x** when all other reps are checked out to master.
Problem we had: when all reps where checked out to **master** and the script run, optaplanner **master** was updated and lost his version **8.0.0-SNAPSHOT**. 
The optaplanner 7.x should have always the same version as all other **master** branches.
> makes script fail when optaplanner is not checked out to 7.x branch

- pullrequest.stages
this should remove kie-jpmml-integration as upstream project for all PRs.
If this is also wanted for FDBs and CDB this line: 
**projectCollection.removeAll(['kie-jpmml-integration'])**
should be added to [FDB stages](https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/master/downstream.stages) and [CDB stages](https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/master/compilation.stages)
> removes kie-pmml-integration for all PRs as upstream rep

- Jenkinsfile
- Jenkinsfile.nightly
- pom.xml
because some parts of the build (optaplanner repo) are not compatible with the older version.
We'll have to announce this before merging.
> Upgrade Maven minimum version from 3.5.2 to 3.6.3

- pom.xml
https://issues.redhat.com/browse/JBPM-9227
Merge together with:
- https://github.com/kiegroup/jbpm/pull/1696
- https://github.com/kiegroup/droolsjbpm-integration/pull/2150
- https://github.com/kiegroup/kie-wb-distributions/pull/1045
> JBPM-9227: upgrade maven cargo plugin for newer Wildlfy 19 container

- Jenkinsfile
- Jenkinsfile.nightly
https://issues.redhat.com/browse/BXMSPROD-881
just adding `@7.39.x` (being 7.39.x the branch name from the library's repo) Jenkins will take version from there
https://github.com/kiegroup/jenkins-pipeline-shared-libraries/tree/7.39.x
A new job has been created in order to automatize it https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/PROD/job/replace-jenkins-pipeline-shared-libraries/
@mbiarnes will add jenkins-pipeline-shared-libraries to branch creation and will call the new job after creating branches.
related with: https://github.com/jboss-integration/rhba/pull/28
> BXMSPROD-881 shared libraries pointing to 7.39.x branch

- kie-pmml-bom/pom.xml
@danielezonca @jiripetrlik
see https://issues.redhat.com/browse/DROOLS-5143
This first step is just declaring Mining model modules inside kie-pmml dependencies bom
> [DROOLS-5143] Declaring Mining Model modules version

- pom.xml
We now have to check against latest product release (7.8 DM/PAM) which means that we have to check against 7.39.0.Final community release.
> BAQE-1488 - Change revapi to check against 7.39.0.Final

- .ci/compilation.stages
- .ci/new.downstream.stages
- .ci/pullrequest.stages
- .ci/upstream.stages
https://issues.redhat.com/browse/BXMSPROD-911
depends on https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/94
Test job https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/new-PR-optaweb-employee-rostering-master.pullrequests/31
The `Linux - Pull Request` result is not right since https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/94 was not merged at the time the job was triggered
> BXMSPROD-911 adapted to take forked projects with different name

- pom.xml
Merge together with https://github.com/kiegroup/jbpm/pull/1719
> [JBPM-9269] ibm jdk: Missing sun.security classes for mock-server tests

- pom.xml
https://issues.redhat.com/browse/JBPM-9216
Merge together with https://github.com/kiegroup/appformer/pull/1020
Unifiying on one version of postgresql while upgrading
> JBPM-9216: Upgrade of JDBC postgresql driver to 42.2.14

- pom.xml
backporting https://issues.redhat.com/browse/JBPM-9216 to 7.39.x
merge together with https://github.com/kiegroup/appformer/pull/1023
> [7.39.x] JBPM-9216: Upgrade of JDBC postgresql driver to 42.2.14

- pom.xml
https://issues.redhat.com/browse/JBPM-9231
There is new version of Apache Batik 1.13
Merge together with https://github.com/kiegroup/droolsjbpm-integration/pull/2183 and https://github.com/kiegroup/jbpm-designer/pull/885
> JBPM-9231: upgrade to the latest Apache Batik 1.13

- pom.xml
Hey @ederign @karreiro 
Just moving from `appformer-parent` to `kie-parent` the version of the monaco editor webjar, so it can be also used by the BPMN editor.
Thanks!
Assembly:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1429
- https://github.com/kiegroup/appformer/pull/1012
- https://github.com/kiegroup/kie-wb-common/pull/3372
> BAPL-678: BPMN Editor - Syntax Highlighting

- script/branched-7-repository-list.txt
- script/release/update-version-all.sh
**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1004
realted to:
https://github.com/kiegroup/optaweb-vehicle-routing/pull/368
https://github.com/kiegroup/optaweb-employee-rostering/pull/499
https://github.com/kiegroup/kie-docs/pull/2850
https://github.com/kiegroup/kie-wb-distributions/pull/1063
- Adds `optaweb-employee-rostering` and `optaweb-vehicle-routing` repos on the 7.x branched repo list.
- Updates the `update-version-all.sh` script to read from the list above and check if 7.x is checked out for all repos on that list.
<details>
<summary>
</summary>
* <b>a compile downstream …
> BXMSPROD-1004: Add optawebs on the 7.x branch list

- .ci/compileDownstreamBuild.properties
- .ci/fullDownstreamBuild.properties
- .ci/pullrequest.properties
https://issues.redhat.com/browse/BXMSPROD-996
https://github.com/kiegroup/appformer/pull/1056
https://github.com/kiegroup/drools/pull/3118
https://github.com/kiegroup/kie-wb-common/pull/3429
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1476
<details>
<summary>
</summary>
</details>
> BXMSPROD-996 remove multithread build for appformer, drools and kie-wb-common

- pom.xml
- Update netty 4.1.51 which includes both security fixes and AArch64 performance improvements
- Refer release notes for detail:
- https://netty.io/news/2020/05/13/4-1-50-Final.html
- https://netty.io/news/2020/07/09/4-1-51-Final.html
> Upgrade to Netty 4.1.51.Final

- pom.xml
There is not used `log4j:log4j` dependency management. We and other dependencies uses `org.apache.logging.log4j` groupId which is next major version of the library.
This is an evidence  https://github.com/jboss-integration/jboss-integration-platform-bom/commit/a551c6c04d6af64f8f8d21e74ccf152c9a3d6133#diff-600376dffeb79835ede4a0b285078036R231 that the version property and dependencyManagement https://github.com/jboss-integration/jboss-integration-platform-bom/commit/a551c6c04d6af64f8f8d21e74ccf152c9a3d6133#diff-600376dffeb79835ede4a0b285078036R1948-R1953 were added for purpose of Modeshape project, which is not related to kiegroup projects.
<details>
<summary>
</summary>
* <b>a pull request</b> please add comment: <b>Jenkins retest …
> removed managed log4j:log4j dependency as not used

- ide-configuration/eclipse-configuration/code-style/eclipse-code-style-formatter_droolsjbpm-java-conventions.xml
Although diff shows a lot of changes, I just modify the wrapping setting for method invocations to use indentations rather than tabular form
> Aligning eclipse formatter with intellij one

- Jenkinsfile
**JIRA**:
https://issues.redhat.com/browse/BXMSPROD-1011
* https://github.com/kiegroup/kie-jenkins-scripts/pull/821
<details>
<summary>
</summary>
</details>
> BXMSPROD-1011 Jenkinsfile expected job names replaced

- .ci/compilation.stages
* link 2
* link 3 etc.
<details>
<summary>
</summary>
</details>
> BXMSPROD-1024: droolsjbpm-tools is not any more excluded in reps for cdb

- Jenkinsfile
two things here, first https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/891fa6089b5ed79107a5ed6ec5d178f1ecd8eb37/Jenkinsfile#L59 was wrong (we copied functionality from there) and the second one folders are removed during PR in order to save space. We didn't have it into account.
<details>
<summary>
</summary> …
> fixing problems with sonar cloud step

- pom.xml
**JIRA**: [BAQE-1567](https://issues.redhat.com/browse/BAQE-1567)
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1485
* https://github.com/kiegroup/appformer/pull/1058
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/467
* https://github.com/kiegroup/drools/pull/3132
* https://github.com/kiegroup/jbpm/pull/1764
* https://github.com/kiegroup/droolsjbpm-integration/pull/2255
* https://github.com/kiegroup/optaplanner/pull/953
We now have to check against latest product release (7.8 DM/PAM) which means that we have to check against 7.39.0.Final community release.
> BAQE-1567 - Change revapi to check against 7.44.0.Final

- kie-pmml-bom/pom.xml
@danielezonca @mareknovotny  @jiripetrlik
See https://issues.redhat.com/browse/DROOLS-5688
This PR declare the version of org.kie/kie-pmml-api
Needed by https://github.com/kiegroup/drools/pull/3162
> [DROOLS-5688] Declaring trusty-pmml public API

- kie-pmml-bom/pom.xml
Fixing duplicated declaration which was warned by maven:
```
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.kie:kie-pmml-bom:pom:7.46.0-SNAPSHOT
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.kie:kie-pmml-api:jar -> duplicate declaration of version ${version.org.kie} @ line 73, column 19
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.kie:kie-pmml-commons:jar -> duplicate declaration of version ${version.org.kie} @ line 83, column 19
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.kie:kie-pmml-api:jar:sources -> duplicate declaration of version …
```
> removed duplicated declarations in kie-pmml-bom

- pom.xml
**JIRA**: [JBPM-9410](https://issues.redhat.com/browse/JBPM-9410)
Added swagger parser dependency needed for testing swagger.json composition
> [JBPM-9410] Add swagger parser dependency

- .ci/pull-request-config.yaml
optaplanner configuration missing from https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1512
<details>
<summary>
</summary>
</details>
> maven connection error configuration optaplanner

- .ci/project-dependencies.yaml
- script/repository-list.txt
[AF-2675](https://issues.redhat.com/browse/AF-2675)
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1520
* https://github.com/kiegroup/kie-jenkins-scripts/pull/853
<details>
<summary>
</summary>
* <b>an upstream …
> AF-2675: remove rep droolsjbpm-tools from builds and pipelines

- kie-soup-bom/pom.xml
- script/repository-list.txt
- uberfire-bom/pom.xml
https://issues.redhat.com/browse/DROOLS-5783
Description:
The goal of this PR is to cleanup `droolsjbpm-integration` repo from unnecessary relation with other repos (in this case `appformer`). It is a sort of followup of this PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1505 that tries to do the same but it has been partially reverted because of some remaining usages
Details of this part of the PR:
- adding `kie-soup-security-utils`
- removing `uberfire-security-backend`
- change `repository-list.txt` accordingly
@mareknovotny @Ginxo @lucamolteni @mariofusco 
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1517
* https://github.com/kiegroup/kie-soup/pull/163
* …
> [DROOLS-5783] Make droolsjbpm-integration repo independent from appformer

- pom.xml
**JIRA** [JBPM-9410](https://issues.redhat.com/browse/JBPM-9410)
**Merge with** [JBPM:1174](https://github.com/kiegroup/droolsjbpm-integration/pull/2274)
Added swagger parser dependency needed for testing swagger.json composition
> (GSS) [7.44.x] [RHPAM-3219] No Model definition in KIE Server Swagger API 

- script/git-clone-others.sh
- script/utils/revapi-clean.sh
**[BAQE-1547](https://issues.redhat.com/browse/BAQE-1547)**: 
- git-clone-others.sh - adding upstream remote branch should always be done
- New script added to update old kie version property automatically
> [BAQE-1547] git-clone-others.sh - adding upstream remote branch should always be done + new update kie old version script

- uberfire-bom/pom.xml
**JIRA**:
[AF-2689](https://issues.redhat.com/browse/AF-2689)
Adds the dependency for dashbuilder-js new project.
Merge with:
https://github.com/kiegroup/appformer/pull/1076
> AF-2689: Adding Dashbuilder JS Artifact

- script/release/10c_optaplanner_upload_filemgmt.sh
since [optaplanner symlinks **latest** and **latest final** ](https://docs.jboss.org/optaplanner/release/) point to version **8.0.0.Final**, when uploading binaries of 7.x versions to filemgmt.jboss.org it is not needed any more to create these symlinks. <br>**latest** and  **latestFinal**  should always (only in optaplanner) point to **8.0.0.Final**
> removed sym link creation

- script/release/10a_drools_upload_filemgmt.sh
the key (**$1** in script) for uploading binaries to filemgmt,jboss.org was missing when uploading drools binaries
> added missing key for uploading binaries to filmgmt.jboss.org

- .github/workflows/generate_files.yml
There's no way to modify PR adding files generated by the flow due to security problems. So, the only way I've found is to trigger the flow on a `push` event and create a new PR to modify image and repository-list files.
You can check a automatically generated PR by this flow 
https://github.com/Ginxo/droolsjbpm-build-bootstrap/pull/32
<details>
<summary>
</summary> …
> generate files flow

- .ci/compilation.stages
- .ci/fullDownstream.stages
- .ci/pullrequest.stages
- .ci/upstream.stages
- .github/workflows/generate_files.yml
- Jenkinsfile
- Jenkinsfile.buildchain
I would have to find alternatives to "Build Chain Generate Files / File Generation" from a forked project. Meanwhile please consider the solution for the getProjectTriggering problem and I will treat "Build Chain Generate Files / File Generation" in a different one.
<details>
<summary>
</summary> …
> getProjectTriggering job error solved

- .ci/project-dependencies.yaml
Hi @mbiarnes, @mareknovotny,  @Ginxo I removed kie-wb-playground dependency from kie-wb-common because this dependency don't make sense to me and make addition instabilities. Do I miss something there? Is kie-wb-common really depends on kie-wb-playground?
I executed `mvn dependency:tree | grep "kie-wb-pla"` on `kie-wb-common` root directory and nothing was found, so I assume it should be safe to delete kie-wb-playground.
<details>
<summary>
</summary>
* <b>a full production downstream build</b> please add comment: …
> wb-common should not depend on wb-playground

- pom.xml
Due to recent jira authentication changes we decided to stop using issue-keeper tool for preventing test method run. It was replaced by simple '@Ignore' junit annotations.
For more details see:
- https://issues.redhat.com/browse/JBPM-9542
- https://github.com/ibek/issue-keeper
**JIRA**: https://issues.redhat.com/browse/JBPM-9542
* https://github.com/kiegroup/kie-wb-distributions/pull/1080
* https://github.com/kiegroup/jbpm/pull/1828
> JBPM-9542: Remove issue-keeper tool

- pom.xml
#1563 cherry-pick
Due to recent jira authentication changes we decided to stop using issue-keeper tool for preventing test method run. It was replaced by simple '@Ignore' junit annotations.
For more details see:
- https://issues.redhat.com/browse/JBPM-9542
- https://github.com/ibek/issue-keeper
* https://github.com/kiegroup/kie-wb-distributions/pull/1081
* https://github.com/kiegroup/jbpm/pull/1831
<details>
<summary>
</summary>
* <b>a full …
> [7.48.x] JBPM-9542: Remove issue-keeper tool

- .ci/project-dependencies.yaml
There is a cross repo PR https://github.com/kiegroup/appformer/pull/987  from @jomarko which fails as Appformer PR adds new classes and kie-wb-common repo GA CI fails on missing them
<details>
<summary>
</summary>
</details>
> Fixing broken upstream repository deps for kie-wb-common

- script/release/10a_drools_upload_filemgmt.sh
- script/release/10b_jbpm_upload_filemgmt.sh
- script/release/10c_optaplanner_upload_filemgmt.sh
The simple `rm` command in shell scripts had to be replaced by `rm -rf` so the removal could be executed and the shell script doesn't exit premature and the whole pipeline fails. 
<details>
<summary>
</summary>
</details>
> fixed removal commands in shell scripts

- Jenkinsfile.buildchain
<details>
<summary>
</summary>
</details>
> Jenkinsfile.buildchain tools replaced by nodejs

- pom.xml
Jira https://issues.redhat.com/browse/JBPM-9549
> [JBPM-9549] Upgrade SpringBoot to 2.3.4

- .github/workflows/generate_files.yml
* Add to the description just the changed files
* add to the new PR description the merged PR triggering the job
* add to the new PR description the action id creating the PR
https://issues.redhat.com/browse/BXMSPROD-1144
You can check a pull request example produced by the job on https://github.com/Ginxo/droolsjbpm-build-bootstrap/pull/55
<details>
<summary>
</summary>
* …
> BXMSPROD-1144 Improve generate_files flow

- script/release/10a_drools_upload_filemgmt.sh
- script/release/prepareUploadDir.sh
<details>
<summary>
</summary>
</details>
> removed leftovers in scripts of droolsjbpm-tools binaries

- script/release/10a_drools_upload_filemgmt.sh
- script/release/10b_jbpm_upload_filemgmt.sh
- since there is not any more the difference between a latest and latestFinal release (we only have Final releases) the condition could be erased. In a release both files (jbpm-installer-$kieVersion.zip & jbpm-installer-full-$kieVersion.zip) have to be uploaded.
- files that should be removed at end of the upload weren't removed because simply the script was in the wrong directory
<details>
<summary>
</summary>
* <b>a full production downstream build</b> please add …
> Upload jbpm binaries

- pom.xml
**JIRA:** [BAQE-1696](https://issues.redhat.com/browse/BAQE-1696)
PR set:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1585
* https://github.com/kiegroup/appformer/pull/1102
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/501
* https://github.com/kiegroup/drools/pull/3376
* https://github.com/kiegroup/jbpm/pull/1862
* https://github.com/kiegroup/droolsjbpm-integration/pull/2394
* https://github.com/kiegroup/optaplanner/pull/1161
> BAQE-1696 - Change revapi to check against 7.48.0.Final

- .github/workflows/pull_request.yml
- .github/workflows/upstream.yml
JIRA
https://issues.redhat.com/browse/BXMSPROD-1214
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1595
https://github.com/kiegroup/kie-soup/pull/182
https://github.com/kiegroup/droolsjbpm-knowledge/pull/504
https://github.com/kiegroup/drools/pull/3406
https://github.com/kiegroup/optaplanner/pull/1177
https://github.com/kiegroup/lienzo-core/pull/141
https://github.com/kiegroup/lienzo-tests/pull/113
https://github.com/kiegroup/appformer/pull/1110
https://github.com/kiegroup/kie-uberfire-extensions/pull/111
https://github.com/kiegroup/jbpm/pull/1875
https://github.com/kiegroup/kie-jpmml-integration/pull/49
https://github.com/kiegroup/droolsjbpm-integration/pull/2405
https://github.com/kiegroup/kie-wb-playground/pull/103
https://github.com/kiegroup/kie-wb-common/pull/3579 …
> BXMSPROD-1214 Install takari error workaround

- pom.xml
**[JBPM-9355](https://issues.redhat.com/browse/JBPM-9355)**: Stabilize some jBPM integration tests by upgrading TJWSEmbeddedJaxrsServer embedded server
> [JBPM-9355] - Stabilize some jBPM integration tests by upgrading TJWSEmbeddedJaxrsServer embedded server

- Jenkinsfile
- Jenkinsfile.buildchain
This calls a method to simply read the disk space before and after each PR.
Done to better understand why we encounter so much "no space left on device" errors.
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1597
https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/145
<details>
<summary>
</summary> …
> new stages for measuring disk space before and after build

- .ci/project-dependencies.yaml
The removal of `droolsjbpm-tools` in this file should determine a new repository-list.txt without it.
Looking in the kie-jenkins-scripts (PRs, FDBs and CDBs `droolsjbpm-tools` is not present).
<details>
<summary>
</summary>
</details>
> removed droolsjbpm-tools

- pom.xml
https://issues.redhat.com/browse/BXMSPROD-1273
Backporting of https://github.com/kiegroup/droolsjbpm-build-bootstrap/commit/0f2c8c33a8111f50f96c522d0fc3c1a964c1f613
<details>
<summary>
</summary>
</details>
> [7.52.x][BXMSPROD-1273] backport of Xstream upgrade to 1.4.16

- drools-bom/pom.xml
- kie-bom/pom.xml
- uberfire-bom/pom.xml
**JIRA**: [KOGITO-5016](https://issues.redhat.com/browse/KOGITO-5016)
- https://github.com/kiegroup/appformer/pull/1135
- https://github.com/kiegroup/kie-wb-common/pull/3632
- https://github.com/kiegroup/drools-wb/pull/1488
- https://github.com/kiegroup/jbpm-wb/pull/1490
- https://github.com/kiegroup/kie-wb-distributions/pull/1099
<details>
<summary>
</summary>
* <b>a full production downstream build</b> please add comment: <b>Jenkins …
> KOGITO-5016: Remove Kogito-related modules from v7 stream

- pom.xml
Related PRs:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1645
`version.org.apache.xmlgraphics.commons` repeated on:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/548244ff02e5dc8749229e4ff060f29a04532a7e/pom.xml#L302
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/548244ff02e5dc8749229e4ff060f29a04532a7e/pom.xml#L163
**JIRA**: 
- https://issues.redhat.com/browse/RHPAM-3489
- https://issues.redhat.com/browse/RHDM-1623
<details>
<summary>
</summary>
* <b>a compile downstream build</b> please  add …
> [RHPAM-3489][RHDM-1623] duplicated version.org.apache.xmlgraphics.commons error fixed

- pom.xml
**JIRA**: https://issues.redhat.com/browse/RHPAM-3489
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1643
<details>
<summary>
</summary>
</details>
> [RHPAM-3489][RHDM-1623][7.52.x] duplicated version.org.apache.xmlgraphics.commons error fixed

- pom.xml
**JIRA**: 
https://issues.redhat.com/browse/DROOLS-6369
* https://github.com/kiegroup/droolsjbpm-integration/pull/2495
<details>
<summary>
</summary>
</details>
> [DROOLS-6369] Fix kie-karaf-itests failures because of guava upgrade

- .ci/pull-request-config.yaml
By default, each path is only uploaded when the build is successful.
https://github.com/kiegroup/github-action-build-chain/blob/master/README.md#upload-for-different-execution-results
In case of OptaWeb, we need the artifacts always. Especially when the
end-to-end test fails so that we can see what went wrong.
**JIRA**:
https://issues.redhat.com/browse/PLANNER-2446
<details>
<summary>
</summary>
* <b>a full production downstream build</b> …
> PLANNER-2446: Always archive screenshots and videos

- pom.xml
**JIRA**: [BAQE-1904](https://issues.redhat.com/browse/BAQE-1904)
PR set:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1665
* https://github.com/kiegroup/appformer/pull/1150
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/525
* https://github.com/kiegroup/drools/pull/3664
* https://github.com/kiegroup/jbpm/pull/1948
* https://github.com/kiegroup/droolsjbpm-integration/pull/2503
* https://github.com/kiegroup/optaplanner/pull/1370
> BAQE-1904 - Change revapi to check against 7.52.0.Final

- Jenkinsfile.buildchain
I propose this change as a temporary solution until we can incorporate https://github.com/kiegroup/kie-jenkins-scripts/commit/d7d3ed5cdd48369bee57a653ddf9c4a72e8344d8 to the new slave machine
<details>
<summary>
</summary>
* <b>an upstream build</b> please add comment: <b>Jenkins run …
> Jenkinsfile.builchain pointing to 7.55.0.Final definition file

- Jenkinsfile.buildchain
related PRs:
- https://github.com/kiegroup/kie-jenkins-scripts/pull/1011
<details>
<summary>
</summary>
</details>
> allow jdk/maven tool per job

- script/git-all.sh
<details>
<summary>
</summary>
</details>
> exit a sh scripts when git-all.sh fails

- .ci/jenkins/Jenkinsfile.nightly
Backport into 7.52.x of https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1691
> Downgrade Maven to 3.6.3

- script/release/update-version-all.sh
Since process-migration-service is a new repo in kiegroup with dependencies of droolsjbpm-integration, its version should be synced to all other community repos. Since no `mvn` command for updating works there is a simple `sed` command executed when running the scipt for upgrading the versions in all kiegroup repos.  
<details>
<summary>
</summary>
* <b>a full production downstream build</b> …
> added new repo to update script

- .ci/jenkins/Jenkinsfile.nightly
Reverts kiegroup/droolsjbpm-build-bootstrap#1690
> Revert "Downgrade Maven to 3.6.3"

- .ci/pull-request-config.yaml
Should eliminate the following false warning:
<details>
<summary>
</summary>
</details>
> PLANNER-2487: Remove wildfly from OptaWeb build commands

- kie-pmml-bom/pom.xml
**JIRA**: 
https://issues.redhat.com/browse/DROOLS-6554
https://github.com/kiegroup/droolsjbpm-integration/pull/2575
<details>
<summary>
</summary>
</details>
> [DROOLS-6554] droolsjbpm-integration deploy job failure

- .ci/compilation-config.yaml
- .ci/full-downstream-config.yaml
- .ci/project-dependencies.yaml
- .ci/pull-request-config.yaml
- with this the repository-list.txt will have again, when created `process-migratopn-service`
- fdb and cdb are skipping PIM
<details>
<summary>
</summary>
</details>
> skipped process-migration-service for fdb and cdb

- pom.xml
- script/mvn-all.sh
**JIRA**: [BXMSPROD-1468](https://issues.redhat.com/browse/BXMSPROD-1468)
- when the reps are build with >= jdk11 the jars will be compiled the jdk1.8 could read them
- when the JAVA version for compiling the reps is **jdk 1.8** the mvn-all.sh scripts skips PIM,  removing this project from repository-list.txt 
Works locally. 
mvn-all.sh was used with jdk1.8 and jdk11, it worked.
In case the build was with jdk 11, a *.jar was downloaded, a class extracted and 
`javap -v XXX.class | grep major` done with 52 (for jdk1.8) as result.
<details>
<summary>
</summary>
* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no …
> BXMSPROD-1468: skipping to build PIM when using jdk1.8

- .ci/compilation-config.yaml
- .ci/full-downstream-config.yaml
- .ci/project-dependencies.yaml
- .ci/pull-request-config.yaml
- with this the repository-list.txt will have again, when created `process-migratopn-service`
- fdb and cdb are skipping PIM
<details>
<summary>
</summary>
</details>
> skipped process-migration-service for fdbs and cdbs 7.59.x

- pom.xml
backport of https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1664
> Bump keycloak-core from 9.0.3 to 13.0.0 (#1664)

- .ci/jenkins/Jenkinsfile.nightly
Backport for: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1761
> [7.59.x] Switch nightly build to JDK11

- pom.xml
Hi @mareknovotny, @romartin, @domhanak,
I fixed the dependency, issue was when we compiling with JDK 11 for JDK 8 there are some collisions with XML API names. Since this dependency was used only for Stunner (according to comments into the POM) file, so I updated it directly without adding new dependencies.
* https://github.com/kiegroup/kie-wb-common/pull/3682
* https://github.com/kiegroup/jbpm-wb/pull/1513
* https://github.com/kiegroup/kie-wb-distributions/pull/1127
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1766
<details>
<summary>
</summary>
* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no longer …
> JBPM-9896 - Fix dependency for compilation Stunner on JDK 11 to JRE 8

- pom.xml
* RHPAM-3510: upgrade minor versions
* downgrade back sshd to 2.3.0
* Cancel Update of version.org.glassfish.jaxb
Co-authored-by: Marek Novotný <hotmana76@gmail.com>
(cherry picked from commit 3cb53e14fb20368dd995258866209863ade5f8d9)
**JIRA**: [RHPAM-3510](https://issues.redhat.com/browse/RHPAM-3510)
<details>
<summary>
</summary>
* <b>a full production downstream build</b> please add …
> [7.59.x] RHPAM-3510: upgrade minor versions (#1736)

- pom.xml
Hi @mareknovotny, @mbiarnes, @romartin, @jomarko it is cherry-pick of https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1766
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1771
* https://github.com/kiegroup/kie-wb-distributions/pull/1129
* https://github.com/kiegroup/jbpm-wb/pull/1515
* https://github.com/kiegroup/kie-wb-common/pull/3685
<details>
<summary>
</summary>
* <b>a full …
> [7.59.x] JBPM-9896 - Fix dependency for compilation Stunner on JDK 11 to JRE 8

- pom.xml
**JIRA**: https://issues.redhat.com/browse/AF-2884
`chemistry-opencmis-commons-impl` does not even use `jaxws-rt` at all and it is the first version after 0.11.0 which does not use it.
```
[INFO] org.jbpm:jbpm-wb-showcase:war:7.60.0-SNAPSHOT
[INFO] +- org.apache.chemistry.opencmis:chemistry-opencmis-commons-impl:jar:0.14.0:runtime
[INFO] |  \- org.codehaus.woodstox:woodstox-core-asl:jar:4.4.1:runtime
[INFO] |     \- org.codehaus.woodstox:stax2-api:jar:3.1.4:runtime
[INFO] +- org.apache.chemistry.opencmis:chemistry-opencmis-commons-api:jar:0.14.0:runtime
[INFO] +- org.apache.chemistry.opencmis:chemistry-opencmis-client-bindings:jar:0.14.0:runtime
[INFO] +- org.kie.uberfire:i18n-taglib:jar:7.60.0-SNAPSHOT:runtime
```
**referenced Pull …
> [AF-2884] upgrading opencmis version to 0.14.0

- .ci/project-dependencies.yaml
https://github.com/kiegroup/drools/pull/3860
</details>
> Removed optaweb exclusion to make Optaplanner build from 7.x branch

- .ci/jenkins/Jenkinsfile.nightly
`DEFAULT_CONFIG_BRANCH` environment variable and job parameter are colliding and no matter what you set on `DEFAULT_CONFIG_BRANCH` parameter the env value will be always taken. I've even tried to see the differences between using `${env.DEFAULT_CONFIG_BRANCH}` and `${DEFAULT_CONFIG_BRANCH}` and the result is the same, so the only possibility here is to use a different parameter name.
This is producing `7.59.x` prod nightly error due to `rhdm` profile is not set for `rhba` project and `decision-central-eap7-deployable` is not produced so rhba-installer fails.
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1783
* …
> [prod nightly] CONFIG_BRANCH

- .ci/project-dependencies.yaml
[BXMSPROD-1444](https://issues.redhat.com/browse/BXMSPROD-1444)
https://github.com/kiegroup/kie-jenkins-scripts/pull/1153
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1801
<details>
<summary>
</summary>
* <b>a full production …
> removed kie-jpmml-integration as dependency from droolsjbpm-integration

- .ci/jenkins/Jenkinsfile.nightly
due to https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/PROD/job/nightly/job/main/111
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in …
> prod nightly timeout increased

- .ci/jenkins/Jenkinsfile.nightly
**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1505
no backport is needed
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions …
> BXMSPROD-1505 RHDM UMB message removed

- .ci/actions/build-chain/action.yml
see https://github.com/kiegroup/drools/pull/4005#issuecomment-966527542
Referenced PRs:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1820
- https://github.com/kiegroup/kogito-pipelines/pull/321
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is …
> deifnition-file default GROUP placeholder value

- .ci/compilation-config.yaml
* link 2
* link 3 etc.
<details>
<summary>
</summary> …
> .ci/compilation-config.yaml updated to clean up and show disk space after every project execution

- .ci/actions/build-chain/action.yml
- .github/workflows/branch-compilation.yml
* additional-flags
* exports execution summary to spreadsheet
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you …
> build chain updated to v2.6.21

- .github/pull_request_template.md
- .github/workflows/full-downstream.yml
[BXMSPROD-1601](https://issues.redhat.com/browse/BXMSPROD-1601)
* https://github.com/kiegroup/kie-soup/pull/245
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/584
* https://github.com/kiegroup/drools/pull/4083
* https://github.com/kiegroup/optaplanner/pull/1745
* https://github.com/kiegroup/lienzo-core/pull/160
* https://github.com/kiegroup/lienzo-tests/pull/133
* https://github.com/kiegroup/appformer/pull/1224
* https://github.com/kiegroup/kie-uberfire-extensions/pull/130
* https://github.com/kiegroup/jbpm/pull/2081
* https://github.com/kiegroup/droolsjbpm-integration/pull/2675
* https://github.com/kiegroup/kie-wb-playground/pull/126
* …
> BXMSPROD-1601 provide FDB github action for RHBA project

- .ci/compilation-config.yaml
- .ci/full-downstream-config.yaml
- .ci/pull-request-config.yaml
- `dependency:tree` added to every maven command 
- common maven options moved to `BUILD_MVN_OPTS` variable.
Thanks to `dependecy:tree` info we can take profit of future maven build logs thanks to https://github.com/Ginxo/treat-maven-dependency-plugin-log tool and to analyze changes impact faster and in a more reliable way.
Related PR:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1853
- https://github.com/kiegroup/kogito-pipelines/pull/342
<details>
<summary>
</summary> …
> dependency:tree added to CI

- .ci/jenkins/Jenkinsfile.buildchain
- .ci/jenkins/Jenkinsfile.nightly
Use the label family designed to support Jenkins pipeline resuming after Jenkins restart.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change …
> CI: Use *-pipeline label

- .ci/jenkins/Jenkinsfile.nightly
Fix the label expression for prod nightly build after switching to the new CI cloud.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple …
> CI: fix nightly label after moving to rhos-01 cloud

- .ci/jenkins/Jenkinsfile.daily
<details>
<summary>
</summary> …
> fixed parameter visibility in upload URL

- .ci/jenkins/Jenkinsfile.daily
removed clean-up-script only from PIM build since  in all daily builds the build broke with:
`Unable to parse command line options: Unrecognized option: --clean-up-script=/home/jenkins/workspace/KIE/main/daily-build-jdk11/jdk11-db-main/clean-up.sh`
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method …
> removed cleanUp script for PIM

- .ci/jenkins/Jenkinsfile.daily
<details>
<summary>
</summary> …
> removed doubled information

- .ci/jenkins/Jenkinsfile.daily
<details>
<summary>
</summary> …
> remove scp optawebs

- .ci/jenkins/Jenkinsfile.release
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1913
https://github.com/kiegroup/kie-jenkins-scripts/pull/1227
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command …
> added expression to send mail only one time

- .github/workflows/generate_files.yml
Let's filter it just by `.ci/pull-request-config.yaml` and `.ci/project-dependencies.yaml` which are the only files affecting the output
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github …
> generate_files workflow path filtering

- .ci/chain-status-info.md
- .github/pull_request_template.md
- .github/workflows/generate_status_page.yaml
- .github/workflows/generate_status_page_data.yaml
- README.md
The idea is to generate a webpage like https://ginxo.github.io/droolsjbpm-build-bootstrap
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change …
> kiegroup status webpage

- .ci/jenkins/Jenkinsfile.release
- .ci/release-config.yaml
- for three projects (optaplanner, kie-docs and jbpm-work-items) can't be removed the `/target` directories after building because there are binaries needed for the upload to file.mgmt.jboss.org (web pages)
- the binaries to upload to filemgmt.jboss.org have to be archived  in case they are needed again in a second pipeline run if the fist pipeline was aborted or failed. This the whole build doesn't to have be repeated.
- once the *tar.gz file was archived it will be removed to save disk space
<details>
<summary>
</summary>
Build Chain tool does "simple" maven …
> fixed binaries to upload to filemgmt.jboss.org

- pom.xml
[DROOLS-6879](https://issues.redhat.com/browse/DROOLS-6879)
Testing if FDB passes with the 17.0.0 Wildfly.
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1918
- https://github.com/kiegroup/appformer/pull/1249
- 
<details>
<summary>
</summary>
[build-chain …
> DROOLS-6879 : Update to Wildfly core 17.x

- .ci/jenkins/Jenkinsfile.daily
- .ci/jenkins/Jenkinsfile.release
the parameter `-p='${buildChainGroup}/droolsjbpm-build-bootstrap'` in buildchain commands was removed
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could …
> removed -p parameter from buid-chain commands

- .ci/jenkins/Jenkinsfile.release
* link 2
* link 3 etc.
<details>
<summary>
</summary> …
> removed cleanWs() and fixed expression

- .ci/jenkins/Jenkinsfile.release
- script/release/09_createjBPM_installers.sh
- script/release/10a_drools_upload_filemgmt.sh
- script/release/10b_jbpm_upload_filemgmt.sh
- script/release/10c_optaplanner_upload_filemgmt.sh
The build chain tool should be installed in any case, also when a new build isn't needed. For pushing the tags the build-chain tools is needed too.
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other …
> removed when condition

- .github/workflows/generate_status_page.yaml
- .github/workflows/generate_status_page_data.yaml
The idea is to avoid executing cron jobs for forked repositories
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and …
> Execute GHA generate status only on kiegroup

- .ci/jenkins/Jenkinsfile.release
Basically these fixes include:
- the order of junit - this happens directly after the build, so when the pìpeline is halted in a later step the junits are done
- the zipping and archiving of binaries is integrated in a script and execute { - so in case it fails it can repeated
- all curls to proxy01 and proxy02 were removed since they don't exist anymore. The caching is done by Akamai.  
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each …
> fixes for release pipeline

- script/release/10a_drools_upload_filemgmt.sh
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which …
> fixed path to upload kie-api-javadoc

- .ci/jenkins/Jenkinsfile.buildchain
This reverts commit 2828cb521ac63fa9d59d8d9dd5a4945062baa0dd.
<details>
<summary>
</summary> …
> Revert "disabled concurrent buildchain builds on pipeline level (#1969)"

- .ci/jenkins/Jenkinsfile.release
- script/release/12_splitOrgKie.sh
Due to the `new` Nexus (or changes on the conf of server repositories.jboss.org) Nexus didn't admit any more files > 5G.
Instead of zipping one big file (about 11G) now it is zipped
drools
jbpm
dashbuilder
optaplanner
uberfire
and kie
All files a uploaded separately to Nexus. The kie.zip has 9g, so this has to be `split ted`.
The upload with these changes were tested and all worked properly.
Hopefully the release pipeline will not fail any more.
)You can check Kiegroup organization repositories CI status from [Chain Status webpage](https://kiegroup.github.io/droolsjbpm-build-bootstrap/)
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, …
> partial upload to Nexus

- .ci/jenkins/Jenkinsfile.release
The release pipeline failed because once with a CURL was closed the staging-repository Nexus needs about 15 minutes to run all checks for closing the staging-rep. The uploaded artifacts are available after the closure on Nexus finishes.
The following step in release pipeline was to run the `additional tests` and these need the uploaded artifacts but the Nexus staging-repository is still closing, and so the artifacts are not yet available.
Now it checks the `type` [open or closed] and waits at least for 15 minutes, in case if everything works fine this time should be enough for closing, in case something happens with Nexus it will repeat every 15 minutes this check.
You can check Kiegroup organization repositories CI status from [Chain Status …
> new stage for checking type of staging-repository

- .ci/jenkins/Jenkinsfile.release
- script/release/12_splitOrgKie.sh
This reverts commit 328632ef1d53391c1374d3eae49993ecba6ae0c9.
This PR was a misunderstanding. 
The `dev` is a Nexus for us for testing things. 
The release binaries will still release to the repository.jboss.org Nexus.
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven …
> Revert "new CREDS and URL for dev Nexus (#1994)"

- script/repository-list.txt
Follows up on #1975. Now there are no dependencies on `optaplanner` in the other repositories.
```
$ ./droolsjbpm-build-bootstrap/script/checks/repo-dep-tree.pl -w -t kie-wb-distributions
You need to build following repositories before building 'kie-wb-distributions' (in order):
droolsjbpm-build-bootstrap,kie-soup,lienzo-core,lienzo-tests,appformer,droolsjbpm-knowledge,drools,jbpm,droolsjbpm-integration,kie-wb-playground,kie-wb-common,drools-wb,jbpm-designer,jbpm-work-items,kie-uberfire-extensions,jbpm-wb,kie-wb-distributions
```
https://issues.redhat.com/browse/BAPL-2293
<details>
<summary>
</summary> …
> [7.67.x-blue] BAPL-2293 Remove OptaPlanner from the build

- pom.xml
Backport of https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1983/commits/3eb5dbd8683c92d41353085897074fd453d3e8a3
> [7.67.x][JBPM-10093] - Adapt testcontainers to support and use a particular Kafka version

- .ci/jenkins/Jenkinsfile.daily
zulip topic looks now better - not starting with dash:
before:  
now it will be **daily build jdk8 - 7.67.x**
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method …
> zulip issue without starting dash

- .ci/compilation-config.yaml
- .ci/full-downstream-config.yaml
- .ci/pull-request-config.yaml
The idea is to print dependency:tree information before failing, this will help on those ban duplicated classes errors
<details>
<summary>
</summary>
[build-chain …
> dependency:tree before goals

- .ci/jenkins/Jenkinsfile.daily
* link 2
* link 3 etc.
<details>
<summary>
</summary> …
> added [] to mail  subject

- .ci/jenkins/Jenkinsfile.daily
* link 2
* link 3 etc.
<details>
<summary>
</summary> …
> zulip issue starting without dash

- pom.xml
Back port of https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1997
<details>
<summary>
</summary>
[build-chain …
> [7.67.x] Bump undertow-core from 2.2.5.Final to 2.2.15.Final (#1997)

- pom.xml
Back port of https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1993
<details>
<summary>
</summary>
[build-chain …
> [7.67.x-blue] Bump xalan from 2.7.1 to 2.7.2 (#1993)

- pom.xml
Ticket: https://issues.redhat.com/browse/RHPAM-4455
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2027
- https://github.com/kiegroup/droolsjbpm-integration/pull/2836
- https://github.com/kiegroup/kie-wb-common/pull/3760
- https://github.com/kiegroup/kie-wb-distributions/pull/1178
Backporting:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2023
> [7.67.x] RHPAM-4455 org.w3c.dom.* ignored from ban-duplicated-classes

- pom.xml
Ticket: https://issues.redhat.com/browse/RHPAM-4455
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2028
- https://github.com/kiegroup/droolsjbpm-integration/pull/2837
- https://github.com/kiegroup/kie-wb-common/pull/3761
- https://github.com/kiegroup/kie-wb-distributions/pull/1179
Backporting:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2023
> [7.67.x-blue] RHPAM-4455 org.w3c.dom.* ignored from ban-duplicated-classes

- .ci/compilation-config.yaml
- .ci/daily-config.yaml
- .ci/full-downstream-config.yaml
- .ci/pull-request-config.yaml
- .ci/release-config.yaml
added `java -version` to PRs, FDBs, CDBs, daily builds and releases
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those …
> added java -version to show up in the logs

- .github/pull_request_template.md
- README.md
**JIRA**:
- [BXMSPROD-1772](https://issues.redhat.com/browse/BXMSPROD-1772)
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2036
Improved the 'Running the Build' section by adding some examples using the `build-chain-action` tool.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest …
> [BXMSPROD-1772] Improved build documentation

- pom.xml
https://issues.redhat.com/browse/DROOLS-5456
Updates to build under JDK 11.
This PR makes the following updates to allow the Drools Projects to build under JDK 11: * Updates version.org.eclipse.tycho to 2.3.0 to add support for JDK 11 * Updates the Maven Compile Goal to use the RELEASE nomenclature.
Jenkins run fdb
> Drools 5456 - Some Drools Projects don't compile with JDK 11

- .ci/jenkins/Jenkinsfile.nightly
**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1796
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2041
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2042
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2043
<details>
<summary>
</summary> …
> [BXMSPROD-1796] setup nexus repository group

- .ci/jenkins/Jenkinsfile.nightly
**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1796
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2041
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2042
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2043
<details>
<summary>
</summary> …
> [7.67.x][BXMSPROD-1796] setup nexus repository group

- .ci/jenkins/Jenkinsfile.nightly
**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1796
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2041
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2042
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2043
<details>
<summary>
</summary> …
> [7.67.x-blue][BXMSPROD-1796] setup nexus repository group

- .ci/project-dependencies.yaml
**JIRA**: https://issues.redhat.com/browse/RHPAM-4416
dependent PR:
- https://github.com/kiegroup/droolsjbpm-integration/pull/2850
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version …
> removing openshift-drools-hacep from dependencies

- .ci/project-dependencies.yaml
**JIRA**: https://issues.redhat.com/browse/RHPAM-4416
related PR 
* https://github.com/kiegroup/droolsjbpm-integration/pull/2853
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of …
> [7.67.x] RHPAM-4416 removing openshift-drools-hacep from dependencies

- .ci/project-dependencies.yaml
**JIRA**: https://issues.redhat.com/browse/RHPAM-4416
related PR 
* https://github.com/kiegroup/droolsjbpm-integration/pull/2854
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of …
> [7.67.x-blue] RHPAM-4416 removal openshift-drools-hacep repository from build dependencies

- .github/workflows/generate_files.yml
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used locally on command line or in Github …
> generate_files workflow updated to 7.67.x and 7.67.x-blue

- .ci/project-dependencies.yaml
**JIRA**:  https://issues.redhat.com/browse/BXMSPROD-1763
<details>
<summary>
</summary>
[build-chain …
> [BXMSPROD-1763] jbpm-designer removed from project-dependencies

- jbpm-bom/pom.xml
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2058
* https://github.com/kiegroup/jbpm-wb/pull/1562
<details>
<summary>
</summary> …
> [7.67.x] jbpm-designer dependecie management removal

- .ci/project-dependencies.yaml
repository-list and diagram image will automatically replaced by github action
<details>
<summary>
</summary>
[build-chain …
> [7.67.x-blue] opta projects removed from project-dependencies

- .ci/actions/build-chain/action.yml
* link 2
* link 3 etc.
<details>
<summary>
</summary> …
> upgrade build-chain to version 2.6.25

- uberfire-bom/pom.xml
https://issues.redhat.com/browse/BXMSPROD-1845
Related PRs:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2097
* https://github.com/kiegroup/appformer/pull/1312
* https://github.com/kiegroup/kie-wb-common/pull/3781
* https://github.com/kiegroup/drools-wb/pull/1558
* https://github.com/kiegroup/jbpm-wb/pull/1572
* https://github.com/kiegroup/optaplanner-wb/pull/413
* https://github.com/kiegroup/kie-wb-distributions/pull/1196
> [BXMSPROD-1845] elasticsearch removed from appformer

- .ci/jenkins/Jenkinsfile.buildchain
- .ci/jenkins/Jenkinsfile.nightly
* link 2
* link 3 etc.
<details>
<summary>
</summary> …
> [7.67.x-blue] changed label master to built-in

- .ci/jenkins/Jenkinsfile.buildchain
- .ci/jenkins/Jenkinsfile.nightly
* link 2
* link 3 etc.
<details>
<summary>
</summary> …
> [7.67.x] changed label master to built-in

- .ci/jenkins/Jenkinsfile.nightly
**JIRA**: https://issues.redhat.com/browse/RHPAM-4541
* https://github.com/kiegroup/kie-jenkins-scripts/pull/1352
<details>
<summary>
</summary> …
> [7.67.x-blue][RHPAM-4541] use bamoe nightly config folder

- .github/workflows/generate_status_page_data.yaml
**JIRA**: 
https://issues.redhat.com/browse/BAPL-2340
* https://github.com/kiegroup/chain-status/pull/45
Enable default `7.67.x` and `7.67.x-blue` branches comparison in the Chain Status webpage.
<details>
<summary>
</summary> …
> [BAPL-2340] provide 7.67.x and blue branches comparison in status page

- .github/dependabot.yml
**JIRA**:  https://issues.redhat.com/browse/BXMSPROD-1881
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2117
<details>
<summary>
</summary> …
> [BXMSPROD-1881] dependant-bot for main, 7.67.x and blue branches

- .github/dependabot.yml
* link 2
* link 3 etc.
<details>
<summary>
</summary> …
> [BXMSPROD-1881] dependabot prefix lenght <15

- .ci/jenkins/Jenkinsfile.nightly
**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1889
Related PRs:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2136
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2148
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2149
<details>
<summary>
</summary> …
> [7.67.x-blue][BXMSPROD-1889] add stage to create tag in prod repositories in Jenkinsfile.nightly

- .github/dependabot.yml
Disable version updates while only keeping security updates
See:
- https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#overriding-the-default-behavior-with-a-configuration-file
> Disable version updates

- pom.xml
7.x backport to keep aligned Antlr version for Drools DMN engine
ref https://github.com/quarkusio/quarkus/pull/27298#issuecomment-1216705851
**JIRA**: https://issues.redhat.com/browse/DROOLS-7105
- (main) https://github.com/kiegroup/drools/pull/4614
- (7.x for alignment) https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2031
- (7.x for alignment) https://github.com/kiegroup/drools/pull/4632
- (7.x for alignment) https://github.com/kiegroup/kie-wb-common/pull/3769
- (7.x for alignment) https://github.com/kiegroup/drools-wb/pull/1552
- (7.x for alignment) https://github.com/kiegroup/kie-wb-distributions/pull/1187
You can check Kiegroup organization repositories CI status from [Chain Status webpage](https://kiegroup.github.io/droolsjbpm-build-bootstrap/ …
> DROOLS-7105 DMN upgrade to Antlr 4.10

- .ci/actions/backporting/action.yml
- .ci/actions/parse-labels/action.yml
- .github/pull_request_template.md
- .github/workflows/pr-backporting.yml
**JIRA**: 
https://issues.redhat.com/browse/BXMSPROD-1892
* https://github.com/carloscastrojumo/github-cherry-pick-action/pull/26
* https://github.com/kiegroup/kogito-pipelines/pull/743
**Workflows PRs**:
- https://github.com/kiegroup/appformer/pull/1370
- https://github.com/kiegroup/droolsjbpm-integration/pull/2919
- https://github.com/kiegroup/droolsjbpm-knowledge/pull/633
- https://github.com/kiegroup/drools-wb/pull/1564
- https://github.com/kiegroup/jbpm/pull/2251
- https://github.com/kiegroup/jbpm-wb/pull/1581
- https://github.com/kiegroup/jbpm-work-items/pull/272
- https://github.com/kiegroup/kie-docs/pull/4380
- https://github.com/kiegroup/kie-jpmml-integration/pull/75
- …
> [BXMSPROD-1892] Automated pull request backporting workflow

- .ci/actions/os-preparation/action.yml
- .ci/actions/parse-labels/action.yml
**JIRA**: 
https://issues.redhat.com/browse/BXMSPROD-1937
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2174
* https://github.com/kiegroup/kogito-pipelines/pull/754
Based on https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ I changed from:
```
echo "::set-output name={name}::{value}"
```
to:
```
echo "{name}={value}" >> $GITHUB_OUTPUT
```
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because …
> [BXMSPROD-1937] using env file instead of set-output

- .ci/actions/backporting/action.yml
- .github/workflows/pr-backporting.yml
**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1936
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2175
* https://github.com/kiegroup/kogito-pipelines/pull/752
**Improvements**
Added new input parameters:
* `include-merge-as-reviewer`: whether to include or not the user who merged the PR as reviewer, default `true`
* `include-requested-reviewers`: whether to include original requested reviewers into backported pr, notice that approved reviewers are not in this list since ti seems github remove them. Default `true`
* `custom-reviewers`: allows users to customize the workflow adding additional custom reviewers
Deprecated `additional-reviewers` as it is now managed internally in the composite …
> [BXMSPROD-1936] Fix default reviewers and customization

- .ci/actions/backporting/action.yml
**JIRA**: 
https://issues.redhat.com/browse/BXMSPROD-1938
- https://github.com/carloscastrojumo/github-cherry-pick-action/pull/72
Upgrading `github-cherry-pick-action` to `1.0.9` we can backport PRs that have been already merged by simply labeling them. This can be also done if new commits have been added in the `main` branch (obviously if they are not conflicting with the one we want to backport).
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the …
> [BXMSPROD-1938] backport PRs already merged

- script/release/update-versions-build-chain.sh
Changes we did in the past for creating a new repository list with `_` have to be undone - otherwise daily builds will fail
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API …
> replaced _ in update version script

- script/release/update-versions-build-chain.sh
(cherry picked from commit f6d1ef96f069c371a04d064338c91ade5291e06f)
* [main](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2215)
* [7.67.x](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2216)
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends …
> [7.67.x] fixed path in updating version script

- .ci/jenkins/Jenkinsfile.buildchain
The naming convention of the cloned folder is `<owner>_<repository>`. So for example instead of `kiegroup_droolsjbpm_integration` we need `kiegroup_droolsjbpm-integration`
> Fix directory name in which we want to run sonar analysis

- .github/workflows/generate_files.yml
`GITHUB_REF_NAME` is not always filled and PR title is produced like `[][Build Chain] Update build chain and repository-list files`
You can check:
- [test job](https://github.com/Ginxo/droolsjbpm-build-bootstrap/actions/runs/4181656099/jobs/7243819842)
- [related PR](https://github.com/Ginxo/droolsjbpm-build-bootstrap/pull/72)
<details>
<summary>
</summary> …
> Build Chain Generate Files get target branch name

- .ci/actions/backporting/action.yml
Remove the `dependabo[bot]` from the backporting reviewers list otherwise that process would fail as dependeabot is not a valid user for reviews.
**JIRA**:  https://issues.redhat.com/browse/BXMSPROD-1939
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2225
* https://github.com/kiegroup/kogito-pipelines/pull/869
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class …
> [BXMSPROD-1939] remove dependabot[bot] from backporting reviewers list

- .ci/daily-config.yaml
- .ci/jenkins/Jenkinsfile.daily
`kiegroup_process-migration-service` will only be built when the jdk version is **kie-jdk11.0.15** - otherwise it will be skipped. We have to assure that this rep is cloned too!
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories …
> fix path of process-migration-service for daily builds

- .ci/jenkins/Jenkinsfile.buildchain
after executing
```
build-chain build full_downstream -f 'https://raw.githubusercontent.com/${GROUP:kiegroup}/droolsjbpm-build-bootstrap/${BRANCH:main}/.ci/downstream-production-config.yaml' -o bc -u https://github.com/kiegroup/kie-wb-distributions/pull/1220
[INFO] 23 projects will be executed
[INFO] [kiegroup/lienzo-core]
[INFO] 	 Level type: upstream
....
```
test job can be checked here https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/7.67.x-blue/job/fdbp/job/kie-wb-distributions-7.67.x-blue.fdbp/2
<details>
<summary>
</summary>
Build Chain tool does "simple" maven …
> Jenkinsfile.buildchain default group

- .ci/full-downstream-config.yaml
- pom.xml
Upgrading sshd-core to 2.9.2
https://issues.redhat.com/browse/RHDM-1788 and https://issues.redhat.com/browse/RHPAM-3807
** Dependent PRs **: 
* https://github.com/kiegroup/appformer/pull/1374
* https://github.com/kiegroup/kie-wb-common/pull/3801
* https://github.com/kiegroup/jbpm-wb/pull/1587
<details>
<summary>
</summary> …
> RHDM-1788: changes related to upgrade of sshd-core 2.9.2

- .ci/jenkins/Jenkinsfile.release
* link 2
* link 3 etc.
<details>
<summary>
</summary> …
> updated build-chain command

- .ci/jenkins/Jenkinsfile.release
* link 2
* link 3 etc.
<details>
<summary>
</summary> …
> leftovers for 7.x releases using build-chain

- pom.xml
Reverts kiegroup/droolsjbpm-build-bootstrap#2180
solves https://issues.redhat.com/browse/RHPAM-4683
> [RHPAM-4683] Revert "RHPAM-4631 apache cxf to 3.5.5" to 3.4.10

- .ci/compilation-config.yaml
- .ci/full-downstream-config.yaml
- .ci/pull-request-config.yaml
Removing `smart` builder from CI checks
**JIRA**: [BXMSPROD-2059](https://issues.redhat.com/browse/BXMSPROD-2059)
* link 2
* link 3 etc.
<details>
<summary>
</summary> …
> [BXMSPROD-2059] Remove smart builder on CI checks

- .ci/jenkins/Jenkinsfile.release
changed email recipients
* link 2
* link 3 etc.
<details>
<summary>
</summary> …
> for 7.74.0.Final: fixed split of org.kie

- .ci/actions/parse-labels/action.yml
**JIRA:** https://issues.redhat.com/browse/BXMSPROD-2064
**referenced Pull Requests:**
* https://github.com/kiegroup/kie-ci/pull/1514
* https://github.com/kiegroup/kogito-pipelines/pull/999
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2321
As suggested here: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable setting untrusted input as env variable
> NOTE: even if we are planning to remove composite actions from this repo I would like to apply the change also here even if it will be needed for short time …
> [BXMSPROD-2064] set untrusted input as intermediate env variable

- .github/workflows/pull_request.yml
**JIRA**:
* https://issues.redhat.com/browse/BXMSPROD-2067
* link 2
* link 3 etc.
<details>
<summary>
</summary> …
> [7.67.x][BXMSPROD-2067] Fix PR workflow concurrency group (#2322)

- .github/workflows/pull_request.yml
**JIRA**:
* https://issues.redhat.com/browse/BXMSPROD-2067
* link 2
* link 3 etc.
<details>
<summary>
</summary> …
> [7.67.x-blue][BXMSPROD-2067] Fix PR workflow concurrency group (#2322)

- .ci/jenkins/Jenkinsfile.daily
* link 2
* link 3 etc.
<details>
<summary>
</summary> …
> builChainBranch does not have anymore main as fallback

- RELEASE-README.md
- kie-bom/pom.xml
- kie-user-bom-parent/pom.xml
- pom.xml
[BXMSPROD-2083](https://issues.redhat.com/browse/BXMSPROD-2083)
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2347
* https://github.com/kiegroup/droolsjbpm-integration/pull/2979
* https://github.com/kiegroup/kie-wb-common/pull/3816
* https://github.com/kiegroup/kie-wb-distributions/pull/1231
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven …
> BXMSPROD-2083: use of OptaPlanner final version

- .ci/daily-config.yaml
- .ci/jenkins/Jenkinsfile.daily
- .ci/update-versions-release.yaml
- script/release/update-versions-build-chain.sh
this PR refactors the update script for build-chain, so the repository-lists are not needed anymore. This was tested locally and it worked. Please look at the changes. Your comments are welcome.
[BXMSPROD-2080](https://issues.redhat.com/browse/BXMSPROD-2080)
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just …
> BXMSPROD-2080: update version adapted to build-chain logic

- .ci/jenkins/Jenkinsfile.daily
The additional tests in daily builds are failing. They didn't even start. 
When you do a replay these tests everything works fine. It seems that when the additional tests start not all artifacts are on qe-Nexus. 
7.67.x branches don't have this problem. 
I think we should put a `sleep` in the daily-build pipeline to delay the additional tests .
* link 2
* link 3 etc.
<details>
<summary> …
> added a sleep before starting with additional tests

- .ci/product-projects-dependencies.yaml
This change is required due to changes done in previous PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2330
<details>
<summary>
</summary>
[build-chain …
> remove reference to kiegroup/optaplanner in .ci/product-projects-dependencies.yaml

- .ci/project-dependencies.yaml
https://issues.redhat.com/browse/DROOLS-7533
> DROOLS-7533 `kie-jpmml-integration` 7.x depends on jbpmn main

- .github/workflows/generate_files.yml
maybe you should be included instead @rgdoliveira ? :thinking: 
<details>
<summary>
</summary>
[build-chain …
> remove ginxo and mbiarnes generate_files.yml flow

- .ci/project-dependencies.yaml
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used locally on command line or in Github …
> .ci/project-dependencies.yaml: use branch 7.x of kie-jpmml-integration when building with Drools branch 7.x

- pom.xml
Replacing https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2441
Dependent PRs:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2444 
- https://github.com/kiegroup/process-migration-service/pull/134 
- https://github.com/kiegroup/appformer/pull/1415 
- https://github.com/kiegroup/jbpm-work-items/pull/298 
- https://github.com/kiegroup/drools/pull/38 
- https://github.com/kiegroup/kie-soup/pull/276 
- https://github.com/kiegroup/jbpm/pull/2407 
- https://github.com/kiegroup/droolsjbpm-integration/pull/3044 
- https://github.com/kiegroup/kie-wb-common/pull/3824 
- https://github.com/kiegroup/kie-wb-distributions/pull/1243
> [7.67.x-blue] [RHPAM-3709] upgrade maven dependencies to address CVE-2021-26291

- .ci/jenkins/Jenkinsfile.buildchain
**JIRA**: [https://issues.redhat.com/browse/BXMSPROD-2188](https://issues.redhat.com/browse/BXMSPROD-2188)
Adding latest LTS version v20.14.0 for Sonar Analysis
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that …
> BXMSPROD-2188: added different node js binary for Sonar analysis

- .ci/jenkins/Jenkinsfile.buildchain
**JIRA**: https://issues.redhat.com/browse/BXMSPROD-2188
It looks like Jenkins CSB doesn't have v20.14.0 so using 20.13.1 instead
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version …
> BXMSPROD-2188: Use v20.13.1 nodejs for Sonar instead of v20.14.0

- .ci/jenkins/Jenkinsfile.buildchain
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used locally on command line or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can …
> [NO-ISSUE] Remove drools from jenkins buildchain configuration

- .ci/jenkins/Jenkinsfile.buildchain
disabling sonar cloud analysis on legacy branches for Jenkins PR runs
[BXMSPROD-2189](https://issues.redhat.com/browse/BXMSPROD-2189)
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest …
> [BXMSPROD-2189] disabling sonar cloud analysis on legacy branches for Jenkins PR runs

- pom.xml
This upgrade to Kafka 3.6.0 will result in an update of the snappy-java dependency to 1.1.10.4 to address the following vulnerabilities:
https://nvd.nist.gov/vuln/detail/CVE-2023-34453
https://nvd.nist.gov/vuln/detail/CVE-2023-34454
https://nvd.nist.gov/vuln/detail/CVE-2023-34455
https://nvd.nist.gov/vuln/detail/CVE-2023-43642
> Upgrade Kafka to address snappy-java vulnerabilities (CVE-2023-43642, CVE-2023-34455, ...)

- .ci/jenkins/Jenkinsfile.nightly
Jira https://issues.redhat.com/browse/BXMSPROD-2193
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool …
> [BXMSPROD-2193] replace gerrit user by gitlab user in .ci/jenkins/Jenkinsfile.nightly

- pom.xml
Full GAV change:
org.apache.velocity:velocity:1.7 ->
org.apache.velocity:velocity-engine-core:2.3
Referenced PRs:
- #2473
- https://github.com/kiegroup/kie-wb-common/pull/3829- 
NOTE: There are some changes that need to be made to the velocity configuration. These can be found at https://velocity.apache.org/engine/2.3/upgrading.html#upgrading-from-velocity-22-to-velocity-23. Read all changes until 1.7 to 2.0.
They all apply to this upgrade.
Test and verify any usage of Apache Velocity templates.
> [7.67.x-blue] Upgrading Apache Velocity to 2.3

- narayana-integration-bom/pom.xml
- pom.xml
**referenced Pull Requests**: https://github.com/kiegroup/droolsjbpm-integration/pull/3055
<details>
<summary>
</summary>
[build-chain …
> [7.67.x blue] Spring/SpringBoot upgrade to address CVEs in transitive dependencies

- .ci/jenkins/Jenkinsfile.nightly
* link 2
* link 3 etc.
<details>
<summary>
</summary> …
> [BXMSPROD-2209] move prod nightly to use rhel8

- .ci/jenkins/Jenkinsfile.buildchain
Related PRs:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2496
- https://github.com/kiegroup/kie-ci/pull/1562
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used locally on command line or in Github Actions …
> [BXMSPROD-2209] move buildchain configuration to use rhel8

- pom.xml
The current picketlink '2.6.0' version is  is affected by [CVE-2015-0277] [CVE-2015-6254]
Updating picketlink to '2.7.1' resolves the CVE
> [7.67.x-blue] update picketlink libraries version to 2.7.1

- pom.xml
> DBACLD-164334 : CVE-2023-5685 org.jboss.xnio_xnio-api

- pom.xml
The current `xstream` `1.4.20` is affected by [CVE-2024-47072](https://x-stream.github.io/CVE-2024-47072.html).
Updating `xstream` to ´1.4.21´ resolves the CVE
Related PR: https://github.com/kiegroup/droolsjbpm-integration/pull/3068
> [7.67.x-blue] NO-ISSUE: Bump `xstream` to version `1.4.21`

- pom.xml
The current protobuf-java '3.19.6' version is is affected by https://access.redhat.com/security/cve/cve-2024-7254
Updating to '4.28.2' resolves the CVE, as all the other lower versions including 4.28.1 has this vulnerability.
> [7.67.x-blue] update protobuf libraries version to 3.25.6

- pom.xml
The current version is affected by CVE-2023-6236. So upgrading to  2.2.5.Final version of wildfly-elytron and infinispan to 4.0.28.Final.
> [7.67.x-blue] upgrade wildfly elytron library

- pom.xml
**referenced Pull Requests**:  
* https://github.com/kiegroup/jbpm-work-items/pull/308
* https://github.com/kiegroup/jbpm/pull/2451
> [DBACLD-164346] Bump smack jar version from 3.1.0 to 4.0.2

- pom.xml
Issue in the remoting code that we're putting in from JBoss. EAP 7.4.20 is using wildfly, so aligning with that version.
> [CVE] Fix CVE-2021-20250 (jboss-remoting)
