optaplanner-bom/pom.xml

dependencies for planner domain support

PLANNER-325 - Data modeler support for basic OptaPlanner annotations

---

kie-platform-bom/pom.xml
pom.xml

* removed plugin versions already coming from jboss-parent
* removed depMgmt for deps already in ip-bom
* removed org.mortbay.jetty deps as they are not needed anymore

Upgrade IP BOM to 6.0.0.CR31 + related build changes

---

pom.xml

New version of Cargo plugin is released: https://codehaus-cargo.atlassian.net/wiki/pages/viewpage.action?pageId=19103755
Among other things it brings improved handling in case of container startup or deployment failure, see: https://codehaus-cargo.atlassian.net/browse/CARGO-1375

Upgrade Cargo plugin version to 1.4.19

---

pom.xml

See also: 
- https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/169
- https://github.com/uberfire/uberfire/pull/337
- https://github.com/uberfire/uberfire-extensions/pull/258
- https://github.com/droolsjbpm/kie-wb-common/pull/337
- https://github.com/droolsjbpm/jbpm-designer/pull/220
- https://github.com/droolsjbpm/jbpm-form-modeler/pull/46
- https://github.com/droolsjbpm/jbpm-console-ng/pull/395
- https://github.com/droolsjbpm/drools-wb/pull/156
- https://github.com/droolsjbpm/optaplanner-wb/pull/56
- https://github.com/droolsjbpm/kie-wb-distributions/pull/261

UF-295 - Updrading lucene to 5.3.1

---

pom.xml

Similar change already done directly in UF.
This will solve all those issues with port binding when running parallel builds.

[GUVNOR-2410] disable UF git/ssh daemons for unit testing

---

kie-platform-bom/pom.xml
pom.xml

* this is a temporary solution until we upgrade to ip-bom which contains the same
upgrade

Upgrade Weld from 1.1.31.Final to 2.3.3.Final and Weld API from 1.1.Final to 2.3.SP1

---

kie-third-party-bom/pom.xml
pom.xml

Don't merge yet. Changes needed in other repos and they need review.

Upgrade to IP BOM 7.0.0.CR3

---

script/release/update-version-all.sh

* we need to separately change the versions for the user BOMs since they no longer inherit from the top-level kie-parent
@mbiarnes please take a look

Fix update-versions-all after recent kie-parent changes

---

pom.xml

See https://issues.jboss.org/browse/GUVNOR-2181 and referenced BPSMPL.
@psiroky @romartin Is working on a "real" Lienzo Mockito release and GAV.... this will be updated.
This is Phase 1, replacing the existing Grid Widget.

GUVNOR-2181: Guided Decision Table Editor: Add support for linked tables

---

kie-bom/pom.xml

See also: 
- https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/215
- https://github.com/droolsjbpm/kie-docs/pull/104

DROOLS-1131,JBPM-5080 - docs code dependency management

---

pom.xml

[RHBRMS-2447] add maven-invoker-plugin:2.0.0 into pluginMgmt

---

pom.xml

* the override is either no longer necessary,
or it can be done only via version property
@mbiarnes please take a look

Remove no longer needed parts of depMgmt

---

pom.xml

Other PRs in the series:
https://github.com/droolsjbpm/guvnor/pull/322
https://github.com/droolsjbpm/jbpm-console-ng/pull/426

[6.4.x][RHBRMS-2447] add maven-invoker-plugin:2.0.0 into pluginMgmt

---

optaplanner-bom/pom.xml

Add optaplanner-persistence-jackson and optaplanner-test to optaplanner-bom

---

pom.xml

See https://issues.jboss.org/browse/GUVNOR-2600

GUVNOR-2600: Expose Dynamic Bean Validation through DataModelOracle

---

kie-bom/pom.xml
pom.xml

- Adds the data source managment modules to the kie-bom
- Adds some dependencies required by the data source management modules to the kie-parent

JBPM-5233: Data source management

---

guvnor-bom/pom.xml

See https://issues.jboss.org/browse/GUVNOR-2637

GUVNOR-2637: Remove Inbox feature

---

script/utils/remove-trailing-spaces.sh
script/utils/tabs2spaces.sh

* one script replaces tabs with spaces; the other
removes trailing whitespaces

Add utility scripts

---

kie-bom/pom.xml

This has been discussed with @ge0ffrey about adding these two into kie-bom.
Please review on it.

RHBRMS-2548 Add kie-server-rest/services-optaplanner into kie-bom

---

script/git-all.sh
script/mvn-all.sh

@mbiarnes could you please review this?

Allow custom repo lists for git-all and mvn-all scripts

---

pom.xml

Define a property for the latest Kie release, to be used in
droolsjbpm-knowledge/kie-api when checking API compatibility,
this allows productization to override this.

RHBRMS-2552 Define a property for the latest Kie release.

---

pom.xml

upgraded to jboss-ip-bom 6.0.8.Final

---

pom.xml

@psiroky, here is the property we discussed in the droolsjbpm/jbpm#604

Introduce a property for org.jboss.xnio for WildFly 10

---

guvnor-bom/pom.xml
pom.xml

Guvnor ALA dependencies update to get this PR: https://github.com/droolsjbpm/guvnor/pull/359 working. It includes Arquillian Cube, Docker Client and Wildfly Swarm

- Guvnor ALA dependencies updates in parent pom

---

optaplanner-bom/pom.xml

Ensemble:
https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/284
https://github.com/droolsjbpm/optaplanner/pull/224
https://github.com/droolsjbpm/kie-wb-distributions/pull/360

PLANNER-657 optaplanner-docs migration from DocBook to AsciiDoc

---

kie-bom/pom.xml

Added new form modules for a better components separation.

Improving ObjectSelector widget on forms.

---

kie-bom/pom.xml

Reponened this PR with same branch name as the PR for kie-wb-common (https://github.com/droolsjbpm/kie-wb-common/pull/493).
@manstis I have fixed the missing sources artifact from the comment on the last PR. 
THanks!

Stunner artifacts added for KIE BOM.

---

script/git-all.sh
script/mvn-all.sh

@mbiarnes please take a look. This should fix the issue with spaces as part of commit msg (the issue is not related to the Jenkins upgrade).

git-all,mvn-all: allow spaces as part of arg. lines

---

drools-bom/pom.xml

https://issues.jboss.org/browse/GUVNOR-2709
There are 3 PRs in the change bundle:
https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/287 
https://github.com/droolsjbpm/drools-wb/pull/309
https://github.com/droolsjbpm/kie-wb-distributions/pull/369

GUVNOR-2709 : Move client side Verification codes to a separate module

---

pom.xml

Upgrade to final GWT 2.8.0 and Guava 20.0-rc1

---

kie-bom/pom.xml

See https://issues.jboss.org/browse/JBPM-5381

JBPM-5381: Added Stunner artifacts into KIE BOM that provide the workbench & guvnor integration.

---

pom.xml

@psiroky please ;).
IMO, we can delete our guava fork repo now.

Upgrade to Guava 20.0

---

jbpm-bom/pom.xml
kie-bom/pom.xml
script/repository-list.txt

KIE forms jBPM integration

---

pom.xml

Hi,
I have updated revapi plugin version.
Thanks for merging.
Marian

Update revapi version

---

drools-bom/pom.xml

https://issues.jboss.org/browse/GUVNOR-2710
All the PRs:
https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/321
https://github.com/droolsjbpm/kie-wb-common/pull/581
https://github.com/droolsjbpm/drools-wb/pull/352
https://github.com/droolsjbpm/optaplanner-wb/pull/123
https://github.com/droolsjbpm/kie-wb-distributions/pull/421

GUVNOR-2710 : Make client side Verifier a web worker.

---

kie-bom/pom.xml

JBPM-5452: Case Modeller

---

drools-bom/pom.xml

https://issues.jboss.org/browse/GUVNOR-2773 
Related to:
https://github.com/droolsjbpm/drools-wb/pull/373

GUVNOR-2773 : [Guided Decision Table] ValidationWebWorkerServlet fails to load web worker

---

README.md

@ge0ffrey could you please review this?

README: update dependency requirements

---

pom.xml

only makes sense to merge with PR https://github.com/jboss-integration/jboss-integration-platform-bom/pull/342

[RHBRMS-2675] pdfbox: XML External Entity vulnerability

---

kie-bom/pom.xml
script/repository-list.txt

Follow up after https://github.com/droolsjbpm/kie-wb-playground/pull/1
@ge0ffrey Can you please take a look?

PLANNER-707: Workbench "import example dialog": Embed stock example repositories

---

ide-configuration/intellij-configuration/code-style/intellij-code-style_droolsjbpm-java-conventions.xml

Fixed IDEA style configuration spitted from https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/342

Static star notation is generally forbidden

---

kie-uberfire-extensions-bom/pom.xml

Depends on https://github.com/uberfire/uberfire/pull/603

Moving Social Activities Framework from kie-uberfire-extensions to uberfire-extensions

---

kie-bom/pom.xml

- Added new Forms ADF modules
These PR's should be merged together:
https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/364
https://github.com/droolsjbpm/kie-wb-common/pull/640
https://github.com/droolsjbpm/jbpm-console-ng/pull/609
https://github.com/droolsjbpm/jbpm-designer/pull/533
https://github.com/droolsjbpm/appformer/pull/66
https://github.com/droolsjbpm/kie-wb-distributions/pull/446

JBPM-5573: Stunner - Integration of latest KIE Forms API & implementations

---

kie-dmn-bom/pom.xml
kie-platform-bom/pom.xml
pom.xml

Proposal for adding Kie DMN BOM.
With consistency with other Kie -based projects.

Add Kie DMN BOM

---

pom.xml

Let's see if the latest fixes around the annotation processors helped or not...
Please don't merge this yet, I will need to run several full builds to make sure everything works.

Disable compiler forking again

---

pom.xml

Add plugin information for ```com.coderplus.maven.plugins:copy-rename-maven-plugin```

Declare com.coderplus.maven.plugins:copy-rename-maven-plugin version information

---

script/repository-list.txt

jBPM now depends on KIE DMN, so order needs to change

kie-dmn needs to be built before jbpm

---

pom.xml

Hi, @psiroky,
here is the change we discussed recently. It allows to generate full revapi report including the ignored changes. See all related commits below.
Thanks
Marian

Introduce profile for revapi report generation

---

kie-user-bom-parent/pom.xml
pom.xml

Upgrade IP BOM from 7.0.0.CR6 to 7.0.0.CR7

---

kie-bom/pom.xml

Needs to be merged together with:
https://github.com/droolsjbpm/jbpm/pull/763
https://github.com/droolsjbpm/kie-wb-distributions/pull/469

[GUVNOR-2889] rename 'kie-wb-distribution-wars-*.war' to 'kie-wb-*.war'

---

kie-bom/pom.xml

kie-bom required changes for kie-server DMN extension.

DROOLS-1460 DMN extension for kie-server

---

pom.xml

All downstream repository have been fixed.

Fail on duplicated classes by default

---

pom.xml

I need the xmlunit dependency for new JUnit tests for the MarshallerHelper in KIE-Server as part of JBPM-5775.

JBPM-5775: Added xmlunit test dependencies.

---

script/release/DSL-scripts/01.KIE_pushReleaseBranches.sh
script/release/DSL-scripts/02.KIE_deployLocally.sh
script/release/DSL-scripts/05.KIE_pushTag.sh
script/release/DSL-scripts/06.KIE_removeReleaseBranches.sh
script/release/DSL-scripts/07.KIE_updateToNextDevelopmentVersion.sh
script/release/DSL-scripts/08.KIE_copyBinariesToFilemgmt.sh
script/release/DSL-scripts/KIE_Release.sh

changed organization name to kiegroup
fixed text for parameter introduction

DSL plugin: changed SettingsName to SettingsId

---

pom.xml

Needed for unit tests for: https://issues.jboss.org/browse/JBPM-5775

Added jsonassert as managed test dependency.

---

pom.xml

Hey @manstis @hasys 
Here is the lienzo-core version upgrade. This fixes some bugs that you already know.. :)
Also created the upgrade for IP bom -> https://github.com/jboss-integration/jboss-integration-platform-bom/pull/359
Thanks!
Roger

JBPM-5595: Upgrade lienzo-core to version 2.0.286-RELEASE.

---

pom.xml

Hi @psiroky, @ge0ffrey it is just small changes. It is not very clear what is wrong when you are trying to enable checkstyle for now. This changes can make migration much easier.

LogViolationToConsole of checkstyle plugin is configurable

---

pom.xml

[7.0.x][GUVNOR-2991] add xstream-hibernate dependency version

---

optaplanner-bom/pom.xml

- Add definitions of optaplanner-wb-guided-rule-editor modules
Part of:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/425
https://github.com/kiegroup/drools/pull/1178
https://github.com/kiegroup/drools-wb/pull/433
https://github.com/kiegroup/optaplanner-wb/pull/143
https://github.com/kiegroup/kie-wb-distributions/pull/486

PLANNER-350: Workbench: scoreHolder support in Guided Rule Editor

---

optaplanner-bom/pom.xml

- Add definitions of optaplanner-wb-guided-rule-editor modules
Backporting changes from master branch.
Part of:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/431
- https://github.com/kiegroup/drools/pull/1202
- https://github.com/kiegroup/drools-wb/pull/452
- https://github.com/kiegroup/optaplanner-wb/pull/148
- https://github.com/kiegroup/kie-wb-distributions/pull/487

[7.0.x] PLANNER-350: Workbench: scoreHolder support in Guided Rule Editor

---

pom.xml

@krisv @psiroky could you please have a look?

Added kie server router to bpms distribution zip

---

kie-bom/pom.xml
pom.xml

Hey @manstis @psiroky 
Until [this one](https://github.com/jboss-integration/jboss-integration-platform-bom/pull/366) is merged and the IP BOM released, here are the lienzo upgrades for our KIE BOM,.
Thanks!

JBPM-5490: Upgrade to lienzo 2.0.287-RELEASE.

---

optaplanner-bom/pom.xml
pom.xml

Together with https://github.com/kiegroup/optaplanner/pull/311

PLANNER-807 optaplanner-core-gwt

---

kie-bom/pom.xml

- Added dependencies for the kie-server-controller-standalone and kie-server-controller-standalone-impl modules

JBPM-5946 Create Standalone Controller

---

pom.xml

This should be merged after 7.0.0.Final is released.

Upgrade Errai version to 4.0.1-SNAPSHOT

---

pom.xml

Add kie-maven-plugin into pluginMgmt

---

script/release/update-version-all-community-settings.xml
script/release/update-version-all-productized-settings.xml

(cherry picked from commit 9ce77887fe384681c22bc6282c030391bc4fc26f)

added kie repo to settings.xml

---

pom.xml

Added dependencies for concurrency api. We need them to use ManagedExecutorService.

UF-506: Added dependencies for concurrenci-api

---

kie-bom/pom.xml

See https://issues.jboss.org/browse/GUVNOR-3288

GUVNOR-3288: [DMN Editor] Merge work to date into kiegroup/master

---

kie-bom/pom.xml

Changed new client module needed for:
JBPM-5736: Update taskforms component menu on task/process change.
JBPM-5985: Forms are generated incorrectly after a removal of the process/task variable.
JBPM-5723: If you delete a data field, there is no response in the form connected to it.
JBPM-5911: DatePicker should be created from LocalDate, LocalDateTime and OffsetDateTime data types.
@jsoltes @manstis  could you take a look?
Relates to:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/465
https://github.com/kiegroup/kie-wb-common/pull/946
https://github.com/kiegroup/jbpm-designer/pull/633
https://github.com/kiegroup/jbpm-wb/pull/778
https://github.com/kiegroup/kie-wb-distributions/pull/543

JBPM-5736, JBPM-5985, JBPM-5723 & JBPM-5911 Form synchronization when model changes

---

pom.xml

Needs to be merged *after* https://github.com/kiegroup/kie-jenkins-scripts/pull/14
@mbiarnes can you please take a look?
cc @porcelli @desmax74 
Jenkins execute full downstream build

Require at least Maven 3.3.9

---

guvnor-bom/pom.xml

- adds the guvnor-ala-ui modules dependencies.

GUVNOR-3130: Release an initial version of Guvnor ALA UI

---

kie-bom/pom.xml
pom.xml

New Kie maven takari plugin.
PR related kiegroup/droolsjbpm-integration#1030 and kiegroup/kie-wb-common#941

[GUVNOR-3016] New Kie Maven Takari Plugin

---

pom.xml

jgit upgrade needed by appformer - can be removed once moved to IP BOM

---

kie-bom/pom.xml

This dependency is actually already managed in the `kie-dmn-bom` BOM.

GUVNOR-3168 GUVNOR-3167 [DMN Editor] Write unmarshaller marshaller

---

guvnor-bom/pom.xml
pom.xml

GUVNOR-3023: Support provisioning of KIE Server instances by Guvnor ALA
https://issues.jboss.org/browse/GUVNOR-3023

GUVNOR-3023: Support provisioning of KIE Server instances by Guvnor ALA

---

kie-bom/pom.xml

GUVNOR-3168 [DMN Editor] Write unmarshaller

---

guvnor-bom/pom.xml

(cherry picked from commit f8ac69ec9ae60b30d6d15184cb9333d2c6b49ec9)

GUVNOR-3128: Store Guvnor ALA state using VFS (#485)

---

pom.xml

Hey @manstis @hasys 
This is the upgrade to `lienzo 2.0.291-RELEASE`. As usually, created the PR too for IP BOM:
https://github.com/jboss-integration/jboss-integration-platform-bom/pull/372
Thanks!

JBPM-5967: Upgrade to lienzo 2.0.291-RELEASE.

---

kie-bom/pom.xml

@manstis @jsoltes  can you review it?
This PR is part of an ensemble, please merge with:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/490
https://github.com/kiegroup/kie-wb-common/pull/1009
https://github.com/kiegroup/drools-wb/pull/561
https://github.com/kiegroup/optaplanner-wb/pull/192
https://github.com/kiegroup/kie-wb-distributions/pull/563
https://github.com/kiegroup/jbpm-wb/pull/817
https://github.com/kiegroup/jbpm-form-modeler/pull/128

[7.2.x] JBPM-5531: Problems after deleting a form that is used as a subform in other form.

---

kie-bom/pom.xml

Copy of https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/490
@manstis @jsoltes can you review it?
This PR is part of an ensemble, please merge with:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/508
https://github.com/kiegroup/kie-wb-common/pull/1069
https://github.com/kiegroup/drools-wb/pull/576
https://github.com/kiegroup/optaplanner-wb/pull/201
https://github.com/kiegroup/jbpm-wb/pull/844
https://github.com/kiegroup/kie-wb-distributions/pull/581
https://github.com/kiegroup/jbpm-form-modeler/pull/132

[7.3.x] JBPM-5531: Problems after deleting a form that is used as a subform in other form.

---

pom.xml

New version released - see http://narayana.io/

Raise Narayana version to 5.6.4

---

pom.xml

Cherrypick of https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/504

[7.3.x] Raise Narayana version to 5.6.4

---

script/branch-mapping.yaml

@mbiarnes could you please review?

Add 7.3.x branch mapping

---

pom.xml

GUVNOR-3025: OpenShift S2I (Source to Image) Integration
https://issues.jboss.org/browse/GUVNOR-3025

GUVNOR-3025: OpenShift S2I (Source to Image) Integration

---

kie-platform-bom/pom.xml

RHBRMS-2870 - added missing dependencies for org.apache.httpcomponents

---

guvnor-bom/pom.xml

(cherry picked from commit 5d62f963778a80821adbf589ddd8666059ddbae7)

GUVNOR-3404: Openshift Provider Integration + UI integration (#530)

---

kie-bom/pom.xml

Copy of https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/490
@manstis @jsoltes can you review it?
This PR is part of an ensemble, please merge with:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/493
https://github.com/kiegroup/kie-wb-common/pull/1011
https://github.com/kiegroup/drools-wb/pull/564
https://github.com/kiegroup/optaplanner-wb/pull/193
https://github.com/kiegroup/jbpm-wb/pull/819
https://github.com/kiegroup/kie-wb-distributions/pull/565
https://github.com/kiegroup/jbpm-form-modeler/pull/126

[8.0.x] JBPM-5531: Problems after deleting a form that is used as a subform in other form.

---

kie-bom/pom.xml

Adding https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/536 into master

JBPM-6148 - rename kie-wb-runtime to kie-wb-monitoring

---

script/branch-mapping.yaml

Needs to be merged _after_ https://github.com/kiegroup/kie-soup/pull/1

Add kiegroup/kie-soup into branch-mapping file

---

pom.xml

[GUVNOR-3500] New project creation fails from Guvnor ALA OpenShift Provider
https://issues.jboss.org/browse/GUVNOR-3500

[GUVNOR-3500] New project creation fails from Guvnor ALA OpenShift Provider

---

pom.xml

(cherry picked from commit 667797cabc820e65bc27b50a7a84aab69fa656b8)

removed ironjacamar

---

kie-platform-bom/pom.xml
pom.xml

@mariofusco @psiroky could you please review?

RHBRMS-2990 Upgrade mvel to 2.3.2.Final

---

RELEASE-README.md
jbpm-bom/pom.xml
pom.xml
script/repository-list.txt

@jsoltes @cristianonicolai could you please review?
IMPORTANT: Don't merge untils there's a fix for this JBPM-6499 on jbpm-designer (https://github.com/kiegroup/jbpm-designer/pull/682)
This PR is a part of an ensemble:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/579
https://github.com/kiegroup/kie-wb-common/pull/1240
https://github.com/kiegroup/jbpm-wb/pull/918
https://github.com/kiegroup/kie-wb-distributions/pull/640
https://github.com/kiegroup/kie-wb-playground/pull/40

[7.4.x] RHBPMS-5000: Remove old jBPM-Form-Modeler

---

RELEASE-README.md
jbpm-bom/pom.xml
pom.xml
script/repository-list.txt

@jsoltes @cristianonicolai could you please review?
IMPORTANT: Don't merge untils there's a fix for this JBPM-6499 on jbpm-designer (https://github.com/kiegroup/jbpm-designer/pull/681)
This PR is a part of an ensemble:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/580
https://github.com/kiegroup/kie-wb-common/pull/1241
https://github.com/kiegroup/jbpm-wb/pull/919
https://github.com/kiegroup/kie-wb-distributions/pull/641
https://github.com/kiegroup/kie-wb-playground/pull/41

[7.5.x] RHBPMS-5000: Remove old jBPM-Form-Modeler

---

kie-platform-bom/pom.xml

See my comment at 
https://github.com/kiegroup/droolsjbpm-build-bootstrap/commit/4aed36dec9e408773eadf69a3f96bd2d6eb94273#commitcomment-25536383

fixed duplicate kie-platform-bom import

---

script/mvn-all.sh

The script now takes another script as parameter(--clean-up-script=<path>).
That clean-up script will be executed for every repository in the list.

mvn-all: optional clean-up of build artifacts to save disk space

---

script/git-add-remote-gerrit.sh
script/git-clone-others.sh
script/release/kie-createReleaseBranches.sh
script/release/kie-pushReleaseBranches.sh

- renamed script and twaeked to push to Gerrit instead of jbpm-integration
- removed obsolete kie-eap-modules - not needed for master & twaeked for pushing to Gerrit
- splittet creating and pushing release branches in different scripts

Push to gerrit

---

script/git-all.sh
script/mvn-all.sh

Backport of #609 + the previous fixes to make sure the cherry-pick is clean

[6.5.x] mvn-all fixes and enhancements

---

pom.xml

See:
- https://issues.jboss.org/browse/RHBRMS-2946
- https://issues.jboss.org/browse/DROOLS-1828
- https://github.com/errai/errai/pull/303#discussion_r150894909
---
---
- https://github.com/errai/errai/pull/303
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/617
- https://github.com/AppFormer/uberfire/pull/913
- https://github.com/kiegroup/drools-wb/pull/708

DROOLS-1828: [Guided Decision Table] New Toolbar

---

pom.xml

DON'T MERGE until https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/601 was merged.

RHBPMS-4819: upgrade batik

---

script/release/update-version-all.sh

since appformer will have it's own version

excluded appformer from update kie versions

---

script/release/kie-createReleaseBranches.sh
script/release/update-version-all.sh

version change also for kie-soup and appformer without skipping these reps

fixed update-all-version.sh incl. kie-soup and appformer

---

pom.xml

Replacement for https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/623
Depends on https://github.com/kiegroup/jbpm/pull/1090

Remove duplicated dependencies

---

script/repository-list.txt

before `drools`
/cc @mariofusco

Add repo `drlx-parser` to the list of repositories

---

script/release/update-version-all.sh

MERGE makes only sense if drlx-parser is part of repository_list.txt

tweaked update-all-versions for drlx-parser

---

pom.xml

Hey @manstis @hasys 
This is the lienzo-core upgrade for the selection multiple stuff.
Notice created the PR for IP BOM as well. See https://github.com/jboss-integration/jboss-integration-platform-bom/pull/410
Please merge together with https://github.com/kiegroup/kie-wb-common/pull/1309
Thanks!

JBPM-6102: Upgrade Lienzo to 2.0.293-RELEASE

---

kie-bom/pom.xml

Cherry picking changes from master.

[7.5.x] JBPM-6243 - Rename new controller module dropping the mgmt part

---

script/git-add-remote-gerrit.sh
script/release/git-push-tag-all.sh

@pszubiak: please review this and approve this so I will merge it. these are the changes we saw today, kie-eap-modules is needed in Gerrit and there were the semicolons misplaced.

removed the skipping of kie-eap-modules

---

pom.xml

merge together with https://github.com/kiegroup/droolsjbpm-integration/pull/1321

fix for JBPM-4531 - Upgrade Quartz to Version 2.x

---

script/release/kie-createReleaseBranches.sh
script/release/kie-pushReleaseBranches.sh
script/release/kie-pushTag.sh

Now, since the pushing to Gerrit works (tags and branches and all reps) the last scripts pointing to jboss-integration were changed to point to Gerrit

Push to gerrit 7.5.x

---

script/release/kie-deployLocally.sh
script/release/kie-pushTag.sh

(cherry picked from commit 5919e3105107ab06a43ab86cf41c46c5b208d4d4)

fixed scripts to clone release branches from gerrit

---

script/release/kie-createJbpmInstaller.sh

DON'T MERGE.
Merge together with https://github.com/kiegroup/kie-jenkins-scripts/pull/136

fixed jbpm installer for internal reps

---

drools-bom/pom.xml

See https://issues.jboss.org/browse/RHDM-44

RHDM-44 Remove the drools-verifier from drools-bom

---

pom.xml

Dependent PR in kie-wb-common repository
https://github.com/kiegroup/kie-wb-common/pull/1378

[7.5.x] RHDM-250: adding enforcer ignore for ASM classes

---

kie-bom/pom.xml
pom.xml

Add deployment validation module for failing deployment with unmigrated niogit directory.

AF-648 : Change Project from a folder in a repo to a repository

---

kie-bom/pom.xml
pom.xml

Hey @mbiarnes @tiagodolphine @manstis 
Created ticket and branches with same names for doing the right Jenkins integration tests. 
See https://issues.jboss.org/browse/JBPM-6806
Please **DO NOT MERGE** yet.
Thanks!

[DO NOT MERGE] JBPM-6806: Included KIE Lienzo artifacts into the dependency management.

---

kie-bom/pom.xml

https://issues.jboss.org/browse/RHDM-344
https://issues.jboss.org/browse/DROOLS-2314
Bundle:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/707
https://github.com/kiegroup/kie-wb-distributions/pull/688

DROOLS-2314 : Standalone decision central is not branded

---

pom.xml

Issues related:
https://github.com/kiegroup/appformer/pull/116
https://github.com/kiegroup/kie-wb-common/pull/1317
https://github.com/kiegroup/drools-wb/pull/727
https://github.com/kiegroup/jbpm-designer/pull/732
https://github.com/kiegroup/jbpm-wb/pull/966
https://github.com/kiegroup/kie-wb-distributions/pull/664

AF-913: Integration with AF-933

---

kie-bom/pom.xml

This also belong to the https://github.com/kiegroup/kie-wb-common/pull/1437 pr, @pefernan could you please review?

add version for kie-wb-common-data-modeller-backend test-jar

---

script/release/errai-productizedVersion.sh

a new script for the errai version for prod releases/tags is required

added script for errai prod version

---

kie-bom/pom.xml

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/723
* https://github.com/kiegroup/appformer/pull/251
* https://github.com/kiegroup/kie-wb-common/pull/1520

AF-1080: New project with the same name as another project in different space disappear after server restarts

---

pom.xml

Used in droolsjbpm-integration

Added new dependencies for embedded apache camel component

---

kie-bom/pom.xml

(cherry picked from commit 1024e66cc0b65f538bc9c943aaa770fe34f8d33e)
https://issues.jboss.org/browse/AF-1079
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/728
https://github.com/kiegroup/appformer/pull/271
https://github.com/kiegroup/kie-wb-common/pull/1561
https://github.com/kiegroup/drools-wb/pull/839

[7.5.x] AF-1079: Empty 'Validation errors' popup in Decision/Business Central

---

pom.xml

Ensemble with:
- https://github.com/kiegroup/droolsjbpm-knowledge/pull/301
- https://github.com/kiegroup/kie-wb-common/pull/1546
- https://github.com/kiegroup/jbpm-designer/pull/758
- https://github.com/kiegroup/drools-wb/pull/840

BAQE-400: Turn on UnusedImports checkstyle module

---

pom.xml

Supersedes:
kiegroup/kie-wb-common#1553
kiegroup/drools-wb#837
kiegroup/jbpm-wb#1026
kiegroup/optaplanner-wb#268
kiegroup/kie-wb-distributions#720
To be merged together with kiegroup/appformer#267.

RHDM-390,RHDM-391: Work around ERRAI-1101 using antrun

---

kie-bom/pom.xml

https://issues.jboss.org/browse/AF-1079
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/725
https://github.com/kiegroup/appformer/pull/259
https://github.com/kiegroup/kie-wb-common/pull/1537
https://github.com/kiegroup/drools-wb/pull/835

AF-1079: Empty 'Validation errors' popup in Decision/Business Central

---

pom.xml

PR for master branch originally as #737

RHPAM-670 Upgrade wildfly swarm to 2018.3.3 

---

drools-bom/pom.xml

@mariofusco could you please review when you have a bit of time?

DROOLS-2390 Add drools-test-suite tests jar to drools-bom

---

kie-user-bom-parent/pom.xml
pom.xml

Signed-off-by: Piotr Szubiakowski <pszubiak@redhat.com>

DROOLS-2503 Switch Maven repository to repository.jboss.org.

---

script/release/errai-productizedVersion.sh

(cherry picked from commit ae9c71b0afb49e114939f16cdb3ba5e8f2444d31)

cd into errai directory for resolving git commands

---

script/branch-mapping.yaml

Signed-off-by: Piotr Szubiakowski <pszubiak@redhat.com>

Update errai branch for PR builder plug-in.

---

script/checks/repo-dep-tree.pl

Use a color to highlight dependencies of the target repository

---

script/release/kie-copyBinariesToFilemgmt.sh
script/repository-list.txt

@krisv @tsurdilo @mbiarnes here is the single zip jbpm server distribution

JBPM-7372 - single zip distribution for jBPM

---

pom.xml

Related:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/770
https://github.com/errai/errai/pull/350
https://github.com/kiegroup/appformer/pull/404
https://github.com/kiegroup/kie-wb-common/pull/1925
https://github.com/kiegroup/drools-wb/pull/878
https://github.com/kiegroup/jbpm-wb/pull/1162
https://github.com/kiegroup/optaplanner-wb/pull/288
https://github.com/kiegroup/kie-wb-distributions/pull/773

AF-1226: Improve error handling displaying additional info to the GenericErrorPopup

---

pom.xml

@AntStephenson could you please review?

BAQE-439 Introduce dependency on Tomcat DBCP for DB connection pooling

---

pom.xml

https://issues.jboss.org/browse/RHBRMS-3118

RHBPMS-5184: upgrades POI due OOM

---

pom.xml

Fixing the broken tests in Drools and jBPM

Return Narayana version back to 5.6.4.Final

---

drools-bom/pom.xml

https://issues.jboss.org/browse/DROOLS-2690
Bundle:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/774
https://github.com/kiegroup/kie-wb-common/pull/1972
https://github.com/kiegroup/drools-wb/pull/886

DROOLS-2690 : Create a Scenario asset

---

script/release/update-version-all.sh
script/repository-list.txt

(cherry picked from commit 1223c6af389f7c91d9364af33d2aa502980c653c)

PLANNER-1154 Rename OptaShift to OptaWeb (7.7.x)

---

script/release/update-version-all.sh
script/repository-list.txt

(cherry picked from commit 1223c6af389f7c91d9364af33d2aa502980c653c)

PLANNER-1154 Rename OptaShift to OptaWeb (7.5.x)

---

script/checks/repo-dep-tree.pl

For example droolsjbpm-build-bootstrap has no direct dependencies on
kie-soup and appformer but it imports their BOMs so it should be built
after them.

Detect BOM imports when building dependency tree

---

pom.xml

@mswiderski Please take a look when you have time. No major changes are expected.
@MarianMacik FYI

Cargo 1.6.9 is released

---

kie-bom/pom.xml

https://issues.jboss.org/browse/DROOLS-2764
Bundle:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/783
https://github.com/kiegroup/kie-wb-common/pull/1985
https://github.com/kiegroup/drools-wb/pull/894
https://github.com/kiegroup/optaplanner-wb/pull/292
https://github.com/kiegroup/jbpm-wb/pull/1182
https://github.com/kiegroup/kie-wb-distributions/pull/780
https://github.com/kiegroup/kie-docs/pull/946

DROOLS-2764 : Remove dead code in AuthoringPerspective, AdministrationPerspective and Social Home Page

---

pom.xml

@mareknovotny could you please take a look?

Upgrade tomcat-dbcp to 9.0.11 to consume fixes

---

pom.xml

We add a second version to use a working old version with settings.xml with authentication for Jenkins and a new one inside the compiler   @domhanak @jhrcek @porcelli @mareknovotny @ederign

[AF-1519] Added a second version of takari

---

kie-bom/pom.xml

Part of ensemble:
https://github.com/kiegroup/kie-jenkins-scripts/pull/319
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/807
https://github.com/kiegroup/kie-wb-distributions/pull/800

Remove tomcat distribution of workbenches from kie bom

---

script/release/kie-copyBinariesToFilemgmt.sh

Change path of built documentation to be published

---

script/release/kie-copyBinariesToFilemgmt.sh

[7.11.x] Change path of built documentation to be published

---

pom.xml

Reverting kiegroup/droolsjbpm-build-bootstrap#820 as @rsynek upgraded not ready tomcat-jta

Revert "Decouple narayana-tomcat version from narayana version"

---

kie-bom/pom.xml

Add new module to Kie bom
@Rikkola @kkufova @romartin @manstis
PRs
https://github.com/kiegroup/kie-wb-common/pull/2062
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/806

[DROOLS-2898] Add kie-wb-common-command-api to Kie bom

---

pom.xml

Workbench offline 7.11.x
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/829
https://github.com/kiegroup/kie-soup/pull/57
https://github.com/kiegroup/appformer/pull/459
https://github.com/kiegroup/kie-wb-common/pull/2117
https://github.com/kiegroup/kie-wb-distributions/pull/811
@porcelli @domhanak @jhrcek

[AF-1528] 7.11.x Workbench offline

---

pom.xml

https://github.com/kiegroup/kie-wb-distributions/pull/806
https://github.com/kiegroup/kie-wb-common/pull/2103
https://github.com/kiegroup/appformer/pull/450
https://github.com/kiegroup/kie-soup/pull/55
@porcelli @domhanak @jhrcek

[AF-1528] Workbench offline

---

pom.xml

Signed-off-by: Piotr Szubiakowski <pszubiak@redhat.com>

RHDM-588 Add support for PME dependency overwriting for freemarker.

---

pom.xml

These PRs should be merged all together:
https://github.com/kiegroup/kie-soup/pull/65
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/839
https://github.com/kiegroup/appformer/pull/470
https://github.com/kiegroup/kie-wb-common/pull/2135
https://github.com/kiegroup/kie-wb-distributions/pull/818
https://github.com/kiegroup/kie-docs/pull/1094

AF-1528 revert

---

pom.xml

Signed-off-by: Piotr Szubiakowski <pszubiak@redhat.com>

RHDM-373 jackson-databind version update from 2.8.9 to 2.8.10 - 7.11.x.

---

pom.xml

https://github.com/kiegroup/kie-jenkins-scripts/pull/335
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/840
https://github.com/kiegroup/kie-wb-distributions/pull/820

BAQE-96: Update version of selenium test dependencies

---

pom.xml

Contains container id for WildFly14

Raise Cargo version to 1.6.11

---

script/release/kie-deployLocally.sh

(cherry picked from commit f644e2cf563aeb8166767df465d424e68c1376c4)

removed parallel test executions

---

pom.xml

Related PRs:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/798
* https://github.com/kiegroup/appformer/pull/434
* https://github.com/kiegroup/kie-wb-common/pull/2037
* https://github.com/kiegroup/drools-wb/pull/910
* https://github.com/kiegroup/jbpm-wb/pull/1187
* https://github.com/kiegroup/optaplanner-wb/pull/294
* https://github.com/kiegroup/kie-wb-distributions/pull/792

[AF-1220]: Infinispan Dependencies added

---

jbpm-bom/pom.xml

in addition removed outdated entires for work items that have been moved to jbpm-work-items repository and new groups id org.jbpm.contrib

JBPM-7880 - ElasticSearch event emitter for runtime events

---

pom.xml

Reverts kiegroup/droolsjbpm-build-bootstrap#867

Revert "BAQE-730 - Change revapi to check against 7.11.0.Final"

---

pom.xml

moved deps into future jboss-ip-bom 8.3.0.Final
merge this when jboss-ip-bom 8.3.0.Final was released and our kie-reps upgraded

Alignment to JBEAP 7.2 - 1st

---

pom.xml

moved deps into future jboss-ip-bom 8.3.0.Final
merge this when jboss-ip-bom 8.3.0.Final was released and our kie-reps upgraded

Alignment to JBEAP 7.2 - 2nd

---

pom.xml

https://issues.jboss.org/browse/JBPM-7685
This is a sync upgrade for narayana-jta version
* https://github.com/kiegroup/droolsjbpm-integration/pull/1554

JBPM-7685: upgrading narayana-jta to 5.9.0.Final

---

pom.xml

added missing dependency cxf-rt-rs-client

---

pom.xml

following https://github.com/kiegroup/drools/pull/2148

Align version management for ch.obermuhlner:big-math

---

kie-bom/pom.xml

https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/892
https://github.com/kiegroup/kie-wb-common/pull/2304
https://github.com/kiegroup/kie-wb-distributions/pull/849

AF-1709: Adding kie-wb-common-profile-backend

---

kie-bom/pom.xml
pom.xml

Raise the fabric8 OpenShift/K8S client version to 4.1.0 
Associated PR: https://github.com/kiegroup/droolsjbpm-integration/pull/1611

[JBPM-7834] Provide OpenShiftStartupStrategy

---

kie-user-bom-parent/pom.xml
pom.xml

org.mvel is in jboss-ip-bom [8.3.3.Final](https://github.com/jboss-integration/jboss-integration-platform-bom/blob/8.3.3.Final/pom.xml#L326)

moved org.mvel to jboss-ip-bom 8.3.3.Final

---

pom.xml

Contains support for Java 11 on WildFly
@MarianMacik FYI

Raise Cargo version to 1.7.1

---

jbpm-bom/pom.xml
script/repository-list.txt

Complete set of PRs 
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/907
https://github.com/kiegroup/appformer/pull/591
https://github.com/kiegroup/kie-wb-common/pull/2374
https://github.com/kiegroup/jbpm-work-items/pull/88
https://github.com/kiegroup/jbpm-wb/pull/1268
https://github.com/kiegroup/kie-wb-distributions/pull/860

JBPM-8000 - Work item repository administration in business central

---

kie-bom/pom.xml

Assemble with:
https://github.com/kiegroup/kie-soup/pull/80
https://github.com/kiegroup/kie-wb-common/pull/2360 and

JBPM-7686: Stunner - Minimal Graphical Constraint Editor

---

pom.xml

(cherry picked from commit 1ff9d7a0be3ac11d3872470d48f557a759003412)

moved io.undertow to jboss-ip-bom 8.4.0.Final

---

pom.xml

@mariofusco 
Removed duplicated soap dependency added in this commit: https://github.com/kiegroup/droolsjbpm-build-bootstrap/commit/7033cb909f337cb566cbec4c70f8f65058a96d6c

Duplicated SOAP dependency in the jdk 11 commit

---

pom.xml

Once ready, should be merged together with:
https://github.com/kiegroup/droolsjbpm-integration/pull/1638
https://github.com/kiegroup/jbpm/pull/1375

JBPM-7951 Update tomcat-dbcp to 9.0.13

---

kie-bom/pom.xml
pom.xml

Providing a solution for WorkBench integration with KieServer OpenShiftStartupStrategy by implementing a new ServerTemplateOpenShiftStorage.
Related PRs:
- https://github.com/kiegroup/droolsjbpm-integration/pull/1670
- https://github.com/kiegroup/kie-wb-common/pull/2319
- https://github.com/kiegroup/droolsjbpm-integration/pull/1611

JBPM-7834: Provide OpenShiftStartupStrategy - WB Integration

---

pom.xml

@ederign @porcelli @manstis @danielezonca
Scope of this PR is to add the version definition of  org.kie:kie-gwthelper-maven-plugin definition to main pom.

[DROOLS-3654] Adding org.kie:kie-gwthelper-maven-plugin definition

---

pom.xml

RHPAM-1874: migrated org.infinispan and its dependencies to jboss-ip-bom

---

pom.xml

Upgrading ISPN to last version because it contains some new analyzers we need
@ederign @porcelli @tomasdavidorg 
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/938
* https://github.com/kiegroup/appformer/pull/663
* https://github.com/kiegroup/kie-wb-common/pull/2531

[AF-1904]: Upgraded ISPN version to 9.4.x

---

script/release/update-version-all.sh

some outstanding block of code for drlx-parser in script ;)

removed drlx-parser for BXMSPROD-312

---

kie-user-bom-parent/pom.xml
pom.xml

removed ISPN and migrated it to jboss-ip-bom

upgraded jboss-ip-bom

---

pom.xml

**merge not before 29.10.2018** - people has to be informed and a few days for preparations are needed

upgraded maven.min.version to 3.5.4

---

pom.xml

downgraded maven.min.version  to 3.5.2 to ensure that Travis jobs will build.

downgraded Maven min version

---

pom.xml

https://issues.jboss.org/browse/DROOLS-3097
@kkufova @gitgabrio @Rikkola 
PR list:
- https://github.com/kiegroup/drools-wb/pull/1113
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/945

[DROOLS-3097] Added commons-csv dependency

---

kie-bom/pom.xml
pom.xml

https://issues.jboss.org/browse/JBPM-7886
@tomasdavidorg Making draft PRs for tests
Bundle:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/944
https://github.com/kiegroup/kie-wb-common/pull/2581
https://github.com/kiegroup/kie-wb-distributions/pull/906

JBPM-7886 : Update WildFly Swarm to Thorntail

---

kie-bom/pom.xml

On this PR:
- New module for AppFormer.js component Spaces Screen.
Related PRs:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/936
https://github.com/kiegroup/appformer/pull/662
https://github.com/kiegroup/kie-wb-common/pull/2526
https://github.com/kiegroup/drools-wb/pull/1090
https://github.com/kiegroup/jbpm-wb/pull/1314
https://github.com/kiegroup/optaplanner-wb/pull/329
https://github.com/kiegroup/kie-wb-distributions/pull/893

 AF-1787 - Integrate AppFormer.js on Business Central

---

pom.xml

https://issues.jboss.org/browse/JBPM-8455

upgrade of jackson to 2.9.8

---

pom.xml

Superseeds https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/946

DROOLS-3868 Update antlr-runtime version to 4.7.2

---

pom.xml

https://issues.jboss.org/browse/BXMSPROD-361

BXMSPROD-361 - upgrade of Apache Camel

---

kie-bom/pom.xml

Assembly:
https://github.com/kiegroup/appformer/pull/709
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/958
https://github.com/kiegroup/kie-wb-common/pull/2650
https://github.com/kiegroup/kie-wb-distributions/pull/927

JBPM-8168: add kie-wb-common-stunner-case-mgmt-project-backend module for case modeler

---

kie-dmn-bom/pom.xml
pom.xml

@etirelli @baldimir @danielezonca @vblagoje

DROOLS-4075 DMN merge upstream PMML evaluators

---

script/repository-list.txt

DROOLS-4147 Add CI jobs for new repository kie-jpmml-integration

---

pom.xml

See:
- https://issues.jboss.org/browse/DROOLS-4117
- https://issues.jboss.org/browse/DROOLS-4118
---
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/971
- https://github.com/kiegroup/kie-wb-common/pull/2694

DROOLS-4118: [DMN Designer] Documentation tab - Show information from the DMN diagram in the documentation tab

---

drools-bom/pom.xml

@gitgabrio @danielezonca @kkufova 
Required for PRs: 
- https://github.com/kiegroup/kie-wb-distributions/pull/939
- https://github.com/kiegroup/drools-wb/pull/1167

Drools 4141 - Split scesim client module in core and business central modules 

---

pom.xml

GitHub: potential security vulnerabilities in dependencies

security vulnerability:update of tika-core

---

uberfire-bom/pom.xml

Add the new dependencies that will call backend services.
Merge with: https://github.com/kiegroup/appformer/pull/724

AF-1987: Adding client with backend calls dependencies

---

pom.xml

5.4 has quite a lot of bug fixes from previous 5.0 that has been used

AF-2097: upgraded JGit version for 5.4

---

pom.xml

Change-Id: Ie8bd502242adeec1b5c04233a8acbb0c67e95eeb
@MarianMacik this is a requested upgrade from you.
related jira from CXF project https://issues.apache.org/jira/browse/CXF-7905

RHPAM-1873: upgrade to newer version due EJB tests failing on NPE

---

pom.xml

GitHub: potential security vulnerabilities in dependencies

security vulnerability:update of pdfbox

---

kie-platform-bom/.gitignore
kie-platform-bom/pom.xml
pom.xml

The kie-platform-bom is useful for end users and also by product builds.

Reintroduce kie-platform-bom

---

script/release/update-version-all.sh

saw in the release right now that the update-version-all.sh script did not work 100%.
This PR fixes it.

fixed update script for bumping up correctly uberfire

---

pom.xml

Change-Id: I5274c91f9d74781a1e660f966dd02e2022c3bbc1
There are not used deps for qpid.

removed qpid depedencies as they are not used

---

script/branch-mapping.yaml

(cherry picked from commit 49772b8e525994358e4248f6d41eaea278476b34)

added new branch for branch mapping

---

kie-bom/pom.xml
pom.xml

Reverts kiegroup/droolsjbpm-build-bootstrap#1032
Targeted incorrect branch,

Revert "Drools 3727 "

---

kie-bom/pom.xml

Renaming kie-wb-common-stunner-submarine to kie-wb-common-stunner-kogito

---

kie-bom/pom.xml

KOGITO-197 Renaming any reference of submarine to kogito

---

pom.xml

https://issues.jboss.org/browse/BXMSPROD-526
dependent PR: https://github.com/kiegroup/appformer/pull/798

BXMSPROD-526 version.org.uberfire property set to ${version.org.kie}

---

script/release/update-version-all.sh
uberfire-bom/pom.xml

uberfire version = kie version
update-version-all.sh has to be fixed and the fixed version in uberfire-bom/pom.xml was replaced by a variable

New version update

---

script/release/kie-removeReleaseBranchesGerrit.sh

(cherry picked from commit d640fec9687e096243aa6147901075a81c288651) 
cherry-picked from master branch

BXMSPROD-524: added shell script for removing branches on Gerrit (#1053)

---

script/release/kie-deleteNpmLockFiles.sh

https://issues.jboss.org/browse/BXMSPROD-477

BXMSPROD-477 delete npm/yarn package lock files

---

pom.xml

Reverts kiegroup/droolsjbpm-build-bootstrap#1055

Revert "Upgrade javax.validation from 1.0.0.GA to 2.0.1.Final "

---

script/release/01_cloneBranches.sh
script/release/02_createReleaseBranches.sh
script/release/03_upgradeVersions.sh
script/release/04_pushReleaseBranches.sh
script/release/05a_communityDeployLocally.sh
script/release/05b_prodDeployLocally.sh
script/release/05c_dailyBuildDeployLocally.sh
script/release/05d_dailyBuildProdInstall.sh
script/release/06_uploadBinariesToNexus.sh
script/release/07_addRemoteToGerrit.sh
script/release/08a_communityPushTags.sh
script/release/08b_prodPushTags.sh
script/release/09_createjBPM_installers.sh
script/release/10_uploadBinariesToFilemgmt.sh
script/release/addAndCommit.sh

When the last pipeline for community releases is done and everything works correctly a lot of useless scripts will be removed. Until now they are needed.

added new scripts for pipelines

---

pom.xml

Reverts kiegroup/droolsjbpm-build-bootstrap#1076

Revert "Work around flaky tests by Surefire automatically rerunning them"

---

kie-bom/pom.xml
pom.xml

Merge  Kogito branch (DROOLS-3727) into master details on [this PR](https://github.com/kiegroup/kie-wb-common/pull/2923)
Related PR's
https://github.com/kiegroup/kie-wb-common/pull/2923
https://github.com/kiegroup/kie-wb-distributions/pull/977

DROOLS-3727 - Initial Kogito work branch into master

---

script/release/01_cloneBranches.sh
script/release/02_createReleaseBranches.sh
script/release/03_upgradeVersions.sh
script/release/04_pushReleaseBranches.sh
script/release/05a_communityDeployLocally.sh
script/release/05b_prodDeployLocally.sh
script/release/05c_dailyBuildDeployLocally.sh
script/release/05d_dailyBuildProdInstall.sh
script/release/06_uploadBinariesToNexus.sh
script/release/07_addRemoteToGerrit.sh
script/release/08a_communityPushTags.sh
script/release/08b_prodPushTags.sh
script/release/09_createjBPM_installers.sh
script/release/10_uploadBinariesToFilemgmt.sh
script/release/addAndCommit.sh
script/release/kie-deleteNpmLockFiles.sh

new sh scripts for pipelines (same as we did on master)

added sh scripts for new pipelines

---

uberfire-bom/pom.xml

Part of an ensemble
https://github.com/kiegroup/appformer/pull/807
kiegroup/kie-wb-common#2917
kiegroup/drools-wb#1235
kiegroup/jbpm-wb#1393
kiegroup/optaplanner-wb#347
kiegroup/kie-wb-distributions#964

AF-2125: Adding Ace and Editors versions

---

kie-bom/pom.xml

See https://issues.jboss.org/browse/KOGITO-407
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1087
- https://github.com/kiegroup/kie-wb-common/pull/2973

KOGITO-407: [DMN Designer] Unit tests: kie-wb-common-dmn-webapp-kogito-runtime

---

README.md

Google Reader has been discontinued.

Remove Google Reader link

---

script/release/01_cloneBranches.sh
script/release/02_createReleaseBranches.sh
script/release/03_upgradeVersions.sh
script/release/04_pushReleaseBranches.sh
script/release/05a_communityDeployLocally.sh
script/release/05b_prodDeployLocally.sh
script/release/05c_dailyBuildDeployLocally.sh
script/release/05d_dailyBuildProdInstall.sh
script/release/06_uploadBinariesToNexus.sh
script/release/08a_communityPushTags.sh
script/release/08b_prodPushTags.sh
script/release/09_createjBPM_installers.sh
script/release/10_uploadBinariesToFilemgmt.sh
script/release/addAndCommit.sh

replaced scripts variable names by standard inputs

---

pom.xml

Change-Id: I93f79ce4a53473e2d1605bc378803dcdd5d8e7f0

undertow update to 2.0.23.Final

---

pom.xml

GitHub: potential security vulnerabilities in dependencies

security vulnerability:update of commons-fileupload

---

pom.xml

Change-Id: I945e356b9f7aa424b0bf0ccbeeb60774a33717eb
https://issues.jboss.org/browse/JBPM-8848

JBPM-8848: Upgrade of thorntail to 2.5.0.Final

---

uberfire-bom/pom.xml

**Task**: [AF-2328](https://issues.jboss.org/browse/AF-2328)
**Related PRs**:
- https://github.com/kiegroup/appformer/pull/837
- https://github.com/kiegroup/droolsjbpm-integration/pull/1936
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1101

[AF-2328] Adding uberfire-security-backend project

---

kie-bom/pom.xml

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1092
* https://github.com/kiegroup/kie-wb-common/pull/2991
* https://github.com/kiegroup/jbpm-wb/pull/1401
* https://github.com/kiegroup/drools-wb/pull/1256
* https://github.com/kiegroup/kie-wb-distributions/pull/986
* https://github.com/kiegroup/optaplanner-wb/pull/349

[AF-2310]: Removed deprecated samples project

---

pom.xml

GitHub: potential security vulnerabilities in dependencies

security vulnerability:update of commons-compress

---

script/release/08b_prodPushTags.sh

@mareknovotny removed the dry run once - but accidental there has been a push to commit it again

removed -n for dry run

---

kie-platform-bom/pom.xml
narayana-integration-bom/pom.xml
pom.xml

RHPAM-2466
requires https://github.com/kiegroup/droolsjbpm-integration/pull/1939

RHPAM-2466 naraya-integration-bom project created

---

pom.xml

Counterpart in OptaPlanner:
https://github.com/kiegroup/optaplanner/pull/615

PLANNER-1716 Switch OptaPlanner to junit-vintage-engine

---

script/release/05a_communityDeployLocally.sh
script/release/05b_prodDeployLocally.sh
script/release/05c_dailyBuildDeployLocally.sh
script/release/05d_dailyBuildProdInstall.sh
script/release/06_uploadBinariesToNexus.sh
script/release/08a_communityPushTags.sh
script/release/09_createjBPM_installers.sh
script/release/10_uploadBinariesToFilemgmt.sh

kie.property file with kieVersion will not be any more created.
kieVersion will be fetched from droolsjbpm-build-bootstrap/pom.xml (release branch after the version update)

removed kie.properties file

---

script/release/09_createjBPM_installers.sh

if .kieVersion was not changed back to .version, the build.properties in jbpm-installer isn't replaced right and the script fails

changed .kieVersion to .version

---

optaplanner-bom/pom.xml

Relates to https://github.com/kiegroup/optaplanner/pull/595

Add optaplanner-spring-boot-* in optaplanner-bom

---

pom.xml

BXMSPROD-580: version.frontend-maven-plugin property added with 1.8.0 value

---

script/release/10_uploadBinariesToFilemgmt.sh

Jira: https://issues.jboss.org/browse/PLANNER-1734

Add employee-rostering docs to filemgmt

---

pom.xml

Jira: https://issues.jboss.org/browse/PLANNER-1695
Prerequisite for:
- https://github.com/kiegroup/optaweb-employee-rostering/pull/312
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/211
- https://github.com/kiegroup/droolsjbpm-integration/pull/1931
- https://github.com/kiegroup/jbpm-work-items/pull/114

Add Spring Boot dependencies

---

pom.xml

Jira: https://issues.jboss.org/browse/PLANNER-1695
Is a prerequisite for: https://github.com/kiegroup/optaweb-vehicle-routing/pull/222
Requires: 
https://github.com/kiegroup/kie-wb-common/pull/3042
https://github.com/kiegroup/drools-wb/pull/1270
https://github.com/kiegroup/drools/pull/2666

Upgrade Assertj version to 3.14.0

---

pom.xml

Jira: https://issues.jboss.org/browse/PLANNER-1695
Merge before https://github.com/kiegroup/optaweb-vehicle-routing/pull/239

Add neovisionaries internationalization dependency management

---

uberfire-bom/pom.xml

Merge with: 
https://github.com/kiegroup/appformer/pull/854

AF-2353: Adding Appformer Kogito Bridge dependency

---

pom.xml

Change-Id: I13fe2066d46f564bd6ae827f331e59e5d18016d7

xmlpull upgrade to have jigsaw and maven metadata fixed

---

pom.xml

@mareknovotny the [test build](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/mbiarnes/job/mbiarnes_kieparent/2/console) was OK but UNSTABLE.
There only failed one [test](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/mbiarnes/job/mbiarnes_kieparent/2/testReport/) that also failed in [daily build master](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/daily-build/job/daily-build-pipeline-master/30/testReport/)

BXMSPROD-572: removed obsolete deps

---

pom.xml

Jira: https://issues.jboss.org/browse/PLANNER-1695
Merge before: https://github.com/kiegroup/optaweb-employee-rostering/pull/348

Add Springfox Swagger dependencies

---

pom.xml

As a prerequisite to this PR:
https://github.com/kiegroup/appformer/pull/799
https://github.com/kiegroup/kie-wb-common/pull/2916
Signed-off-by: Evan Zhang <evan.zhang@redhat.com>

[AF-2058] Provide alternative implementation of uberfire-nio2-impl backed by OCP/K8S

---

kie-bom/pom.xml

BXMSPROD-621
dependent PR kiegroup/kie-wb-distributions/pull/1004

BXMSPROD-621 org.kie:business-monitoring-webapp:thorntail added to kie-bom

---

uberfire-bom/pom.xml

Signed-off-by: Evan Zhang <evan.zhang@redhat.com>

KIECLOUD-256: Default to ocp/k8s backed uberfire java nio2 file system implementation

---

script/release/10_uploadBinariesToFilemgmt.sh

Jira: https://issues.redhat.com/browse/PLANNER-1741
Prerequisite for: https://github.com/kiegroup/optaplanner-website/pull/191

[PLANNER-1741] Add optaweb-vehicle-routing docs to filemgmt

---

script/release/10_uploadBinariesToFilemgmt.sh

a directory for the optaweb-vehicle-routing docs on filemgmt.jboss.or is needed

PLANNER-1741: added directory for optaweb-vehicle-routing docs

---

pom.xml

@mareknovotny 
@jiripetrlik
@danielezonca

[Drools-4915] fix for CVE-2019-10219

---

narayana-integration-bom/pom.xml

https://issues.redhat.com/browse/RHPAM-2484

RHPAM-2484 - aligning tomcat-dbcp version

---

kie-bom/pom.xml

**Task**: [AF-2366](https://issues.redhat.com/browse/AF-2366)
**Related PRs**:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1151
- https://github.com/kiegroup/kie-soup/pull/124
- https://github.com/kiegroup/appformer/pull/872
- https://github.com/kiegroup/kie-wb-common/pull/3098
- https://github.com/kiegroup/jbpm-wb/pull/1406
- https://github.com/kiegroup/drools-wb/pull/1278
- https://github.com/kiegroup/optaplanner-wb/pull/352
- https://github.com/kiegroup/kie-wb-distributions/pull/1005

[AF-2366] BC Maven Archetype Support

---

script/release/10_uploadBinariesToFilemgmt.sh
script/release/prepareUploadDir.sh

- new script that creates a directory where all binaries that have to be uploaded to filemgmt.jboss.org are stored
- upload file to filemgmt.jboss.org changed, because now the binaries are caught from the new created dir

added script for creating dir for upload binaries

---

pom.xml

https://issues.redhat.com/browse/BXMSPROD-635

BXMSPROD-635: upgrade of ISPN to the latest 9.4.16.Final version

---

kie-bom/pom.xml

**Task**: [AF-2363](https://issues.redhat.com/browse/AF-2363)
**Related PRs**:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1171
- https://github.com/kiegroup/appformer/pull/881
- https://github.com/kiegroup/kie-wb-common/pull/3126
- https://github.com/kiegroup/drools-wb/pull/1293
- https://github.com/kiegroup/optaplanner-wb/pull/353
- https://github.com/kiegroup/jbpm-wb/pull/1410
- https://github.com/kiegroup/kie-wb-distributions/pull/1009

[AF-2363] Be able to create projects from empty repositories

---

script/release/10_uploadBinariesToFilemgmt.sh
script/release/prepareUploadDir.sh

Jira: https://issues.redhat.com/browse/PLANNER-1811
Merge with:
- https://github.com/kiegroup/optaweb-employee-rostering/pull/377
- https://github.com/kiegroup/optaplanner-website/pull/199

[PLANNER-1811] Rename optaweb-employee-rostering filenames for consistency

---

pom.xml

Ensemble together with:
https://github.com/kiegroup/kie-wb-common/pull/3067

KOGITO-666: Add managed dependencies for kogito webapps

---

pom.xml

Change-Id: I224ffee183cb7f8aec20a65b417e60c72db509a8
https://issues.redhat.com/browse/BXMSPROD-639

Upgrade of commons-beanutils to 1.9.4

---

pom.xml

https://issues.redhat.com/browse/PLANNER-1839
- kiegroup/droolsjbpm-build-bootstrap/pull/1192
- kiegroup/kie-docs/pull/2200 (optional)
- kiegroup/optaplanner/pull/696
- kiegroup/optaweb-employee-rostering/pull/395
- kiegroup/optaweb-vehicle-routing/pull/268

PLANNER-1839: Upgrade Asciidoctor

---

pom.xml

Merge with:
https://github.com/kiegroup/optaplanner/pull/701
https://github.com/kiegroup/jbpm-work-items/pull/124
https://github.com/kiegroup/optaweb-employee-rostering/pull/397
https://github.com/kiegroup/optaweb-vehicle-routing/pull/270

[7.33.x] RHPAM-2734: Downgrade Spring dependencies for RHOAR compatibility

---

pom.xml

Needed for Swagger-UI tests with Springboot, following the approach documented [here](https://github.com/kiegroup/kie-docs/blob/master/doc-content/enterprise-only/springboot/bus-app-swagger_proc.adoc)

Added WebJar for Swagger UI dependency

---

pom.xml

Merge with: https://github.com/kiegroup/optaplanner/pull/681
Jira: https://issues.redhat.com/browse/PLANNER-1851

[PLANNER-1851] Add JAXB dependencies for JSON support

---

script/release/10_uploadBinariesToFilemgmt.sh
script/release/create_filemgmt_links.sh

Forced scripts to use the proper keys

use of proper ssh keys

---

pom.xml

Review Lienzo dependency in Dashbuilder
--
Merge with:
https://github.com/kiegroup/appformer/pull/916

AF-2442: Review Lienzo dependency in Dashbuilder

---

pom.xml

upgrades of
version.org.jboss.xnio
version.org.wildfly.common

BXMSPROD-685: upgrade of versions

---

drools-bom/pom.xml

@danielezonca @jomarko Can you please review it?
Thanks!
https://issues.redhat.com/browse/DROOLS-5154

DROOLS-5154: Added kogito scesim modules.

---

Jenkinsfile.nightly
nightly.stages

BXMSPROD-583 cleanWS removed and DEFAULT_BRANCH job parameter adapted

---

kie-bom/pom.xml

- Declares the task assigning modules

PLANNER-1627: TaskAssigningPlanning & TaskAssignigRuntime kie-sever extensions (target architecture)

---

pom.xml

Merge with https://github.com/kiegroup/optaplanner/pull/720

Add JSONB dependencies for JSON serialization

---

pom.xml

BXMSPROD-672 netty upgraded to 4.1.43.Final

---

pom.xml

Change-Id: I51886d6cc4665073d7fe071e03d6b38afd6f4741
Merge together with kiegroup/droolsjbpm-integration/pull/2041

Upgrade of quartz to 2.3.2

---

Jenkinsfile.nightly

BXMSPROD-583 nightly pipeline file created for 7.33.x

---

Jenkinsfile.nightly

BXMSPROD-583 Jenkinsfile with parameters

---

optaplanner-bom/pom.xml

Merge with: https://github.com/kiegroup/optaplanner/pull/727

Add optaplanner-persistence-jsonb dependencies to optaplanner-bom

---

upstream.stages

BXMSPROD-710 upstream adapted to github plugin requirements

---

Jenkinsfile.nightly
nightly.stages

BXMSPROD-719 default branch parameter removed from nightly pipeline

---

Jenkinsfile
downstream.production.stages
downstream.stages
upstream.stages

BXMSPROD-710
kie-mem24g label is needed since we use the same pipeline for community and non-community projects

BXMSPROD-710 upstream/downstream pipelines adatped to github plugin requirements

---

Jenkinsfile.nightly

BXMSPROD-719 PRODUCT_VERSION and UMB_VERSION parameters added

---

Jenkinsfile.nightly
nightly.stages

BXMSPROD-719 nightly tweak backported to 7.33.x

---

README.md
RELEASE-README.md

BXMSPROD-633: upgraded READMEs

---

Jenkinsfile.nightly

BXMSPROD-719 BRANCH_NAME variable added to RHBA_PROPERTIES_GENERATOR_PATH job. Backported to 7.33.x

---

Jenkinsfile.nightly

BXMSPROD-719 BRANCH_NAME variable added to RHBA_PROPERTIES_GENERATOR_PATH job

---

pom.xml

BXMSPROD-722 netty upgraded to 4.1.46

---

Jenkinsfile.nightly

BXMSPROD-729
Depends on https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/14

BXMSPROD-729 file upload mechanism moved from pmebuild.groovy script to the Jenkins.nightly itself

---

Jenkinsfile
downstream.production.stages
downstream.stages
upstream.stages

BXMSPROD-710
Depends on https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/18

BXMSPROD-710 skipTests treatment

---

pom.xml

merge with this kiegroup/optaweb-vehicle-routing/pull/290

PLANNER-1912: Move Pitest config so that it can be overriden easily

---

Jenkinsfile

BXMSPROD-710 Jenkinsfile centralized for every RHBA repo

---

downstream.production.stages

BXMSPROD-735 downstream.production xml settings pointing to the nightly one

---

Jenkinsfile
downstream.stages

BXMSPROD-740 -fae duplicated attribute removed form the maven command and tests report

---

pom.xml

PR group:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1273
- https://github.com/kiegroup/appformer/pull/943
- https://github.com/kiegroup/droolsjbpm-integration/pull/2064
- https://github.com/kiegroup/kie-wb-common/pull/3269
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/296
- https://github.com/kiegroup/optaweb-employee-rostering/pull/425

BXMSPROD-741: Manage Node, npm and yarn versions

---

downstream.production.stages

https://issues.redhat.com/browse/BXMSPROD-747

BXMSPROD-747 skip test failures during production build

---

Jenkinsfile.nightly

https://issues.redhat.com/browse/BXMSPROD-575

BXMSPROD-575 Jenkinsfile.nightly notification emails

---

Jenkinsfile

https://issues.redhat.com/browse/BXMSPROD-754

BXMSPROD-754 Jenkinsfile pipeline timeout increased to 1200 minutes

---

pom.xml

https://issues.redhat.com/browse/BXMSPROD-750

BXMSPROD-750: upgrade of jackson-databind to 2.9.10.4

---

drools-bom/pom.xml
jbpm-bom/pom.xml

merge together with https://github.com/kiegroup/droolsjbpm-integration/pull/2075

[DROOLS-5195] remove no longer supported integration modules

---

kie-soup-bom/pom.xml

Part of https://github.com/kiegroup/kie-soup/pull/137

KOGITO-1546 XStreamUtils kie-soup refactoring

---

pom.xml

https://issues.redhat.com/browse/JBPM-9135

JBPM-9135: upgrade of SpringBoot to 2.2.6 and Springframework to 5.2.5

---

Jenkinsfile
Jenkinsfile.nightly

https://issues.redhat.com/browse/BXMSPROD-773

BXMSPROD-773 archive maven log files

---

Jenkinsfile

https://issues.redhat.com/browse/BXMSPROD-773

BXMSPROD-773 Jenkinsfile typo

---

kie-bom/pom.xml
pom.xml

Change-Id: Ibfc9ba78c40b5d6b72eda7d7ff437da4be691de8
https://issues.redhat.com/browse/JBPM-9044
List of PRs:
* this PR #1203 
* kiegroup/appformer/pull/910
* kiegroup/jbpm/pull/1601
* kiegroup/droolsjbpm-integration/pull/2033
* kiegroup/jbpm-work-items/pull/125
* kiegroup/kie-wb-common/pull/3273
* kiegroup/drools-wb/pull/1349
* kiegroup/jbpm-wb/pull/1429
* kiegroup/optaplanner-wb/pull/368
* kiegroup/kie-wb-distributions/pull/1022

Upgrade Wildfly to 18.0.1.Final

---

pom.xml

https://issues.redhat.com/browse/BXMSPROD-746

BXMSPROD-746: Upgrade Node, npm and Yarn

---

pom.xml

For more details see: https://issues.redhat.com/browse/AF-2489
Ensemble together with:
- https://github.com/kiegroup/appformer/pull/955

AF-2489: Consolidate wildfly.security version

---

Jenkinsfile
compilation.stages
pullrequest.stages

PLEASE don't merge yet - let's discuss this in next BXMS-prod meetg.

BXMSPROD-753: added stages for PRs and CDBs and adapted Jenkinsfile

---

Jenkinsfile

https://issues.redhat.com/browse/BXMSPROD-793

BXMSPROD-793 archiveArtifacts splitted by artifact types

---

script/release/update-version-all.sh

Depends on https://github.com/kiegroup/optaplanner/pull/783

Update optaplanner quickstarts version

---

pom.xml

Reverts kiegroup/droolsjbpm-build-bootstrap#1235

Revert "BXMSPROD-685: upgrade of different version of org.jboss.spec"

---

Jenkinsfile

depends on https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/27
https://issues.redhat.com/browse/BXMSPROD-801

BXMSPROD-801 print git Information report

---

pom.xml

this PR and followup on fixing Enforcer ban-duplicated-classes:
- https://github.com/kiegroup/appformer/pull/979
- https://github.com/kiegroup/jbpm-wb/pull/1438
- https://github.com/kiegroup/kie-wb-distributions/pull/1035

RHPAM-2943: keycloak upgrade to 9.0.3

---

pom.xml

https://issues.redhat.com/browse/RHPAM-2806

RHPAM-2806: upgrade of cxf-core to 3.2.12

---

uberfire-bom/pom.xml

Please merge with:
https://github.com/kiegroup/appformer/pull/956

AF-2471: Adding Dashbuilder Runtime

---

uberfire-bom/pom.xml

Dependencies for new projects added in: 
https://github.com/kiegroup/appformer/pull/970
Please merge with  https://github.com/kiegroup/appformer/pull/970

AF-2474: Adding dashbuilder-kie-server project versions

---

pom.xml

Merge with:
https://github.com/kiegroup/optaplanner/pull/796
https://github.com/kiegroup/kie-benchmarks/pull/85
https://github.com/kiegroup/kie-wb-distributions/pull/1036
https://github.com/kiegroup/jbpm/pull/1674
https://github.com/kiegroup/droolsjbpm-integration/pull/2124
https://github.com/kiegroup/optaweb-vehicle-routing/pull/322
https://github.com/kiegroup/optaweb-employee-rostering/pull/448

Bump postgresql version to 42.2.12

---

pom.xml

Adding mock server dependency for testing proxy

[JBPM-9138] - RESTWorkItemHandler doesn't support proxy

---

pom.xml
uberfire-bom/pom.xml

Excluding for now Weld upgrade and keeping other changes from #1320
Merge together with:
- https://github.com/kiegroup/appformer/pull/982
- https://github.com/kiegroup/drools/pull/2932
- https://github.com/kiegroup/jbpm/pull/1669
- https://github.com/kiegroup/droolsjbpm-integration/pull/2127
- https://github.com/kiegroup/jbpm-work-items/pull/132
- https://github.com/kiegroup/optaweb-employee-rostering/pull/450

BXMSPROD-685 upgrade of different dependencies /hibernate, xmlschema

---

Jenkinsfile
compilation.stages
downstream.production.stages
downstream.stages
new.downstream.stages
pullrequest.stages

https://issues.redhat.com/browse/BXMSPROD-753
depends on https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/35

BXMSPROD-753

---

Jenkinsfile.nightly

https://issues.redhat.com/browse/BXMSPROD-781
depends on:
- https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/33
- https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/42
naginator plugin is not available for pipelines https://plugins.jenkins.io/naginator/

BXMSPROD-781 PipelineHelper.retry added

---

pom.xml

- There doesn't seem to be any impact so as per local test
- Will run more tests upon FDB.

Upgrading thorntail to support EAP upgrade

---

pom.xml

merge together with https://github.com/kiegroup/kie-wb-common/pull/3328

BXMSPROD-685: upgrade javassist and GWTMockito to play nice with it

---

pom.xml

Merge together with https://github.com/kiegroup/droolsjbpm-integration/pull/2125

[RHPAM-2977] upgrade to jackson 2.10.4 + wildfly 19

---

pom.xml

This PR is part of an ensemble:
https://github.com/kiegroup/kie-wb-common/pull/3310
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1323
https://github.com/kiegroup/drools-wb/pull/1375
This PR is not part of the ensemble, but is required. It have to be merged alone to generate the new Gwt Jsonix Schema Compiler build:
https://github.com/kiegroup/gwt-jsonix-schema-compiler/pull/8
The following JIRAS are included in this PR:
KOGITO-1553: [DMN Designer] Open a DMN file with an included model - Included Models tab
KOGITO-1776: [DMN Designer] Create a "Load Projects From Client" button
KOGITO-1552: [DMN Designer] Open a DMN file with an included model - DRG Elements

KOGITO-1553: [DMN Designer] Open a DMN file with an included model - Included Models tab

---

pom.xml

https://issues.redhat.com/browse/JBPM-9189
Merge together with:
- kiegroup/kie-wb-common/pull/3330
- kiegroup/jbpm-wb/pull/1440
- kiegroup/kie-wb-distributions/pull/1039

JBPM-9189: upgrading to fixed 19.1.0.SP1 Errai Wildfly distribution

---

Jenkinsfile.nightly

Signed-off-by: Alberto Morales Pérez <almorale@redhat.com>

Update 7.39.x nightly Jenkinsfile

---

pom.xml

@tarilabs @jiripetrlik @manstis 
See https://issues.redhat.com/browse/DROOLS-5451
I launch a FDB to verify it does not broke something

[DROOLS-5451] Upgraded org.jpmml:pmml-model to 1.5.1 version

---

kie-bom/pom.xml

https://issues.redhat.com/browse/JBPM-9201
Merge with 
- https://github.com/kiegroup/jbpm-wb/pull/1442
- https://github.com/kiegroup/kie-wb-distributions/pull/1043

JBPM-9201: fixed classifier for wildfly 19

---

pom.xml

see https://issues.redhat.com/browse/DROOLS-5464

[DROOLS-5464] Add kie-pmml-dependencies version

---

Jenkinsfile

depends on https://github.com/kiegroup/kie-jenkins-scripts/pull/768

additionalArtifactsToArchive moved to specific arhiceArtifact method

---

Jenkinsfile
script/release/01_cloneBranches.sh
script/release/02_createReleaseBranches.sh
script/release/06_uploadBinariesToNexus.sh

Jenkins file sync

---

Jenkinsfile.nightly

https://issues.redhat.com/browse/BXMSPROD-815
Depends on: https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/45

BXMSPROD-815 nightly error action implemented

---

compilation.stages
downstream.stages

removed kie-jpmml-integration and droolsjbpm-tools as upstream projects for FDBs and CDBs

removed repositories as upstream projects

---

drools-bom/pom.xml

Added a new module `drools-metric`
See https://github.com/kiegroup/drools/pull/2900

[BAPL-1259] Add logging for rule performance analysis

---

pom.xml

DROOLS-5530 DMN strongly typed codegen Eclipse MP OpenAPI enum  String

---

Jenkinsfile.nightly

https://issues.redhat.com/browse/BXMSPROD-884
we clone branch/tag from build-configuration project
depends on: https://gitlab.cee.redhat.com/middleware/build-configurations/-/merge_requests/127 and `7.39.x` tag creation on that repo

BXMSPROD-884 nightly build configuration checking out tag

---

Jenkinsfile

https://issues.redhat.com/browse/BXMSPROD-910

BXMSPROD-910 Jenkinsfile job selection improved (7.39.x)

---

Jenkinsfile

https://issues.redhat.com/browse/BXMSPROD-910

BXMSPROD-910 Jenkinsfile job selection improved

---

script/release/06_uploadBinariesToNexus.sh

staging rep should not be dropped after closure

BXMSPROD-886: do not drop staged repository after closing

---

.ci/compilation.stages
.ci/new.downstream.stages
.ci/pullrequest.stages
.ci/upstream.stages

This reverts commit 067bab7923eb64b1f3de5f1e3e980a85a2f23e91.
Depends on https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/96

Revert "BXMSPROD-911 adapted to take forked projects with different name (#1418)

---

pom.xml

Reverts kiegroup/droolsjbpm-build-bootstrap#1348
Merge together with:
- https://github.com/kiegroup/droolsjbpm-knowledge/pull/455
- https://github.com/kiegroup/kie-soup/pull/151
- https://github.com/kiegroup/drools/pull/3042
- https://github.com/kiegroup/droolsjbpm-integration/pull/2194

Revert "[JBPM-9178] Immutable SpringBoot Deployment"

---

kie-bom/pom.xml
pom.xml

(cherry picked from commit 6e9a73f4a476a25635222321c487f20e8fc70d5b)
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1437
* https://github.com/kiegroup/jbpm/pull/1728
* https://github.com/kiegroup/droolsjbpm-integration/pull/2195
* https://github.com/kiegroup/jbpm-wb/pull/1453
* https://github.com/kiegroup/kie-wb-distributions/pull/1051
**How to retest or run**:
* a pull request please add comment: regex **[.\*[j|J]enkins,?.\*(retest|test) this.\*]**
* a full downstream build please add comment: regex …

JBPM-9201: fixed classifier for wildfly 19 (#1371)

---

.github/pull_request_template.md

paste the link(s) from GitHub here
**How to retest or run**:
* a pull request please add comment: regex **[.\*[j|J]enkins,?.\*(retest|test) this.\*]**
* a full downstream build please add comment: regex **[.*\[j|J]enkins,?.\*(execute|run|trigger|start|do) fdb.\*]**
* a compile downstream build please  add comment: regex **[.\*[j|J]enkins,?.\*(execute|run|trigger|start|do) cdb.\*]**
* a full production downstream please add comment: regex **[.\*[j|J]enkins,?.\*(execute|run|trigger|start|do) product fdb.\*]**
* an upstream build please add comment: regex …

change of pull_request_template.dm

---

pom.xml

upstream jira:
https://issues.redhat.com/browse/JBPM-9178

[JBPM-9178] Immutable SpringBoot Deployment

---

pom.xml

added amqp producer/consumer library

[JBPM-9277] JMS Audit Data Replication in spring boot

---

.ci/fullDownstreamBuild.properties
.ci/pullrequest.properties

* link 2
* link 3 etc.
<pre>
</pre>

increased mem for kie-wb-common PR and FDB

---

kie-pmml-bom/pom.xml

Required modification for https://issues.redhat.com/browse/DROOLS-5143

[DROOLS-5143] Add Models tests dependencies

---

uberfire-bom/pom.xml

Add version for components backend project.
https://github.com/kiegroup/appformer/pull/1016
https://github.com/kiegroup/kie-wb-distributions/pull/1048

AF-2577: External Components Support

---

.ci/pullrequest.stages

* link 2
* link 3 etc.
<pre>
</pre>

added kie-jpmml-integration to projectCollection again

---

pom.xml

@danielezonca @tarilabs  @jiripetrlik
See https://issues.redhat.com/browse/KOGITO-3222
This PR declares jandex maven plugin inside kie-parent pom

[KOGITO-3222] Implement jpmml/trustypmml co-existence

---

pom.xml

[DROOLS-5608](https://issues.redhat.com/browse/DROOLS-5608)
* link 2
* link 3 etc.
<pre>
</pre>

[DROOLS-5608] Upgrade MVEL to 2.4.10.Final

---

.ci/compileDownstreamBuild.properties
.ci/fullDownstreamBuild.properties
.ci/pullrequest.properties

* link 2
* link 3 etc.
<pre>
</pre>

removed jvmArgs in mvn commands

---

pom.xml

part of an ensemble of PRs
**JIRA**: https://issues.redhat.com/browse/KOGITO-2277
**referenced Pull Requests**: downstream PRs will appear below.
<pre>
</pre>

KOGITO-2277 fix OpenAPI schema for temporals

---

pom.xml

https://issues.redhat.com/browse/RHDM-1338
Related to:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1461
- https://github.com/kiegroup/kie-soup/pull/156
- https://github.com/kiegroup/appformer/pull/1049
<pre>
</pre>

RHDM-1338 org.apache.logging.log4j:log4j-api and log4j-core 2.13.2

---

pom.xml

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-846
* https://github.com/kiegroup/droolsjbpm-integration/pull/2231
<pre>
</pre>

BXMSPROD-846: upgrade cxf-core to 3.2.14

---

.ci/compileDownstreamBuild.properties
.ci/fullDownstreamBuild.properties
.ci/pullrequest.properties

* link 2
* link 3 etc.
<pre>
</pre>

changed mvn fdb commands for parallel builds using takari extensions

---

pom.xml

**JIRA**:
https://issues.redhat.com/browse/BXMSPROD-994
<pre>
</pre>

BXMSPROD-994: wildfly-elytron upgrade to 1.10.7.Final

---

pom.xml

**JIRA**: 
https://issues.redhat.com/browse/BXMSPROD-995
<pre>
</pre>

BXMSPROD-995: hibernate core upgrade to 5.3.17.Final

---

pom.xml

**Description**
ISPN version upgraded to match RHDG 7.3.6
**JIRA**: 
* https://issues.redhat.com/browse/AF-2604
* https://issues.redhat.com/browse/RHPAM-3089
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1444
* https://github.com/kiegroup/appformer/pull/1031

AF-2604: Infinispan version upgraded to 9.4.19

---

pom.xml

**JIRA**: 
https://issues.redhat.com/browse/RHDM-1331
https://issues.redhat.com/browse/RHPAM-2914
<details>
<summary>
</summary>
</details>

RHDM-1331 update hibernate validator to 6.0.20.Final

---

jbpm-bom/pom.xml
pom.xml

**JIRA**:  [JBPM-9357](https://issues.redhat.com/browse/JBPM-9357)
* https://github.com/kiegroup/droolsjbpm-integration/pull/2238.

[JBPM-9357] Add springboot Kafka WIH test

---

jbpm-bom/pom.xml
pom.xml

Reverts kiegroup/droolsjbpm-build-bootstrap#1466
Merge together with https://github.com/kiegroup/droolsjbpm-integration/pull/2253

Revert "[JBPM-9357] Add springboot Kafka WIH test"

---

jbpm-bom/pom.xml
pom.xml

**JIRA**:  [JBPM-9357](https://issues.redhat.com/browse/JBPM-9357)
After refactoring, these tests to be part of jbpm-work-items, this PR is again needed
**referenced Pull Requests**: [jbpm-work-items#157](https://github.com/kiegroup/jbpm-work-items/pull/157)

[7.44.x][JBPM-9357] Add springboot Kafka WIH test

---

.ci/sonarAnalysis.stages
Jenkinsfile

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-957
<details>
<summary>
</summary>
</details>

BXMSPROD-957 Sonar analysis adapted to JDK11 requirement

---

kie-pmml-bom/pom.xml

See https://issues.redhat.com/browse/DROOLS-5367
This PR just add a new module to kie-pmml bom

[DROOLS-5367] Updated kie-pmml bom

---

pom.xml

**JIRA**: https://issues.redhat.com/browse/DROOLS-5714
**referenced Pull Requests**: part of an ensemble of PRs:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1493
* https://github.com/kiegroup/drools/pull/3155
* (DRAFT) https://github.com/kiegroup/kogito-runtimes/pull/817
the Kogito DRAFT PR downstream can be helpful to understand (one of) potential usages of this utility module.
<details>
<summary>
</summary>
* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product …

DROOLS-5714 DMN produce programmatically OAS first iteration

---

pom.xml

https://issues.redhat.com/browse/BXMSPROD-685
Merge with these PR together:
- https://github.com/kiegroup/appformer/pull/969
- https://github.com/kiegroup/drools/pull/3077
- https://github.com/kiegroup/jbpm/pull/1654
- https://github.com/kiegroup/kie-wb-common/pull/3409
- https://github.com/kiegroup/drools-wb/pull/1373
- https://github.com/kiegroup/jbpm-wb/pull/1434
- https://github.com/kiegroup/kie-wb-distributions/pull/1055

BXMSPROD-685: Weld 3.x upgrade

---

drools-bom/pom.xml

https://github.com/kiegroup/droolsjbpm-knowledge/pull/471
https://github.com/kiegroup/drools/pull/3159
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1498
https://github.com/kiegroup/drools/pull/3159
https://github.com/kiegroup/droolsjbpm-knowledge/pull/471
https://github.com/kiegroup/droolsjbpm-integration/pull/2277
<details>
<summary>
</summary>
* <b>a compile downstream build</b> …

[DROOLS-5658] New alpha network compiler modules

---

pom.xml

Adding kafka version to parent pom
[JBPM-9413](https://issues.redhat.com/browse/JBPM-9413)

[JBPM-9413]  AMQ Streams (Kafka) integration Notifier / producer

---

Jenkinsfile

* link 2
* link 3 etc.
<details>
<summary>
</summary>
</details>

enabled hyphen in regex of job names

---

.ci/pull-request-config.yaml

trying to solve problems like this one
https://github.com/kiegroup/appformer/pull/1067/checks?sha=a74dccf13c50f2c0a09078924b7c40f8f7c23d1d
```
Error:  Failed to execute goal on project uberfire-metadata-backend-infinispan: Could not resolve dependencies for project org.uberfire:uberfire-metadata-backend-infinispan:jar:7.46.0-SNAPSHOT: Failed to collect dependencies at org.arquillian.cube:arquillian-cube-docker-junit-rule:jar:1.15.3 -> org.arquillian.cube:arquillian-cube-docker:jar:1.0.0.Alpha15 -> org.arquillian.cube:arquillian-cube-spi:jar:1.0.0.Alpha15 -> org.arquillian.extension:arquillian-recorder-reporter-api:jar:1.1.2.Final -> org.eclipse.persistence:org.eclipse.persistence.moxy:jar:2.7.6: Failed to read artifact descriptor for …
```

maven connection errors on GA build

---

.ci/pull-request-config.yaml

* link 2
* link 3 etc.
<details>
<summary>
</summary>
</details>

Archive jbpm-container-test logs on GitHub Actions

---

.ci/project-dependencies.yaml
.github/workflows/pull_request.yml

https://issues.redhat.com/browse/BXMSPROD-1005
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1516
* https://github.com/kiegroup/kie-soup/pull/162
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/482
* https://github.com/kiegroup/drools/pull/3206
* https://github.com/kiegroup/optaplanner/pull/1005
* https://github.com/kiegroup/jbpm/pull/1792
* https://github.com/kiegroup/kie-jpmml-integration/pull/46
* https://github.com/kiegroup/lienzo-core/pull/138
* https://github.com/kiegroup/lienzo-tests/pull/111
* https://github.com/kiegroup/appformer/pull/1072
* https://github.com/kiegroup/droolsjbpm-integration/pull/2305
* https://github.com/kiegroup/openshift-drools-hacep/pull/103
* https://github.com/kiegroup/droolsjbpm-tools/pull/122
* …

BXMSPROD-1005 Cache Maven packages

---

Jenkinsfile

<details>
<summary>
</summary>
</details>

enforcer.skip=true added to sonar analysis

---

.ci/pullrequest.properties
.ci/pullrequest.stages
Jenkinsfile

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1086
<details>
<summary>
</summary>
</details>

BXMSPROD-1086 sonar analysis for PR only

---

pom.xml

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1077

[BXMSPROD-1077] Upgrade hibernate to 5.3.18.Final

---

pom.xml

**JIRA**: 
* https://issues.redhat.com/browse/RHPAM-3234
* https://issues.redhat.com/browse/RHDM-1476
<details>
<summary>
</summary>
</details>

RHPAM-3234 httpclient to 4.5.13

---

pom.xml

JIRA: https://issues.redhat.com/browse/BXMSPROD-1077
backporting https://github.com/kiegroup/droolsjbpm-build-bootstrap/commit/d410ffc3e581ccc70067cf4f63e1c462cd660d47
<details>
<summary>
</summary>
</details>

[7.44.x] BXMSPROD-1077 Upgrade hibernate core to 5.3.18.Final

---

uberfire-bom/pom.xml

**JIRA**: [KOGITO-2693](https://issues.redhat.com/browse/KOGITO-2693)
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1504
* https://github.com/kiegroup/appformer/pull/1065
* https://github.com/kiegroup/kie-wb-common/pull/3464
* https://github.com/kiegroup/kogito-tooling/pull/293
<details>
<summary>
</summary>
* <b>an upstream build</b> please add comment: <b>Jenkins run …

KOGITO-2693: Embeddable editors (Milestone 1)

---

pom.xml

https://x-stream.github.io/CVE-2020-26217.html
Obsoletes #1455
Jenkins retest this

Update XStream to 1.4.14 fixing Remote Code Execution (CVE-2020-26217)

---

pom.xml

**JIRA**: 
* https://issues.redhat.com/browse/RHPAM-3094
* https://issues.redhat.com/browse/RHDM-1414
<details>
<summary>
</summary>
</details>

RHPAM-3094 & RHDM-1414 xerces to 2.12.0.SP03

---

.ci/project-dependencies.yaml

project-dependencies adapted from
to
> note: in case you want to increase image size and you browser adds a dark background you always have the chance to inspect browser and change background color to `#ffffff`
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1539
<details>
<summary>
</summary>
* <b>an upstream build</b> please …

project dependencies adapted

---

.ci/project-dependencies.yaml

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1539
<details>
<summary>
</summary>
</details>

project dependencies updated

---

.github/workflows/generate_files.yml
script/repository-list.txt

<details>
<summary>
</summary>
</details>

repository-list opta* projects restored

---

Jenkinsfile
Jenkinsfile.buildchain

depends on: https://github.com/kiegroup/kie-jenkins-scripts/pull/869
<details>
<summary>
</summary>
</details>

Jenkinsfile.buildchain adapted to use custom maven settings file

---

.ci/project-dependencies.yaml

Reverts kiegroup/droolsjbpm-build-bootstrap#1550

Revert "wb-common should not depend on wb-playground"

---

pom.xml

**JIRA**: [JBPM-9557](https://issues.redhat.com/browse/JBPM-9557)
referenced Pull Requests:
- https://github.com/kiegroup/droolsjbpm-integration/pull/2368

[JBPM-9557] Enable sb keycloak test with testcontainers

---

Jenkinsfile.buildchain

**issue**: https://github.com/kiegroup/github-action-build-chain/issues/126
- https://github.com/kiegroup/github-action-build-chain/pull/127
- https://github.com/kiegroup/kie-jenkins-scripts/pull/912
<details>
<summary>
</summary>
</details>

[ISSUE 126] --skipParallelCheckout added to Jenkinsfile.builchain

---

pom.xml

This reverts commit 9a1b93bca65de8a90841d29eed21f355ffaf23b3.
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1579
https://github.com/kiegroup/droolsjbpm-integration/pull/2383
https://github.com/kiegroup/jbpm-work-items/pull/172
<details>
<summary>
</summary>
* <b>a full …

Revert "[JBPM-9549] Upgrade SpringBoot to 2.3.4 (#1565)"

---

kie-soup-bom/pom.xml

TBD
Part of an ensemble. Merge with:
https://github.com/kiegroup/kie-soup/pull/172
https://github.com/kiegroup/appformer/pull/1091

AF-2766: Dashbuilder Prometheus data-set provider

---

pom.xml

see https://github.com/kiegroup/appformer/security/dependabot/pom.xml/io.netty:netty-codec-http/open/
<details>
<summary>
</summary>
</details>

Upgrade netty to 4.1.59.Final

---

Jenkinsfile.revapi

**[BAQE-1546](https://issues.redhat.com/browse/BAQE-1546)**: Revapi clean-up process should be automated

[BAQE-1546] - revapi clean-up process should be automated

---

Jenkinsfile.buildchain

tested by https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/droolsjbpm-integration-master.pr/763/
<details>
<summary>
</summary>
</details>

Jenkinsfile.buildchain sonar cloud error

---

Jenkinsfile.nightly

Pointing to https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/configfiles/editConfig?id=rhba-prod-master
<details>
<summary>
</summary>
</details>

Jenkinsfile.nightly pointing to rhba-prod-master maven settings

---

pom.xml

**JIRA**: 
https://issues.redhat.com/browse/RHDM-1574
<details>
<summary>
</summary>
</details>

[7.48.x] [RHDM-1574] Consume Mvel version to 2.4.12+

---

.github/workflows/pull_request.yml
.github/workflows/upstream.yml
.mvn/extensions.xml

https://issues.redhat.com/browse/BXMSPROD-1228
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1601
https://github.com/kiegroup/kie-soup/pull/184
https://github.com/kiegroup/droolsjbpm-knowledge/pull/507
https://github.com/kiegroup/drools/pull/3417
https://github.com/kiegroup/optaplanner/pull/1195
https://github.com/kiegroup/lienzo-core/pull/143
https://github.com/kiegroup/lienzo-tests/pull/115
https://github.com/kiegroup/appformer/pull/1113
https://github.com/kiegroup/kie-uberfire-extensions/pull/113
https://github.com/kiegroup/jbpm/pull/1882
https://github.com/kiegroup/kie-jpmml-integration/pull/51
https://github.com/kiegroup/droolsjbpm-integration/pull/2411
https://github.com/kiegroup/kie-wb-playground/pull/105
https://github.com/kiegroup/kie-wb-common/pull/3584 …

BXMSPROD-1228 .mvn/extensions.xml takari backported

---

.github/workflows/pull_request.yml
.github/workflows/upstream.yml
.mvn/extensions.xml

https://issues.redhat.com/browse/BXMSPROD-1216
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1599
https://github.com/kiegroup/kie-soup/pull/183
https://github.com/kiegroup/droolsjbpm-knowledge/pull/506
https://github.com/kiegroup/drools/pull/3416
https://github.com/kiegroup/optaplanner/pull/1194
https://github.com/kiegroup/lienzo-core/pull/142
https://github.com/kiegroup/lienzo-tests/pull/114
https://github.com/kiegroup/appformer/pull/1112
https://github.com/kiegroup/kie-uberfire-extensions/pull/112
https://github.com/kiegroup/jbpm/pull/1881
https://github.com/kiegroup/optaplanner-wb/pull/389
https://github.com/kiegroup/kie-jpmml-integration/pull/50
https://github.com/kiegroup/droolsjbpm-integration/pull/2410
https://github.com/kiegroup/kie-wb-playground/pull/104 …

BXMSPROD-1216 .mvn/extensions.xml takari

---

kie-dmn-bom/pom.xml
pom.xml

**JIRA**: https://issues.redhat.com/browse/DROOLS-6047
* https://github.com/kiegroup/droolsjbpm-integration/pull/2408
<details>
<summary>
</summary>
</details>

DROOLS-6047 Next gen DMN kie-server endpoints

---

.github/workflows/generate_files.yml

https://issues.redhat.com/browse/BXMSPROD-1232
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1604
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1605

BXMSPROD-1232 generate_files.xml 7.48.x branch added

---

pom.xml

**JIRA**:
[KOGITO-4539](https://issues.redhat.com/browse/KOGITO-4539)
* https://github.com/kiegroup/kie-wb-common/pull/3580
<details>
<summary>
</summary>
</details>

KOGITO-4539: Upgrade kogito selenium tests libraries

---

pom.xml

**JIRA**: [KOGITO-4539](https://issues.redhat.com/browse/KOGITO-4539)
**cherry-pick of**:
* #1600 
<details>
<summary>
</summary>
</details>

[7.48.x] KOGITO-4539: Upgrade kogito selenium tests libraries

---

pom.xml

**JIRA**: [JBPM-9634](https://issues.redhat.com/browse/JBPM-9634)
* https://github.com/kiegroup/droolsjbpm-integration/pull/2413

[JBPM-9634] Upgrade testcontainers to 1.15.2

---

pom.xml

Jira :https://issues.redhat.com/browse/JBPM-9549

[JBPM-9549] Upgrade SpringBoot to 2.3.4 (#1565)

---

script/release/10c_optaplanner_upload_filemgmt.sh

<details>
<summary>
</summary>
</details>

fixed typo

---

kie-soup-bom/pom.xml

Adds Kafka data set version
Merge with:
https://github.com/kiegroup/kie-soup/pull/177
https://github.com/kiegroup/appformer/pull/1104
https://github.com/kiegroup/kie-wb-distributions/pull/1087

AF-2767: Kafka dataset provider

---

pom.xml

https://issues.redhat.com/browse/BXMSPROD-1235
<details>
<summary>
</summary>
</details>

BXMSPROD-1235: upgrade apache batik 1.14 and xml commons to 2.6

---

Jenkinsfile.buildchain

<details>
<summary>
</summary>
</details>

fix build chain sonar flow

---

Jenkinsfile.buildchain

<details>
<summary>
</summary>
</details>

Jenkinsfile.buildchain sonar folder

---

kie-dmn-bom/pom.xml
pom.xml

**JIRA**: [KOGITO-4233](https://issues.redhat.com/browse/KOGITO-4233): [DMN Designer] IntelliSense service
**Part of an ensemble**:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1611
- https://github.com/kiegroup/drools/pull/3435
- https://github.com/kiegroup/appformer/pull/1115
- https://github.com/kiegroup/kie-wb-common/pull/3590
- https://github.com/kiegroup/drools-wb/pull/1471
- https://github.com/kiegroup/kie-wb-distributions/pull/1091
**Artifacts**:
- **Business Central**: [WAR file](https://www.dropbox.com/s/fu3ra76qhptzprr/KOGITO-4233-bc.war?dl=0)
- **VS Code**: [plugin](https://www.dropbox.com/s/jaxmlnilmexk1zw/KOGITO-4233-plugin.vsix?dl=0)
<details>
<summary>
</summary>
* <b>a pull request</b> please add comment: …

KOGITO-4233: [DMN Designer] IntelliSense service

---

kie-bom/pom.xml

See https://issues.redhat.com/browse/KOGITO-3891
It **DEPENDS ON**:
- https://github.com/kiegroup/kie-wb-common/pull/3498
- https://github.com/kiegroup/drools-wb/pull/1445
- https://github.com/kiegroup/jbpm-wb/pull/1472
- https://github.com/kiegroup/kie-wb-distributions/pull/1071
Thanks!

KOGITO-3891: Stunner - Editors refactoring

---

uberfire-bom/pom.xml

**JIRA**: https://issues.redhat.com/browse/AF-2771
Adding DSL API version. Merge with
https://github.com/kiegroup/appformer/pull/1119

AF-2771: Dashbuilder Programmatic Layout API

---

drools-bom/pom.xml

- Introducing drools-legacy-test-util
**JIRA**: 
Review drools-mvel test leftovers : 1st round
* https://github.com/kiegroup/drools/pull/3482
<details>
<summary>
</summary>
</details>

[DROOLS-6174] Review drools-mvel test leftovers : 1st round

---

pom.xml

**JIRA**: https://issues.redhat.com/browse/DROOLS-6271
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1624
* https://github.com/kiegroup/drools/pull/3530
<details>
<summary>
</summary>
</details>

DROOLS-6271 Drools phreak rete diagram

---

pom.xml

**JIRA**: https://issues.redhat.com/browse/DROOLS-6311
**referenced Pull Requests**: part of an ensemble
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1634
* https://github.com/kiegroup/drools/pull/3576
<details>
<summary>
</summary>
</details>

DROOLS-6311 DMN update SmallRye OpenAPI to 2.0.26

---

kie-pmml-bom/pom.xml

See https://issues.redhat.com/browse/DROOLS-6308
Needed by https://github.com/kiegroup/drools/pull/3565

[DROOLS-6308] Define tree codegen dependencies

---

Jenkinsfile.buildchain

<details>
<summary>
</summary>
</details>

replaced findbugs and checkstyle calls in Jenkinsfile.buildchain

---

.github/workflows/pull_request.yml
.github/workflows/upstream.yml

https://issues.redhat.com/browse/BXMSPROD-1311
Related pull requests:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1641
* https://github.com/kiegroup/kie-soup/pull/202
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/519
* https://github.com/kiegroup/drools/pull/3599
* https://github.com/kiegroup/optaplanner/pull/1314
* https://github.com/kiegroup/lienzo-core/pull/144
* https://github.com/kiegroup/lienzo-tests/pull/116
* https://github.com/kiegroup/appformer/pull/1139
* https://github.com/kiegroup/kie-uberfire-extensions/pull/114
* https://github.com/kiegroup/jbpm/pull/1928
* https://github.com/kiegroup/kie-jpmml-integration/pull/53
* https://github.com/kiegroup/droolsjbpm-integration/pull/2476
* https://github.com/kiegroup/kie-wb-playground/pull/106
* …

BXMSPROD-1311 surefire report check to GA

---

kie-pmml-bom/pom.xml

**JIRA**: [DROOLS-6100](https://issues.redhat.com/browse/DROOLS-6100)
**Referenced Pull Request**: to be merged together with [drools PR](https://github.com/kiegroup/drools/pull/3527) and [droolsjbpm-integration PR](https://github.com/kiegroup/droolsjbpm-integration/pull/2468)

DROOLS-6100: Add clustering model to pom

---

.ci/project-dependencies.yaml
.ci/pull-request-config.yaml
Jenkinsfile.buildchain

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1333
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1647
* https://github.com/kiegroup/kie-wb-distributions/pull/1104
* https://gitlab.cee.redhat.com/business-automation/eng-jenkins/-/merge_requests/54
<details>
<summary>
</summary>
* <b>a full production downstream build</b> please add comment: <b>Jenkins …

[BXMSPROD-1333] kie-wb-distributions test failures fixed

---

.github/pull_request_template.md

related PR: https://github.com/kiegroup/kie-jenkins-scripts/pull/990

Update PR template with optional this keyword

---

pom.xml

https://app.snyk.io/vuln/SNYK-JAVA-ORGFREEMARKER-1076795
<details>
<summary>
</summary>
</details>

Updating freemarker to 2.3.30

---

pom.xml

**JIRA**: [JBPM-9761](https://issues.redhat.com/browse/JBPM-9761)

[JBPM-9761] PIM doesn't start with guava 30.0-jre

---

.github/workflows/pull_request.yml
.github/workflows/upstream.yml

https://issues.redhat.com/browse/BXMSPROD-1349
related PR:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1655
* https://github.com/kiegroup/kie-soup/pull/206
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/523
* https://github.com/kiegroup/drools/pull/3641
* https://github.com/kiegroup/optaplanner/pull/1343
* https://github.com/kiegroup/lienzo-core/pull/145
* https://github.com/kiegroup/lienzo-tests/pull/118
* https://github.com/kiegroup/appformer/pull/1145
* https://github.com/kiegroup/kie-uberfire-extensions/pull/115
* https://github.com/kiegroup/jbpm/pull/1940
* https://github.com/kiegroup/kie-jpmml-integration/pull/55
* https://github.com/kiegroup/droolsjbpm-integration/pull/2499
* https://github.com/kiegroup/kie-wb-playground/pull/107
* …

BXMSPROD-1349 point to ScaCap/action-surefire-report@v1.0.10

---

kie-pmml-bom/pom.xml

See https://issues.redhat.com/browse/DROOLS-6341
Needed by kiegroup/drools#3604

[DROOLS-6341] Define scorecard codegen dependencies

---

pom.xml

**JIRA**: [JBPM-9723](https://issues.redhat.com/browse/JBPM-9723)
* https://github.com/kiegroup/jbpm-work-items/pull/192

[JBPM-9723] Add integration tests for Kafka WIH async

---

pom.xml

**JIRA**: _RHPAM-3596_ 
<details>
<summary>
</summary>
</details>

[7.52.x] [RHPAM-3596] - Added a managed dependency for jsr305

---

.ci/compilation-config.yaml
.ci/downstream-production-config.yaml
.ci/full-downstream-config.yaml
.ci/product-projects-dependencies.yaml
.ci/project-dependencies.yaml
.ci/pull-request-config.yaml
.ci/upstream-config.yaml
.github/workflows/pull_request.yml
.github/workflows/upstream.yml

https://issues.redhat.com/browse/BXMSPROD-1363
please merge all of them at the same time
related PRs:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1670
- https://github.com/kiegroup/kie-soup/pull/208
- https://github.com/kiegroup/droolsjbpm-knowledge/pull/526
- https://github.com/kiegroup/drools/pull/3681
- https://github.com/kiegroup/optaplanner/pull/1383
- https://github.com/kiegroup/lienzo-core/pull/147
- https://github.com/kiegroup/lienzo-tests/pull/120
- https://github.com/kiegroup/appformer/pull/1153
- https://github.com/kiegroup/kie-uberfire-extensions/pull/118
- https://github.com/kiegroup/jbpm/pull/1954
- https://github.com/kiegroup/kie-jpmml-integration/pull/57
- https://github.com/kiegroup/droolsjbpm-integration/pull/2512
- …

BXMSPROD-1363 build-chain definition and project-dependencies upgraded to v2.1

---

.github/workflows/pull_request.yml
.github/workflows/upstream.yml

https://issues.redhat.com/browse/BXMSPROD-1361
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1672
- https://github.com/kiegroup/kie-soup/pull/210
- https://github.com/kiegroup/droolsjbpm-knowledge/pull/528
- https://github.com/kiegroup/drools/pull/3687
- https://github.com/kiegroup/optaplanner/pull/1388
- https://github.com/kiegroup/lienzo-core/pull/148
- https://github.com/kiegroup/lienzo-tests/pull/121
- https://github.com/kiegroup/appformer/pull/1154
- https://github.com/kiegroup/kie-uberfire-extensions/pull/119
- https://github.com/kiegroup/jbpm/pull/1956
- https://github.com/kiegroup/kie-jpmml-integration/pull/58
- https://github.com/kiegroup/droolsjbpm-integration/pull/2519
- https://github.com/kiegroup/kie-wb-playground/pull/111
- …

BXMSPROD-1361 decrease API rate limit probability

---

typescript

<details>
<summary>
</summary>
</details>

removed accidentally pushed file

---

Jenkinsfile.buildchain
Jenkinsfile.nightly
Jenkinsfile.revapi

**JIRA**: _BXMSPROD-1339_ 
* https://github.com/kiegroup/kie-jenkins-scripts/pull/1007
<details>
<summary>
</summary>
</details>

[BXMSPROD-1339] - Changed to the maven 3.8.1

---

.ci/pull-request-config.yaml

<details>
<summary>
</summary>
</details>

changed mvn command for kie-docs pullrequests

---

pom.xml

**JIRA**: https://issues.redhat.com/browse/DROOLS-6470
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1684
* https://github.com/kiegroup/drools/pull/3711
<details>
<summary>
</summary>
</details>

DROOLS-6470 Share Community Experimental xls2dmn converter (CLI version)

---

Jenkinsfile.buildchain

This reverts commit 2311c2c73b5929dda6166351d001b6f50566b90c.
* link 2
* link 3 etc.
<details>
<summary>
</summary>
* <b>a full production downstream build</b> please add …

Revert "Jenkinsfile.builchain pointing to 7.55.0.Final definition file (#1673)

---

.ci/jenkins/Jenkinsfile.nightly

Downgrade Maven to 3.6.3

---

.ci/project-dependencies.yaml

[BXMSPROD-1387](https://issues.redhat.com/browse/BXMSPROD-1387)
https://github.com/kiegroup/process-migration-service/pull/1
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1694
https://github.com/kiegroup/kie-jenkins-scripts/pull/1036
<details>
<summary>
</summary>
* <b>a full …

added new project kiegroup/process-migration-service

---

.ci/jenkins/Jenkinsfile.nightly
.ci/jenkins/Jenkinsfile.revapi
.ci/project-dependencies.yaml
.github/workflows/generate_files.yml
README.md
RELEASE-README.md
pom.xml
script/checks/oldbranches.pl
script/git-all.sh
script/git-checkout-all.sh
script/git-clone-others.sh
script/release/kie-upgrade-branch-auxiliary-reps.sh
script/release/update-version-all.sh
script/utils/revapi-clean.sh

**JIRA**: [BXMSPROD-1265](https://issues.redhat.com/browse/BXMSPROD-1265)
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1704
https://github.com/kiegroup/kie-jenkins-scripts/pull/1040
https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/160
https://github.com/kiegroup/kie-docs/pull/3806
https://gitlab.cee.redhat.com/middleware/build-configurations/-/merge_requests/503
<details>
<summary>
</summary>
* <b>a compile …

BXMSPROD-1265: Conscientious language initiative [master]

---

.ci/jenkins/Jenkinsfile.nightly

Add a parameter to specify the configuration branch to be used

---

pom.xml

@danielezonca @jiripetrlik
See https://issues.redhat.com/browse/DROOLS-6483
Needed by https://github.com/kiegroup/drools/pull/3740

[DROOLS-6483] Implement TextIndex

---

.ci/jenkins/Jenkinsfile.nightly

Rearrange timeout and retry for the nightly builds

---

script/release/curlsToProxies.sh

[BXMSPROD-1434](https://issues.redhat.com/browse/BXMSPROD-1434)
* https://github.com/kiegroup/kie-jenkins-scripts/pull/1058
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1722
<details>
<summary>
</summary>
* <b>a full production …

BXMSPROD-1434: New script for syncronizing the proxies

---

script/release/update-version-all.sh

https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1726
https://github.com/kiegroup/kie-jenkins-scripts/pull/1060
<details>
<summary>
</summary>
</details>

fixed script

---

pom.xml

* Upgrade Errai version to 4.14.2.Final
**JIRA**: 
[AF-2829](https://issues.redhat.com/browse/AF-2829)
* https://github.com/kiegroup/optaplanner-wb/pull/401
* https://github.com/kiegroup/kie-wb-playground/pull/117
* https://github.com/kiegroup/kie-soup/pull/219
* https://github.com/kiegroup/appformer/pull/1178
* https://github.com/kiegroup/kie-wb-common/pull/3665
* https://github.com/kiegroup/drools-wb/pull/1509
* https://github.com/kiegroup/jbpm-designer/pull/914
* https://github.com/kiegroup/jbpm-wb/pull/1509
* https://github.com/kiegroup/kie-wb-distributions/pull/1118
**Businnes Central Distribution**: [Download](https://drive.google.com/file/d/163uatfBlK6TkiuZbbjDpx18WJv1fh2pT/view?usp=sharing)
<details>
<summary>
How to retest this PR or trigger a …

[DO NOT MERGE] AF-2829 : Conscious language initiative (Design tools)

---

pom.xml

**JIRA**:  [BAPL-2054](https://issues.redhat.com/browse/BAPL-2054)
Update Kafka to version 2.8.0
PRs:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1714
- https://github.com/kiegroup/droolsjbpm-integration/pull/2568
- https://github.com/kiegroup/jbpm/pull/1996
<details>
<summary>
</summary>
* <b>an upstream build</b> please …

[BAPL-2054] Update Kafka to 2.8.0

---

pom.xml

**JIRA**: 
https://issues.redhat.com/browse/BXMSPROD-1267
**related PRs**:
* https://github.com/kiegroup/droolsjbpm-integration/pull/2558
<details>
<summary>
</summary>
</details>

BXMSPROD-1267: upgrade of kubernetes-client to 4.7.2

---

pom.xml

Add a specific property for jakarta-el dependency version

---

pom.xml

[DROOLS-6584](https://issues.redhat.com/browse/DROOLS-6584)
* https://github.com/kiegroup/drools/pull/3809
* https://github.com/kiegroup/kie-docs/pull/3860
<details>
<summary>
</summary>
* <b>a full production downstream build</b> please add …

[DROOLS-6584] Expose Drools metrics via Micrometer

---

.ci/project-dependencies.yaml
.ci/pull-request-config.yaml

@mareknovotny  has to be merged together with https://github.com/kiegroup/kie-jenkins-scripts/pull/1098
<details>
<summary>
</summary>
</details>

tried to eradicate PIM from fdb and cdb

---

.ci/jenkins/Jenkinsfile.nightly

**JIRA**: [BXMSPROD-1466](https://issues.redhat.com/browse/BXMSPROD-1466)
<details>
<summary>
</summary>
</details>

[BXMSPROD-1466] increased timeout value for nightlies

---

.ci/project-dependencies.yaml
.ci/pull-request-config.yaml

(cherry picked from commit c26b07db50f3a62a9562905224dd09611a0844fa)
@mareknovotny has to be merged together with https://github.com/kiegroup/kie-jenkins-scripts/pull/1099
<details>
<summary>
</summary>
</details>

removed PIM from fdb and cdb

---

.ci/jenkins/Jenkinsfile.nightly

Switch nightly build to JDK11

---

pom.xml

[RHPAM-3510](https://issues.redhat.com/browse/RHPAM-3510)
<details>
<summary>
</summary>
</details>

RHPAM-3510: micro upgrades

---

pom.xml

[RHPAM-3510](https://issues.redhat.com/browse/RHPAM-3510)
<details>
<summary>
</summary>
</details>

RHPAM-3510: upgrade minor versions

---

.github/workflows/pull_request.yml

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1475
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1770
* https://github.com/kiegroup/kie-soup/pull/228
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/549
* https://github.com/kiegroup/drools/pull/3835
* https://github.com/kiegroup/optaplanner/pull/1577
* https://github.com/kiegroup/lienzo-core/pull/152
* https://github.com/kiegroup/lienzo-tests/pull/126
* https://github.com/kiegroup/appformer/pull/1197
* https://github.com/kiegroup/kie-uberfire-extensions/pull/124
* https://github.com/kiegroup/jbpm/pull/2024
* https://github.com/kiegroup/kie-jpmml-integration/pull/65
* https://github.com/kiegroup/droolsjbpm-integration/pull/2607
* …

BXMSPROD-1475 maven version

---

pom.xml

(cherry picked from commit 14a8039a0509e6c09e91becc201db5bbbc80e7b6)
RHPAM-3510: hibernate upgrade
(cherry picked from commit f358e2a16044d4c617634a8e50a5373641644788)
RHPAM-3510: org.jboss* upgrades
(cherry picked from commit 81c3671b6e8ced545f9d33b83e22e6e40d1a5de6)
RHPAM-3510: org.jboss.weld upgrades
RHPAM-3510: upgrade of micro versions
(cherry picked from commit 1b23cfbb806d467ebcc2f1d5a2f72664eca549e6)
**JIRA**: [RHPAM-3510](https://issues.redhat.com/browse/RHPAM-3510)
<details>
<summary>
</summary>
* <b>a full downstream build</b> please …

[7.59.x] RHPAM-3510: micro upgrades (#1735)

---

narayana-integration-bom/pom.xml
pom.xml

**JIRA**: [RHPAM-3897](https://issues.redhat.com/browse/RHPAM-3897)
* https://github.com/kiegroup/jbpm/pull/2016
* https://github.com/kiegroup/drools/pull/3832
* https://github.com/kiegroup/droolsjbpm-integration/pull/2602
* https://github.com/kiegroup/jbpm-work-items/pull/215
* https://github.com/kiegroup/kie-jpmml-integration/pull/64
* https://github.com/kiegroup/optaplanner/pull/1574
* https://github.com/kiegroup/kie-soup/pull/227
* https://github.com/jboss-integration/rhba-installers/pull/92

RHPAM-3897: switch to jboss-transaction-spi-jakarta

---

narayana-integration-bom/pom.xml
pom.xml

**JIRA**: [RHPAM-3897](https://issues.redhat.com/browse/RHPAM-3897)
* https://github.com/kiegroup/jbpm/pull/2028
* https://github.com/kiegroup/drools/pull/3839
* https://github.com/kiegroup/droolsjbpm-integration/pull/2609
* https://github.com/kiegroup/jbpm-work-items/pull/218
* https://github.com/kiegroup/kie-jpmml-integration/pull/67
* https://github.com/kiegroup/optaplanner/pull/1580
* https://github.com/kiegroup/kie-soup/pull/230
* https://github.com/jboss-integration/rhba-installers/pull/93

[7.59.x] RHPAM-3897: switch to jboss-transaction-spi-jakarta

---

pom.xml

**JIRA**: 
https://issues.redhat.com/browse/AF-2884
- https://github.com/kiegroup/jbpm-wb/pull/1522
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1779
Backported from https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1777
<details>
<summary>
</summary>
* <b>a full production downstream build</b> please add comment: <b>Jenkins execute …

[7.59.x][AF-2884] upgrading opencmis version to 0.14.0

---

.ci/project-dependencies.yaml

https://issues.redhat.com/browse/DROOLS-6535
* https://github.com/kiegroup/kie-jenkins-scripts/pull/1087
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1738
* https://github.com/kiegroup/drools/pull/3807
<details>
<summary>
</summary>
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run …

[DROOLS-6535] Set up CI for Drools 8 - project-dependencies.yaml

---

kie-bom/pom.xml
kie-soup-bom/pom.xml
pom.xml

**JIRA**: 
[AF-2880](https://issues.redhat.com/browse/AF-2880)
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1776
* https://github.com/kiegroup/kie-soup/pull/231
* https://github.com/kiegroup/appformer/pull/1199
* https://github.com/kiegroup/droolsjbpm-integration/pull/2611
* https://github.com/kiegroup/jbpm-wb/pull/1518
* https://github.com/kiegroup/kie-wb-distributions/pull/1132
<details>
<summary>
</summary>
* <b>a full …

[7.59.x] AF-2880 : Support Elytron in Business Central 

---

pom.xml

**JIRA**: https://issues.redhat.com/browse/DROOLS-6622
* https://github.com/kiegroup/drools/pull/3853
<details>
<summary>
</summary>
</details>

[DROOLS-6622] Bump Mvel version to 2.4.13

---

.ci/jenkins/Jenkinsfile.buildchain

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1785
* https://github.com/kiegroup/kie-jenkins-scripts/pull/1126
<details>
<summary>
</summary>
</details>

Jenkinsfile.buildchain configurable build-chain group and branch

---

.ci/jenkins/Jenkinsfile.nightly

<details>
<summary>
</summary>
</details>

[prod nightly] cleanWs post action improved

---

script/release/05a_communityDeployLocally.sh
script/release/05b_prodInstall.sh
script/release/05c_dailyBuildDeployLocally.sh
script/release/05d_dailyBuildProdInstall.sh

<details>
<summary>
</summary>
</details>

added missing profiles to mvn commands

---

.ci/jenkins/Jenkinsfile.nightly

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1505
- https://github.com/kiegroup/kie-jenkins-scripts/pull/1128
<details>
<summary>
</summary> …

[BXMSPROD-1505][7.59.x] Jenkinsfile.nightly call RHPAM properties file

---

.ci/jenkins/Jenkinsfile.nightly

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1505
- https://github.com/kiegroup/kie-jenkins-scripts/pull/1128
<details>
<summary>
</summary> …

[BXMSPROD-1505] Jenkinsfile.nightly call RHPAM properties file

---

.ci/jenkins/Jenkinsfile.buildchain
.github/pull_request_template.md
.github/workflows/pull_request.yml
.github/workflows/upstream.yml
script/repository-list.txt

See build-chain update details at https://github.com/kiegroup/github-action-build-chain/pull/190
blocked by:
- https://github.com/kiegroup/kie-jenkins-scripts/pull/1150
- https://gitlab.cee.redhat.com/business-automation/eng-jenkins/-/merge_requests/123
related PRs:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1798
- https://github.com/kiegroup/kie-soup/pull/235
- https://github.com/kiegroup/droolsjbpm-knowledge/pull/576
- https://github.com/kiegroup/drools/pull/3959
- https://github.com/kiegroup/optaplanner/pull/1640
- https://github.com/kiegroup/lienzo-core/pull/156
- https://github.com/kiegroup/lienzo-tests/pull/130
- https://github.com/kiegroup/appformer/pull/1208
- https://github.com/kiegroup/kie-uberfire-extensions/pull/127
- …

[ISSUE 117] build-chain upgraded to v2.6.13

---

.ci/actions/build-chain/action.yml
.github/workflows/pull_request.yml

includes
- https://github.com/kiegroup/github-action-build-chain/pull/196
- https://github.com/kiegroup/github-action-build-chain/pull/195
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github …

build-chain to 2.3.23

---

.github/workflows/pull_request.yml

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

build-chain composite pointing to kiegroup/main

---

script/release/11_removeOptaWebRepos.sh

@mareknovotny this script removes for all pipelines (daily build, community or prod tag) 
- optaweb-vehicle-routing 7.x
- opaweb-employee-rostering 7.x
from repository-list.txt and branched-7-repository-list.txt.
The scripts that clone all reps and upgrade the versions work fine (tested).
The changes to this list are done in the job, so the repository lists on GitHub keep the same!
[RHDM-1840](https://issues.redhat.com/browse/RHDM-1840)
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method …

RHDM-1840: fixed optaweb* removal script

---

.ci/jenkins/Jenkinsfile.buildchain

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1808
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1809
* https://github.com/kiegroup/kie-jenkins-scripts/pull/1156
* https://github.com/kiegroup/kogito-pipelines/pull/314
* https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/168
you can check job execution result at https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/pullrequest/job/lienzo-core-main.pr/21/console
<details>
<summary> …

Jenkinsfile.buildchain install build-chain tool at runtime

---

.ci/jenkins/Jenkinsfile.buildchain

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1808
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1809
* https://github.com/kiegroup/kie-jenkins-scripts/pull/1156
<details>
<summary>
</summary> …

[7.59.x] Jenkinsfile.buildchain install build-chain tool at runtime

---

.ci/actions/build-chain/action.yml
.ci/actions/cache-maven/action.yml
.ci/actions/disk-space/action.yml
.ci/actions/java/action.yml
.ci/actions/long-paths/action.yml
.ci/actions/surefire-report/action.yml

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

[7.59.x] composite actions

---

pom.xml

**JIRA**: https://issues.redhat.com/browse/DROOLS-6693

[DROOLS-6693] upgrade to JavaParser 3.23.1

---

.github/workflows/branch-compilation.yml

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

branch compilation workflow

---

.ci/actions/build-chain/action.yml
.github/workflows/branch-compilation.yml

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

Compilation workflow updated

---

.ci/actions/build-chain/action.yml

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

build chain updated to v2.6.19

---

.ci/jenkins/Jenkinsfile.nightly_rhos-01

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1832
* https://github.com/kiegroup/kie-jenkins-scripts/pull/1171
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure …

Temporary Run nightly build on RHOS-01 cloud

---

pom.xml

7.x of https://github.com/kiegroup/drools/pull/4034
<details>
<summary>
</summary> …

KOGITO-6285 bump antlr4 version

---

.ci/actions/build-chain/action.yml

* https://github.com/kiegroup/github-action-build-chain/pull/206
<details>
<summary>
</summary>
[build-chain …

build chain updated to v2.6.20

---

.ci/jenkins/Jenkinsfile.nightly_rhos-01

* https://github.com/kiegroup/kie-jenkins-scripts/pull/1174
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1837
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1838
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use …

[7.59.x] RHBA nightly job moved to rhos-01

---

.ci/README.md

<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can …

Fix minor typos in the CI readme

---

pom.xml

[https://issues.redhat.com/browse/JBPM-9958](JBPM-9958)
* https://github.com/kiegroup/appformer/pull/1216
* https://github.com/kiegroup/kie-wb-common/pull/3710
<details>
<summary>
</summary> …

JBPM-9958 Jsoup library upgrade

---

.ci/jenkins/Jenkinsfile.buildchain

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

Jenkinsfile.buildchain @kie/build-chain-action installation step improved

---

pom.xml

https://issues.redhat.com/browse/BXMSPROD-1558
https://github.com/kiegroup/appformer/pull/1217
https://github.com/kiegroup/kie-wb-common/pull/3709
https://github.com/kiegroup/kogito-apps/pull/1141
https://github.com/kiegroup/kogito-editors-java/pull/184
https://github.com/kiegroup/optaweb-employee-rostering/pull/730
https://github.com/kiegroup/optaweb-vehicle-routing/pull/614
https://github.com/kiegroup/process-migration-service/pull/37
https://github.com/kiegroup/lock-treatment-tool/pull/2
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1840

BXMSPROD-1558 install lock-treatment-tool exec

---

pom.xml

**JIRA**: 
https://issues.redhat.com/browse/DROOLS-6741
<details>
<summary>
</summary> …

[DROOLS-6741] Upgrade to mvel 2.4.14+

---

pom.xml

issue: https://issues.redhat.com/browse/RHPAM-4012
related to https://github.com/kiegroup/droolsjbpm-integration/pull/2671

[RHPAM-4012] upgrade apache-cxf to version 3.4.5

---

pom.xml

Handle logback-core upgrade to 1.2.8
Handle log4j dependency management for transitive dependencies
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to …

Upgraded logback and dependency mgmt of log4j

---

pom.xml

**JIRA**: 
* As a part of https://issues.redhat.com/browse/RHDM-1861
* Backport https://issues.redhat.com/browse/DROOLS-6741 to 7.59.x
* https://github.com/kiegroup/drools/pull/4118
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) …

[7.59.x] [DROOLS-6741] Upgrade to mvel 2.4.14+ (#1854)

---

pom.xml

https://issues.redhat.com/browse/RHPAM-4111
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1872
- https://github.com/kiegroup/droolsjbpm-integration/pull/2693
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/641
- https://github.com/kiegroup/optaweb-employee-rostering/pull/755
Closes #1860.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of …

[RHPAM-4111]-Certify Spring Boot 2.4.x

---

pom.xml

**JIRA**: https://issues.redhat.com/browse/DROOLS-6794

[DROOLS-6794] upgrade netty version to 4.1.73

---

pom.xml

https://issues.redhat.com/browse/RHPAM-4098
Upgrade of SpringFramework to 5.2.19.RELEASE
* link 2
* link 3 etc.
<details>
<summary>
</summary>
[build-chain …

[7.59.x] springframework upgraded to 5.2.19.RELEASE

---

script/release/05a_communityDeployLocally.sh

<details>
<summary>
</summary>
* for a <b>full downstream build</b> 
* for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
* for <b>github actions</b> job: add the label `run_fdb`
</details>

added testing to community release  mvn command

---

.ci/jenkins/Jenkinsfile.nightly

It is aborted due to timeout. See https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/custom/job/emingora/job/nightly-retry/3/
```
stages {
stage('Build Nightly projects') {
steps {
script {
timeout(time: 10, unit: 'SECONDS') {
retry(3) {
println "WAITING..."
sleep(time:5,unit:"SECONDS")
println "DONE"
throw new RuntimeException("shilly exception")
}
}
}
}
}
}
```
it fails after 3 tries
```
stages {
stage('Build Nightly projects') {
steps {
script {
retry(3) {
timeout(time: 10, unit: 'SECONDS') {
println "WAITING..."
sleep(time:5,unit:"SECONDS")
println "DONE"
throw new RuntimeException("shilly exception")
}
}
}
}
}
}
```

timeout step inside the retry step

---

pom.xml

**JIRA**: https://issues.redhat.com/browse/RHPAM-3461
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1885
* https://github.com/kiegroup/drools/pull/4180
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the …

RHPAM-3461 netty excluded from errai-bus

---

pom.xml

**JIRA**: https://issues.redhat.com/browse/RHPAM-3461
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1885
<details>
<summary>
</summary>
[build-chain …

[7.59.x] RHPAM-3461 netty excluded from errai-bus (#1885)

---

pom.xml

**[JBPM-10012](https://issues.redhat.com/browse/JBPM-10012)**: Right Springboot version should be 2.3.10
* https://github.com/kiegroup/droolsjbpm-integration/pull/2711
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool …

[7.59.x][JBPM-10012] - Right Springboot version should be 2.3.10

---

script/release/05a_communityDeployLocally.sh

https://github.com/kiegroup/kie-jenkins-scripts/pull/1209
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1892
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure …

SAVE DISK SPACE: added execution of clean-up script into mvn command

---

.ci/create-push-tags.yaml
.ci/jenkins/Jenkinsfile.release
.ci/release-config.yaml
.ci/update-versions-release.yaml

New needed scripts/files for the community release pipeline applying the build-chain methodology
The removal of obsolete scripts will happen this works properly.
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1893
https://github.com/kiegroup/kie-jenkins-scripts/pull/1213
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use …

new buildchain community pipeline

---

.ci/create-push-tags.yaml
.ci/release-config.yaml

- optaweb-employee-rostering and optaweb-vehicle-routing have to be skipped for release
This works when updating the versions (https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/main/script/release/update-versions-build-chain.sh) but was forget to do for building and commiting
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use …

skip optaweb* repositories

---

.ci/daily-config.yaml
.ci/jenkins/Jenkinsfile.daily

in all daily-build PIM will be skipped first but after the build of all other repositories it will be built with jdk11. So it will be also built with jdk11 when the java-tool is defined jdk8.
The jdk11-db-main and jdk11-prod-main are built both with jdk11and PIM is needed here. OK
The jdk8-db-main is built with jdk8 but PIM will be built with jdk11.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to …

forced PIM to build with jdk11

---

pom.xml

https://issues.redhat.com/browse/RHPAM-4031
Upgrade of mysql connector to 8.0.27
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple …

Upgrade of mysql client to 8.0.27

---

pom.xml

Jira: https://issues.redhat.com/browse/RHPAM-3794
<details>
<summary>
</summary> …

[RHPAM-3794] upgrade wildfly elytron to version 1.15.5.Final

---

pom.xml

backport of https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1858 
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple …

Upgraded logback and dependency mgmt of log4j (#1858)

---

.ci/create-push-tags.yaml
.ci/jenkins/Jenkinsfile.release
.ci/release-config.yaml
script/release/update-versions-build-chain.sh

<details>
<summary>
</summary> …

fixes for community build chain pipeline

---

pom.xml

**JIRA**: [RHPAM-4166](https://issues.redhat.com/browse/RHPAM-4166)
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is …

[RHPAM-4166] Update protobuf to 3.19.4

---

pom.xml
script/utils/revapi-clean.sh

**JIRA:** [BAQE-2254](https://issues.redhat.com/browse/BAQE-2254)
PR set:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1923
* https://github.com/kiegroup/appformer/pull/1250
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/597
* https://github.com/kiegroup/drools/pull/4273
* https://github.com/kiegroup/jbpm/pull/2129
* https://github.com/kiegroup/droolsjbpm-integration/pull/2752
* https://github.com/kiegroup/optaplanner/pull/1888
<details>
<summary>
</summary> …

BAQE-2254 - Change revapi to check against 7.67.0.Final

---

pom.xml

(cherry picked from commit c0aa44924011bc0c82b8d9f6f98d1ea01a9d8f36)
[DROOLS-6879](https://issues.redhat.com/browse/DROOLS-6879)
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1924
* https://github.com/kiegroup/appformer/pull/1252
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle …

[7.67.x] DROOLS-6879 : Update to Wildfly core 17.x

---

pom.xml

**JIRA**: [BAQE-2253](https://issues.redhat.com/browse/BAQE-2253)
PR set:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1925
* https://github.com/kiegroup/appformer/pull/1254
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/598
* https://github.com/kiegroup/drools/pull/4282
* https://github.com/kiegroup/jbpm/pull/2132
* https://github.com/kiegroup/droolsjbpm-integration/pull/2754
* https://github.com/kiegroup/optaplanner/pull/1894
<details>
<summary>
</summary> …

[7.67.x] BAQE-2253 - Change revapi to check against 7.59.0.Final

---

.ci/jenkins/Jenkinsfile.nightly

https://issues.redhat.com/browse/BXMSPROD-1670
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1926
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1927
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1928
* https://github.com/kiegroup/kogito-pipelines/pull/409
* https://github.com/kiegroup/kogito-pipelines/pull/410
* https://github.com/kiegroup/kogito-pipelines/pull/411

BXMSPROD-1670 upload files to repository --fail

---

.ci/jenkins/Jenkinsfile.nightly

https://issues.redhat.com/browse/BXMSPROD-1670
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1926
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1927
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1928
* https://github.com/kiegroup/kogito-pipelines/pull/409
* https://github.com/kiegroup/kogito-pipelines/pull/410
* https://github.com/kiegroup/kogito-pipelines/pull/411

[7.67.x] BXMSPROD-1670 upload files to repository --fail

---

.ci/jenkins/Jenkinsfile.nightly

https://issues.redhat.com/browse/BXMSPROD-1670
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1926
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1927
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1928
* https://github.com/kiegroup/kogito-pipelines/pull/409
* https://github.com/kiegroup/kogito-pipelines/pull/410
* https://github.com/kiegroup/kogito-pipelines/pull/411

[7.59.x] BXMSPROD-1670 upload files to repository --fail

---

.ci/actions/build-chain/action.yml

Solves https://github.com/kiegroup/github-action-build-chain/issues/221
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/412
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1930
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that …

build-chain composite action upgraded to v2.6.22

---

pom.xml

**JIRA**: https://issues.redhat.com/browse/DROOLS-6853
Related PRs:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1912
https://github.com/kiegroup/drools/pull/4261
https://github.com/kiegroup/jbpm/pull/2122
https://github.com/kiegroup/droolsjbpm-integration/pull/2736
https://github.com/kiegroup/drools-wb/pull/1541
https://github.com/kiegroup/jbpm-designer/pull/929
https://github.com/kiegroup/jbpm-wb/pull/1546
https://github.com/kiegroup/kie-wb-distributions/pull/1158

[DROOLS-6853] jdk17 compatibility

---

pom.xml

[DROOLS-6859](https://issues.redhat.com/browse/DROOLS-6859)
* https://github.com/kiegroup/kie-wb-distributions/pull/1156
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1908
<details>
<summary>
</summary> …

 [DROOLS-6859] Update bootable jar 

---

pom.xml

**JIRA**: 
[https://issues.redhat.com/browse/DROOLS-6859](https://issues.redhat.com/browse/DROOLS-6859)
backport
* [kiegroup/kie-wb-distribution/pull/1159](https://github.com/kiegroup/kie-wb-distributions/pull/1159)
<details>
<summary>
</summary> …

[Drools-6859] backport of XP bootable jar upgrade

---

pom.xml

https://issues.redhat.com/browse/BXMSPROD-1673
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1935
* https://github.com/kiegroup/optaplanner/pull/1910
* https://github.com/kiegroup/droolsjbpm-integration/pull/2759
* https://github.com/kiegroup/openshift-drools-hacep/pull/129
* https://github.com/kiegroup/optaweb-employee-rostering/pull/785
* https://github.com/kiegroup/optaweb-vehicle-routing/pull/675
* https://github.com/kiegroup/optaplanner/pull/1909
* https://github.com/kiegroup/optaplanner-quickstarts/pull/317
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), …

BXMSPROD-1673 spring-webmvc/spring-framework 5.3.18. spring-boot to 2.6.6

---

.ci/jenkins/Jenkinsfile.release
script/release/10a_drools_upload_filemgmt.sh
script/release/10b_jbpm_upload_filemgmt.sh
script/release/10c_optaplanner_upload_filemgmt.sh

since filemgmt.jboss.org doesn't work anymore we have to use now
- for sftp: filemgmt-prod.jboss.org
- for rsync: filemgmt-prod-sync.jboss.org [with port 2222]
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends …

changes related to filemgmt-prod.jboss.org

---

pom.xml

https://issues.redhat.com/browse/BXMSPROD-1673
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1939
* https://github.com/kiegroup/optaplanner/pull/1920
* https://github.com/kiegroup/droolsjbpm-integration/pull/2764
* https://github.com/kiegroup/openshift-drools-hacep/pull/128
* https://github.com/kiegroup/optaweb-employee-rostering/pull/786
* https://github.com/kiegroup/optaweb-vehicle-routing/pull/676
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just …

[7.59.x] BXMSPROD-1673 spring-webmvc/spring-framework 5.3.18. spring-boot to 2.6.6

---

pom.xml

https://issues.redhat.com/browse/RHPAM-4257
<details>
<summary>
</summary> …

RHPAM-4257 jackson-databind version upgraded to RHPAM-4257

---

pom.xml

Reverts kiegroup/droolsjbpm-build-bootstrap#1940

Revert "RHPAM-4257 jackson-databind version upgraded to 2.12.6.1"

---

pom.xml

https://issues.redhat.com/browse/RHPAM-4172
<details>
<summary>
</summary>
[build-chain …

[RHPAM-4172] mysql-connector-java to 8.0.28

---

pom.xml

https://issues.redhat.com/browse/RHPAM-4257
<details>
<summary>
</summary> …

RHPAM-4257 jackson version upgraded to 2.12.6

---

pom.xml

https://issues.redhat.com/browse/RHPAM-4257
<details>
<summary>
</summary> …

[7.67.x] RHPAM-4257 jackson version upgraded to RHPAM-4257

---

.ci/actions/build-chain/action.yml

build-chain change https://github.com/kiegroup/github-action-build-chain/pull/229, just a minor thing at print local execution command
<details>
<summary>
</summary> …

build-chain to 2.6.24

---

pom.xml

https://issues.redhat.com/browse/RHPAM-4368
<details>
<summary>
</summary> …

RHPAM-4368 netty-codec-http to 4.1.77.Final

---

pom.xml

Jira: https://issues.redhat.com/browse/RHPAM-4370
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1960
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1974
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1976
<details>
<summary>
</summary> …

[7.67.x][RHPAM-4370] update gson to 2.8.9

---

pom.xml

Jira: https://issues.redhat.com/browse/RHPAM-4370
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1960
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1974
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1976
<details>
<summary>
</summary> …

[7.67.x-blue][RHPAM-4370] update gson to 2.8.9

---

pom.xml

https://issues.redhat.com/browse/RHPAM-4342
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent …

[RHPAM-4342] update commons-fileupload to 1.4

---

.ci/jenkins/Jenkinsfile.release
script/release/12_splitOrgKie.sh

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

new CREDS and URL for dev Nexus

---

pom.xml

**JIRA**: https://issues.redhat.com/browse/RHPAM-4342
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1977
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1989
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1990
<details>
<summary>
</summary> …

[7.67.x][RHPAM-4342] update commons-fileupload to 1.4

---

pom.xml

**JIRA**: https://issues.redhat.com/browse/RHPAM-4342
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1977
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1989
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1990
<details>
<summary>
</summary> …

[7.67.x-blue][RHPAM-4342] update commons-fileupload to 1.4

---

pom.xml

**[JBPM-10093](https://issues.redhat.com/browse/JBPM-10093)**
* https://github.com/kiegroup/jbpm-work-items/pull/234
<details>
<summary>
</summary> …

[JBPM-10093] - Adapt testcontainers to support and use a particular Kafka version

---

pom.xml

Co-authored-by: Enrique Mingorance <ginxo@hotmail.com>
**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4368
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1971
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2006
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2007
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and …

[7.67.x] RHPAM-4368 netty-codec-http to 4.1.77.Final (#1971)

---

pom.xml

**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4449
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2008
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2010
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2009
* https://github.com/kiegroup/optaplanner/pull/2089
* https://github.com/kiegroup/optaplanner/pull/2090
* https://github.com/kiegroup/optaplanner/pull/2091
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each …

[RHPAM-4449] spring-boot downgraded to 2.5.12

---

pom.xml

**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4449
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2008
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2010
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2009
* https://github.com/kiegroup/optaplanner/pull/2089
* https://github.com/kiegroup/optaplanner/pull/2090
* https://github.com/kiegroup/optaplanner/pull/2091
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each …

[7.67.x][RHPAM-4449] spring-boot downgraded to 2.5.12

---

pom.xml

**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4387
**Referenced Pull Requests**:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1987
* https://github.com/kiegroup/kie-wb-common/pull/3742
* https://github.com/kiegroup/drools-wb/pull/1543
* https://github.com/kiegroup/jbpm-wb/pull/1550
* https://github.com/kiegroup/kie-wb-distributions/pull/1169
* https://github.com/kiegroup/lienzo-tests/pull/136
**Business Central**: [WAR file](https://donwnload.here/something)
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could …

RHPAM-4387 xercesImpl to 2.12.2

---

pom.xml

**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4387
**Referenced Pull Requests**:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2012
* https://github.com/kiegroup/kie-wb-common/pull/3745
* https://github.com/kiegroup/drools-wb/pull/1545
* https://github.com/kiegroup/jbpm-wb/pull/1553
* https://github.com/kiegroup/kie-wb-distributions/pull/1172
* https://github.com/kiegroup/lienzo-tests/pull/138
<details>
<summary>
</summary> …

[BLUE] RHPAM-4387 xml-apis:xml-apis excluded

---

pom.xml

**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4387
**Referenced Pull Requests**:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2011
* https://github.com/kiegroup/kie-wb-common/pull/3744
* https://github.com/kiegroup/drools-wb/pull/1544
* https://github.com/kiegroup/jbpm-wb/pull/1552
* https://github.com/kiegroup/kie-wb-distributions/pull/1171
* https://github.com/kiegroup/lienzo-tests/pull/137
<details>
<summary>
</summary> …

[7.67.x] RHPAM-4387 xercesImpl to 2.12.2 (#1987)

---

pom.xml

Jira: https://issues.redhat.com/browse/JBPM-10101

[JBPM-10101] kafka-clients misalignment with any supported AMQ Streams version

---

pom.xml

Reverts kiegroup/droolsjbpm-build-bootstrap#2013

Revert "[JBPM-10101] kafka-clients misalignment with any supported AMQ Streams version"

---

pom.xml

backport of https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1997
<details>
<summary>
</summary>
[build-chain …

[7.67.x-blue] undertow upgrade to 2.2.15

---

pom.xml

**JIRA**: https://issues.redhat.com/browse/RHPAM-4172
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1931
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2021
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2022
<details>
<summary>
</summary> …

[7.67.x][RHPAM-4172] mysql-connector-java to 8.0.28 (#1931)

---

pom.xml

**JIRA**: https://issues.redhat.com/browse/RHPAM-4172
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1931
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2021
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2022
<details>
<summary>
</summary> …

[BLUE][RHPAM-4172] mysql-connector-java to 8.0.28 (#1931)

---

pom.xml

backport of https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1988
<details>
<summary>
</summary>
[build-chain …

[7.67.x] Bump jython from 2.5.3 to 2.7.2 (#1988)

---

pom.xml

the `org.w3c.dom.ElementTraversal` class is not present for jdk8, so we force org.w3c:dom dependency to be present.
As soon as we agree this is the right proposal, I will propagate it to `7.67.x` and `7.67.x-blue` branches
Built and tested either with JDK11 and 8.
**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4455
* https://github.com/kiegroup/kie-wb-distributions/pull/1173
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2023
* https://github.com/kiegroup/kie-wb-common/pull/3755
* https://github.com/kiegroup/droolsjbpm-integration/pull/2835
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and …

RHPAM-4455 org.w3c.dom.* ignored from ban-duplicated-classes

---

pom.xml

Jira: https://issues.redhat.com/browse/JBPM-10101

[7.67.x] [JBPM-10101] kafka-clients misalignment with any supported AMQ Streams version

---

pom.xml

Jira: https://issues.redhat.com/browse/JBPM-10101

[7.67.x-blue] [JBPM-10101] kafka-clients misalignment with any supported AMQ Streams version

---

.ci/project-dependencies.yaml

**JIRA**:  https://issues.redhat.com/browse/BXMSPROD-1763
Related to:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2050
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2053
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2054
<details>
<summary>
</summary> …

[7.67.x-blue][BXMSPROD-1763] jbpm-designer removed from project-dependencies

---

.ci/project-dependencies.yaml

**JIRA**:  https://issues.redhat.com/browse/BXMSPROD-1763
Related to:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2050
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2053
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2054
<details>
<summary>
</summary> …

[7.67.x][BXMSPROD-1763] jbpm-designer removed from project-dependencies

---

jbpm-bom/pom.xml

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2060
* https://github.com/kiegroup/jbpm-wb/pull/1563
Cherry picked from:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2058
* https://github.com/kiegroup/jbpm-wb/pull/1562
<details>
<summary>
</summary> …

jbpm-designer dependecie management removal

---

jbpm-bom/pom.xml

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2061
* https://github.com/kiegroup/jbpm-wb/pull/1564
Cherry picked from:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2058
* https://github.com/kiegroup/jbpm-wb/pull/1562
<details>
<summary>
</summary> …

[7.67.x-blue] jbpm-designer dependecie management removal (#2058)

---

pom.xml

Bumps jython from 2.5.3 to 2.7.2.
---
updated-dependencies:
- dependency-name: org.python:jython
dependency-type: direct:production
...
Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does …

[7.67.x-blue] Bump jython from 2.5.3 to 2.7.2 (#1988)

---

.ci/jenkins/Jenkinsfile.buildchain

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

upgraded nodejs version

---

pom.xml

**JIRA**: https://issues.redhat.com/browse/RHPAM-4535
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2095
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2093
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2094
<details>
<summary>
</summary> …

[7.67.x-blue][RHPAM-4535] CVE-2018-1000134 unboundid-ldapsdk upgraded to 4.0.

---

pom.xml

**JIRA**: https://issues.redhat.com/browse/RHPAM-4535
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2095
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2093
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2094
<details>
<summary>
</summary> …

[7.67.x][RHPAM-4535] CVE-2018-1000134 unboundid-ldapsdk upgraded to 4.0.

---

pom.xml

**JIRA**: https://issues.redhat.com/browse/RHPAM-4535
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2095
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2093
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2094
<details>
<summary>
</summary> …

[RHPAM-4535] CVE-2018-1000134 unboundid-ldapsdk upgraded to 4.0.5

---

pom.xml

**JIRA**: https://issues.redhat.com/browse/RHPAM-4525
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2081
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2082
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2083
* https://github.com/kiegroup/kie-soup/pull/255
* https://github.com/kiegroup/kie-soup/pull/256
* https://github.com/kiegroup/kie-soup/pull/257
* https://github.com/kiegroup/appformer/pull/1311
* https://github.com/kiegroup/appformer/pull/1309
* https://github.com/kiegroup/appformer/pull/1310
<details>
<summary>
How to …

RHPAM-4525 lucene updraded to 6.6.6

---

pom.xml

**JIRA**: https://issues.redhat.com/browse/RHPAM-4525
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2081
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2082
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2083
* https://github.com/kiegroup/kie-soup/pull/255
* https://github.com/kiegroup/kie-soup/pull/256
* https://github.com/kiegroup/kie-soup/pull/257
* https://github.com/kiegroup/appformer/pull/1311
* https://github.com/kiegroup/appformer/pull/1309
* https://github.com/kiegroup/appformer/pull/1310
<details>
<summary>
How to …

[7.67.x] RHPAM-4525 lucene updraded to 6.6.6

---

pom.xml

**JIRA**: https://issues.redhat.com/browse/RHPAM-4525
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2081
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2082
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2083
* https://github.com/kiegroup/kie-soup/pull/255
* https://github.com/kiegroup/kie-soup/pull/256
* https://github.com/kiegroup/kie-soup/pull/257
* https://github.com/kiegroup/appformer/pull/1311
* https://github.com/kiegroup/appformer/pull/1309
* https://github.com/kiegroup/appformer/pull/1310
<details>
<summary>
How to …

[7.67.x-blue] RHPAM-4525 lucene updraded to 6.6.6

---

pom.xml

related to:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2098
* https://github.com/kiegroup/appformer/pull/1313

Bump jsoup from 1.14.2 to 1.15.3

---

pom.xml

**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4536
cherry pick of https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2074
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure …

[7.67.x] [RHPAM-4536] backport of Snakeyaml upgrade to 1.31

---

kie-bom/pom.xml
kie-user-bom-parent/pom.xml
pom.xml

**JIRA**:
- https://issues.redhat.com/browse/BXMSPROD-1798
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2051
- https://github.com/kiegroup/appformer/pull/1301
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2064
- https://github.com/kiegroup/appformer/pull/1302
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2065
- https://github.com/kiegroup/appformer/pull/1303
Added new property `version.org.kie.lienzo` for lienzo dependencies.
<details>
<summary>
</summary>
Build Chain tool does …

[BXMSPROD-1798] Own property for lienzo version

---

kie-bom/pom.xml
kie-user-bom-parent/pom.xml
pom.xml

**JIRA**: 
- https://issues.redhat.com/browse/BXMSPROD-1798
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2051
- https://github.com/kiegroup/appformer/pull/1301
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2064
- https://github.com/kiegroup/appformer/pull/1302
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2065
- https://github.com/kiegroup/appformer/pull/1303
Backport for newer Lienzo version property.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the …

[7.67.x] [BXMSPROD-1798] Added new lienzo version property

---

.ci/jenkins/Jenkinsfile.buildchain
.ci/jenkins/Jenkinsfile.nightly

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

[main] changed label master to built-in

---

pom.xml

**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4536
cherry pick of https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2074
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure …

[7.67.x-blue] [RHPAM-4536] backport of Snakeyaml upgrade to 1.31

---

pom.xml

related to:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2098
* https://github.com/kiegroup/appformer/pull/1313
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2099
* https://github.com/kiegroup/appformer/pull/1314
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2100
* https://github.com/kiegroup/appformer/pull/1315

[7.67.x-blue] Bump jsoup from 1.14.2 to 1.15.3

---

pom.xml

https://issues.redhat.com/browse/BXMSPROD-1700
Related PRs:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2110
* https://github.com/kiegroup/appformer/pull/1320
* https://github.com/kiegroup/process-migration-service/pull/80
* https://github.com/kiegroup/kie-wb-common/pull/3785

[7.67.x] [BXMSPROD-1700] lock-treatment-tool version propert

---

pom.xml

https://issues.redhat.com/browse/BXMSPROD-1700
Related PRs:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2109
* https://github.com/kiegroup/appformer/pull/1321
* https://github.com/kiegroup/process-migration-service/pull/81
* https://github.com/kiegroup/kie-wb-common/pull/3786

[7.67.x-blue] [BXMSPROD-1700] lock-treatment-tool version property

---

pom.xml

https://issues.redhat.com/browse/BXMSPROD-1700
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2111
- https://github.com/kiegroup/appformer/pull/1322
- https://github.com/kiegroup/kie-wb-common/pull/3787
- https://github.com/kiegroup/process-migration-service/pull/84
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/781
- https://github.com/kiegroup/optaweb-employee-rostering/pull/860

[BXMSPROD-1700] lock-treatment-tool version property

---

kie-bom/pom.xml
kie-user-bom-parent/pom.xml
pom.xml

**JIRA**: 
- https://issues.redhat.com/browse/BXMSPROD-1798
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2051
- https://github.com/kiegroup/appformer/pull/1301
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2064
- https://github.com/kiegroup/appformer/pull/1302
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2065
- https://github.com/kiegroup/appformer/pull/1303

[7.67.x-BLUE] [BXMSPROD-1798] Custom lienzo version property

---

.ci/jenkins/Jenkinsfile.daily

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

[main] replaced jdk11 by jdk11.0.15

---

.ci/jenkins/Jenkinsfile.daily

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

[7.67.x] replaced jdk11 by jdk11.0.15

---

.ci/jenkins/Jenkinsfile.nightly

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1889
Related PRs:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2136
- https://github.com/kiegroup/kie-jenkins-scripts/pull/1374
- https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/225
<details>
<summary>
</summary> …

[7.67.x][BXMSPROD-1889] add stage to create tag in prod repositories in Jenkinsfile.nightly

---

.ci/jenkins/Jenkinsfile.nightly

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1889
Related PRs:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2136
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2148
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2149
<details>
<summary>
</summary> …

[BXMSPROD-1889] add stage to create tag in prod repositories in Jenkinsfile.nightly

---

kie-bom/pom.xml
pom.xml

https://issues.redhat.com/browse/RHPAM-4556
<details>
<summary>
</summary> …

[7.67.x-blue] RHPAM-4556 Remove OptaPlanner related artifacts from kie-bom

---

uberfire-bom/pom.xml

https://issues.redhat.com/browse/BXMSPROD-1845
Related PRs:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2168
* https://github.com/kiegroup/kie-soup/pull/260
* https://github.com/kiegroup/appformer/pull/1368
* https://github.com/kiegroup/kie-wb-common/pull/3793
* https://github.com/kiegroup/drools-wb/pull/1562
* https://github.com/kiegroup/jbpm-wb/pull/1579
* https://github.com/kiegroup/optaplanner-wb/pull/421
* https://github.com/kiegroup/kie-wb-distributions/pull/1209
<details>
<summary>
</summary>
Build Chain tool does "simple" maven …

[7.67.x] [BXMSPROD-1845] elasticsearch removed 

---

uberfire-bom/pom.xml

Back port for
https://issues.redhat.com/browse/BXMSPROD-1845
Related PRs:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2169
* https://github.com/kiegroup/kie-soup/pull/261
* https://github.com/kiegroup/appformer/pull/1369
* https://github.com/kiegroup/kie-wb-common/pull/3794
* https://github.com/kiegroup/drools-wb/pull/1563
* https://github.com/kiegroup/jbpm-wb/pull/1580
* https://github.com/kiegroup/kie-wb-distributions/pull/1210
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, …

[7.67.x-blue] [BXMSPROD-1845] elasticsearch removed from appformer (#2097)

---

pom.xml

**JIRA**:
https://issues.redhat.com/browse/RHPAM-4631
<details>
<summary>
</summary>
[build-chain …

RHPAM-4631 apache cxf to 3.5.5

---

pom.xml

This reverts commit 54850f55fb938476e1d32a771b2ef8d73703606b.
Reverting on 7.x due to Antlr tooling (not runtime) incompatibility with Java 8.
**JIRA**: https://issues.redhat.com/browse/DROOLS-7105
* (revert) https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2189
* (revert) https://github.com/kiegroup/drools/pull/4911
* (revert) https://github.com/kiegroup/kie-wb-common/pull/3797
* (revert) https://github.com/kiegroup/drools-wb/pull/1566
* (revert) https://github.com/kiegroup/kie-wb-distributions/pull/1212
<details>
<summary>
</summary>
Build Chain tool does …

DROOLS-7105 Revert "DROOLS-7105 DMN upgrade to Antlr 4.10 (#2031)"

---

pom.xml

**JIRA**: https://issues.redhat.com/browse/RHPAM-4554
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2112
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2185
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2186
<details>
<summary>
</summary> …

[7.67.x] [RHPAM-4554] upgrade commons-text

---

kie-soup-bom/pom.xml

https://issues.redhat.com/browse/BXMSPROD-1845
* https://github.com/kiegroup/kie-soup/pull/259
* https://github.com/kiegroup/kie-soup/pull/263
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross …

BXMSPROD-1845 kie-soup-dataset-elasticsearch removed kie-soup bom

---

pom.xml

**JIRA**: https://issues.redhat.com/browse/RHPAM-4554
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2112
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2185
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2186
<details>
<summary>
</summary> …

[7.67.x-blue] [RHPAM-4554] upgrade commons-text

---

.ci/actions/build-chain/action.yml
README.md

Resolves https://github.com/kiegroup/github-action-build-chain/issues/325
Upgrade build-chain to latest tag

upgrade build chain to typescript version

---

.ci/actions/build-chain/action.yml
README.md

Reverts kiegroup/droolsjbpm-build-bootstrap#2187

Revert "upgrade build chain to typescript version"

---

pom.xml

**Backport**: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2190
Bumps [keycloak-core](https://github.com/keycloak/keycloak) from 20.0.0 to 20.0.3.
- [Release notes](https://github.com/keycloak/keycloak/releases)
- [Commits](https://github.com/keycloak/keycloak/compare/20.0.0...20.0.3)
---
updated-dependencies:
- dependency-name: org.keycloak:keycloak-core dependency-type: direct:production ...
Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2203
- …

[7.67.x-blue] Bump keycloak-core from 20.0.0 to 20.0.3

---

.ci/actions/build-chain/action.yml
.ci/jenkins/Jenkinsfile.buildchain
.ci/jenkins/Jenkinsfile.daily
.ci/jenkins/Jenkinsfile.release
README.md

This reverts #2198 
To be merged after: 
* https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/259

Upgrade build chain to typescript version - second try

---

pom.xml

**JIRA**: 
https://issues.redhat.com/browse/DROOLS-7331
* https://github.com/kiegroup/drools/pull/4971
<details>
<summary>
</summary> …

[DROOLS-7331] ResultSetGeneratorTest fails with JDK8

---

.ci/jenkins/Jenkinsfile.daily

[main](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2209)
[7.67.x](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2210)
[7.67.x-blue](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2211) 
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are …

[7.67.x] upgraded node version for daily builds

---

.ci/jenkins/Jenkinsfile.daily

[main](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2209)
[7.67.x](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2210)
[7.67.x-blue](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2211) 
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are …

[7.67.x-blue] upgraded node version for daily builds

---

script/release/update-versions-build-chain.sh

(cherry picked from commit 6d139e9a8e5a8f37bfbfcf2e31993cc0db502bf1)
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those …

replaced _ in update version script

---

pom.xml

test the upgrade for https://issues.redhat.com/browse/RHDM-1949
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a …

RHDM-1949: Upgrading plexus-utils to 3.0.24

---

.ci/daily-config.yaml

The first repo is lienzo-core. After checking out all reps and before building lienzo-core the kie version is changed.
Tested locally and it works. This will fix the daily build.
We have to have in mind that each time the order of reps changes we have to do the same change here.
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain …

fix daily build problem

---

.ci/project-dependencies.yaml

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

removed optawebs* from dependant repositories

---

pom.xml

**JIRA**:  
[https://issues.redhat.com/browse/RHDM-1958](https://issues.redhat.com/browse/RHDM-1958)
[https://issues.redhat.com/browse/RHPAM-4641](https://issues.redhat.com/browse/RHPAM-4641)
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2239
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2240
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2241
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any …

[RHPAM-4641] Upgrading RESTEasy version.

---

pom.xml

**JIRA**:  
[https://issues.redhat.com/browse/RHDM-1958](https://issues.redhat.com/browse/RHDM-1958)
[https://issues.redhat.com/browse/RHPAM-4641](https://issues.redhat.com/browse/RHPAM-4641)
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2239
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2240
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2241
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any …

[7.67.x][RHPAM-4641] Upgrading RESTEasy version.

---

pom.xml

**JIRA**:  
[https://issues.redhat.com/browse/RHDM-1958](https://issues.redhat.com/browse/RHDM-1958)
[https://issues.redhat.com/browse/RHPAM-4641](https://issues.redhat.com/browse/RHPAM-4641)
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2239
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2240
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2241
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any …

[7.67.x-blue][RHPAM-4641] Upgrading RESTEasy version.

---

pom.xml

**JIRA**: [JBPM-10166](https://issues.redhat.com/browse/JBPM-10166)
* [jbpm-work-items#276](https://github.com/kiegroup/jbpm-work-items/pull/276)
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version …

[JBPM-10166] Allow tests with productized Kafka version

---

.ci/downstream-production-config.yaml
.ci/full-downstream-config.yaml
.ci/jenkins/Jenkinsfile.buildchain
.ci/jenkins/Jenkinsfile.daily
.ci/jenkins/Jenkinsfile.release
.ci/pull-request-config.yaml

**JIRA**:  https://issues.redhat.com/browse/RHPAM-4431
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2253
* https://github.com/kiegroup/kie-wb-distributions/pull/1214
* https://github.com/kiegroup/kie-wb-distributions/pull/1203
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could …

RHPAM-4431: Session Cookie Without Secure Attribute Set

---

.ci/project-dependencies.yaml

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

kie-parent depends on lienzo-core

---

.github/workflows/branch-compilation.yml
.github/workflows/full-downstream.yml
.github/workflows/pr-backporting.yml
.github/workflows/pull_request.yml

**JIRA**: [https://issues.redhat.com/browse/BXMSPROD-1930](https://issues.redhat.com/browse/BXMSPROD-1930)
**Referenced Pull Requests**: 
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2263
* https://github.com/kiegroup/kogito-pipelines/pull/935
**Notes**:
* The former folders/files are not going to be removed in this PR.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect …

[BXMSPROD-1930] Change references from droolsjbpm-build-bootstrap

---

.ci/jenkins/Jenkinsfile.buildchain
.ci/product-projects-dependencies.yaml

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

[7.67.x-blue] Removed opta reference from product project dependencies

---

.ci/update-versions-release.yaml

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

lienzo-core is now first project

---

.ci/jenkins/Jenkinsfile.release
script/release/10a_drools_upload_filemgmt.sh
script/release/prepareUploadDir.sh
script/release/update-versions-build-chain.sh

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

prepared scripts for next community release

---

pom.xml

**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4688
possible replacement for https://github.com/kiegroup/droolsjbpm-integration/pull/2955
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be …

upgraded version.org.wildfly.security property to 1.15.16.Final

---

script/release/09_createjBPM_installers.sh
script/release/10a_drools_upload_filemgmt.sh
script/release/10b_jbpm_upload_filemgmt.sh

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

fixed path for fetching the right file

---

.github/workflows/generate_files.yml

* https://github.com/kiegroup/build-chain-files-generator/pull/11
* https://github.com/kiegroup/build-chain-files-generator/pull/12
tested by https://github.com/Ginxo/droolsjbpm-build-bootstrap/actions/runs/5444853386/jobs/9903272132 (error from `Create PR` step is expected)
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository …

BC generate files node16

---

pom.xml

**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4733
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool …

[RHPAM-4733][CVE-2023-34455 snappy-java] kafka version to 3.5.0

---

pom.xml

This reverts commit 5c3a8fa0455f44df6eff3f1ff5c1577f098e2db8.
Since `strimzi-test-container:0.104.0` is compiled on jdk11 the build is broken. We will find a different approach for updating kafka
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because …

Revert "[RHPAM-4733][CVE-2023-34455 snappy-java] kafka version to 3.5.0 (#2334)

---

.ci/update-versions-release.yaml

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

fixed script name for bumping up versions

---

.ci/jenkins/Jenkinsfile.release

In case the release branch doesn't exist we don't want to remove all repositories in ../bc after the version update, rather we want to maintain all already checked out repositories  - so in this case we want a `--skipCheckout` when building the projects.
In case the release branch already exists and we don't have to bump-up versions again, the branches will be cloned from GitHub.  In this case `--skipParralelCheckout`
(we had this in opposite way)
* link 2
* link 3 etc.
You can check Kiegroup organization repositories CI status …

skipped checkout when relese branch does not exist yet

---

pom.xml

**JIRA**: [JBPM-10193](https://issues.redhat.com/browse/JBPM-10193)
* https://github.com/kiegroup/kie-wb-common/pull/3819
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to …

JBPM-10193 upgrade maven-jaxb2-plugin for fix PR build failed issue

---

pom.xml

**JIRA**:  https://issues.redhat.com/browse/RHPAM-4816
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool …

[RHPAM-4816] upgrade undertow to 2.2.28.Final

---

pom.xml

**Backport:** https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2390
**JIRA**:  https://issues.redhat.com/browse/RHPAM-4816
<details>
<summary>
</summary> …

[7.67.x_RHPAM-4821] [RHPAM-4816] upgrade undertow to 2.2.28.Final (#2390) (#2392)

---

pom.xml

JIRA: https://issues.redhat.com/browse/RHPAM-4816
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to …

[7.67.x-blue_RHPAM-4821][RHPAM-4816] upgrade undertow to 2.2.28.Final

---

pom.xml

Trying to fix Sonarcloud analysis warnings
```
Analysis status
Last analysis has warnings
The property 'sonar.login' is deprecated and will be removed in the future. Please use the 'sonar.token' property instead when passing a token.
The version of Java (11.0.20) you have used to run this analysis is deprecated and we will stop accepting it soon. Please update to at least Java 17.
Read more [here](https://docs.sonarcloud.io/appendices/scanner-environment/)
```
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just …

replacing old sonar.login with sonar.token property

---

pom.xml

- Bump to mvel 2.5.1.Final
**Ports** 
This is a PR for 7.x.
for 7.67.x ->
for 7.67.x-blue ->
**JIRA**: 
https://issues.redhat.com/browse/DROOLS-7540
* https://github.com/kiegroup/drools/pull/32
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds …

[DROOLS-7540] Coercion from Interger literal to BigDecimal bind variable

---

narayana-integration-bom/pom.xml
pom.xml

**JIRA**: 
https://issues.redhat.com/browse/DROOLS-7598
* https://github.com/kiegroup/droolsjbpm-integration/pull/3007
<details>
<summary>
</summary> …

[DROOLS-7598] Upgrade tomcat version

---

pom.xml

[RHPAM-4812](https://issues.redhat.com/browse/RHPAM-4812)
<details>
<summary>
</summary>
[build-chain …

[RHPAM-4812] Updating kubernetes-client to 6.10.0

---

narayana-integration-bom/pom.xml
pom.xml

Extension of https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2416
<details>
<summary>
</summary>
[build-chain …

tomcat 9.0.83

---

pom.xml

issue: https://github.com/apache/incubator-kie-issues/issues/994

[incubator-kie-issues-994] add in memory token logins

---

pom.xml

cherry-pick from https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2440

[incubator-kie-issues-994] add in memory token logins (#2440) [7.67.x-blue]

---

pom.xml

**JIRA**: 
* https://issues.redhat.com/browse/BXMSPROD-2189
<details>
<summary>
</summary>
[build-chain …

upgraded Spotbugs maven plugin to the latest 4.8.5.0

---

pom.xml

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

[7.67.x-blue] Bumped `bcprov-jdk15to18` from `1.74` to `1.78.1`

---

pom.xml

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

[7.67.x blue] CVE-2023-34462 Upgrade netty-handler

---

pom.xml

<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used locally on command line or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can …

[7.67.x blue] Bump `infinispan` to `11.0.19.Final`

---

pom.xml

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

[7.67.x blue] [CVE] Upgrade xnio-api from 3.8.4 to 3.8.8

---

pom.xml

<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used locally on command line or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can …

[7.67.x-blue] Bumped undertow to `2.2.33.Final`

---

pom.xml

Fixes CVE-2024-31573
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used locally on command line or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related …

[7.67.x-blue] Update to xmlunit 2.10.0

---

pom.xml

Related PR: https://github.com/kiegroup/droolsjbpm-integration/pull/3060

[7.67.x-blue] Update camel to 2.25.4.

---

pom.xml

Upgrading apache poi to version 5.2.1 fixes CVE-2022-26336.
Ensemble:
https://github.com/kiegroup/appformer/pull/1423
https://github.com/kiegroup/drools/pull/76
https://github.com/kiegroup/kie-wb-common/pull/3831
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven …

[7.67.x-blue] - Upgrade apache poi version to 5.2.1

---

pom.xml

Updates the version of infinispan to fix several CVEs. 
Related PR: https://github.com/kiegroup/appformer/pull/1419

[7.67.x-blue] Update infinispan to 14.0.27.Final.

---

pom.xml

Depends on https://github.com/errai/errai/pull/466 (a new errai release is required) 
Ensemble: 
- https://github.com/kiegroup/lienzo-core/pull/185
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2464
- https://github.com/kiegroup/lienzo-tests/pull/149
- https://github.com/kiegroup/drools/pull/72
- https://github.com/kiegroup/appformer/pull/1420
- https://github.com/kiegroup/kie-wb-common/pull/3830
- https://github.com/kiegroup/drools-wb/pull/1574
- https://github.com/kiegroup/kie-wb-distributions/pull/1246
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect …

[7.67.x-blue] bumped `guava` to `33.2.1` and `GWT` `2.11.0`

---

pom.xml

* Update undertow related PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2482
Referenced PRs:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2490
* https://github.com/kiegroup/appformer/pull/1424
* https://github.com/kiegroup/kie-wb-common/pull/3832
<details>
<summary>
</summary> …

Backports of CVEs

---

pom.xml

security
* link 2
* link 3 etc.
<details>
<summary>
</summary> …

[7.67.x-blue] Downgrade spring-security to `5.7.11`

---

pom.xml

Upgrading to latest available netty version. This would require to update netty version during productization CI.
* link 2
* link 3 etc.
<details>
<summary>
</summary> …

[7.67.x-blue] DBACLD-164366: [CVE] [Medium] CVE-2024-47535 netty-common-4.1.108.Final-redhat-00001.jar

---

pom.xml

[**NOTE**] - The fix for the CVE is available in JDOM 2.0.6.1, hence it's required to [migrate to JDOM2](https://github.com/hunterhacker/jdom/wiki/JDOM2-Migration-Issues).
Related PR: https://github.com/kiegroup/appformer/pull/1433
**JIRA**: https://jsw.ibm.com/browse/DBACLD-164330
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because …

DBACLD-164330: [CVE] [High] CVE-2021-33813 and more jdom-1.1.3.redhat-3.jar

---

pom.xml

This upgrades Spring to version 5.3.39.

[7.67.x-blue] Update Spring to version 5.3.39.

---

pom.xml

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

[7.67.x-blue] Bump `cxf` to version `3.5.10`

---

pom.xml

[link](https://jsw.ibm.com/browse/DBACLD-164361)
* link 2
* link 3 etc.
<details>
<summary>
</summary> …

DBACLD-164361: kafka CVE fix

---

pom.xml

**JIRA**: _(https://jsw.ibm.com/browse/DBACLD-164354)_

[DBACLD-164354] Bump xerces version from 2.12.0.SP04 to 2.12.2

---

pom.xml

Upgrade tomcat-embed artifacts to fix multiple CVEs
Needed by https://github.com/kiegroup/droolsjbpm-integration/pull/3077
<details>
<summary>
</summary>
[build-chain …

[NO_ISSUE] Embed-tomcat related multiple CVES

---

pom.xml

referenced PRs:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2563
* https://github.com/kiegroup/appformer/pull/1443
<details>
<summary>
</summary>
[build-chain …

[NO-ISSUE]: Fix okhttp3 mockserver tests on uberfire.nio2.k8s
